krb5/krb5

src/tests/t_otp.py

Declare User-Password as having type "octets" instead of "string" or
pyrad 2.x will throw a decoding error when retrieving it.

Fix OTP tests with pyrad 2.x

---

src/util/profile/prof_get.c

In profile_iterator(), return PROF_MAGIC_ITERATOR if *iter_p is NULL,
instead of dereferencing a null pointer, as we did prior to 1.10.
Correct calling code will not trigger this case, but incorrect code
has been reported in the field.

Check for null *iter_p in profile_iterator()

---

src/lib/krb5/ccache/cc_file.c

In fcc_destroy and krb5int_fcc_new_unique, call set_errmsg_filename
before deleting the cache handle, or else the reference to
data->filename is a use after free.
In set_errmsg_filename, do nothing if the code is 0, as we don't have
an error to annotate.

Fix bugs in previous cc_file.c changes

---

src/lib/krb5/krb/get_in_tkt.c
src/tests/t_general.py

Simo's commit, not reviewed or edited.

Do not loop on principal unknown errors

---

src/kdc/do_tgs_req.c
src/kdc/tgs_policy.c
src/lib/krb5/asn.1/asn1_k_encode.c
src/tests/asn.1/krb5_decode_test.c

The EncTicketPart decoder sets starttime to authtime if it wasn't
included in the ASN.1 value.  This is problematic for upcoming CAMMAC
work, as we will need to re-encode a received EncTicketPart to check
the KDC verifier.  Remove that behavior and just use opt_kerberos_time
for the starttime field.  Adjust krb5_decode_test.c to match the new
decoder behavior.
Similarly, remove the process_tgs_req() code which sets starttime in
the header ticket if it isn't set.  Add a comment explaining the
unrelated code adjacent to it.
check_tgs_times() used the ticket starttime without checking if it was
present.  Add a fallback to times->authtime, and narrow the function
contract to make the implementation more concise.
There is a similar hack in the EncKDCRepPart decoder; leave that alone
for now.

Remove starttime hack in EncTicketPart decoder

---

src/include/kdb.h

Commit ab009b8568d9b64b7e992ecdb98114e895b4a7ff for issue #7977
changed the signature of krb5_db_iterate() and properly bumped
KRB5_KDB_API_VERSION from 7 to 8.  It also changed the signature of
the DAL iterate() function, but did not bump
KRB5_KDB_DAL_MAJOR_VERSION.  Bump that version from 4 to 5 now.

Bump DAL major version for iterate change

---

src/tests/gssapi/t_prf.c

In t_prf.c, make sure that the partially initialized, faked-up
structures gss_union_ctx_id_desc and krb5_gss_ctx_id_rec are zeroed.
This avoids uninitialized reads in gss_pseudo_random(), which can
cause intermittent test failures on some platforms.

Avoid uninitialized data in t_prf.c

---

src/configure.in

Check a few portability assumptions: integers are two's complement,
unsigned-to-signed conversions preserve representations, and bytes are
8 bits.

Add configure checks for portability assumptions

---

src/kadmin/cli/ss_wrapper.c

In ss_wrapper.c, if ss_execute_command() returns an error, we should
call ss_perror() with *args as the third argument and not request
(which is NULL).  Expand out the conditional into three commented
branches for greater clarity, since the error-handling is no longer
identical for the ss_execute_command() and ss_execute_line() cases.

Fix kadmin script mode command-not-found error

---

src/lib/kadm5/srv/server_acl.c
src/tests/t_kadmin_acl.py

In kadm5int_acl_find_entry(), clear the wildcard back-references list
for each acl entry.  Otherwise the wildcards we process can affect
back-references for later entries.

Fix scope of kadmind ACL wildcard back-references

---

src/lib/kadm5/clnt/client_init.c
src/lib/kadm5/clnt/client_rpc.c
src/lib/rpc/clnt_generic.c

The first commit is intended to be backportable by downstreams, although I'm not sure we need to backport it ourselves as it isn't really a bugfix.  The second commit is mostly just code hygiene, although it affects the behavior of clnt_create() which we don't use within the tree.

Extend kadmin timeout to one hour

---

doc/admin/admin_commands/kpropd.rst
src/slave/kpropd.c
src/tests/t_iprop.py
src/util/k5test.py

Here is John Devitofranceschi's commit from RT #8161, unmodified.
It's a good proof of concept; it demonstrates that since the listener child process will exit after accepting a full dump, the master process can simply wait for it to exit.  However, in addition to having some style issues, it is a bit too hackish:
* Most problematically, it contains a recursive call to main(), which is not a  safe practice.
* The meaning of waitfor_do_standalone is not well-stated; it begins at 0, is incremented to 1 when the first full dump is requested, and is incremented again to 2 after the full dump is complete (and possibly again to 3 if another dump is requested).  When the patch uses it, it specifically compares it to 1.  So it's implicitly a tri-state, beginning life at "no dump was requested", …

kpropd -t full dump patch

---

src/lib/kdb/kdb_log.c
src/lib/kdb/t_ulog.c
src/slave/kproplog.c
src/tests/t_iprop.py

The first three commits are from PR #267.
The last commit resolves the second "related problem" documented at http://k5wiki.kerberos.org/wiki/Projects/Hierarchical_iprop#Related_problems
(the first problem is resolved by PR #267) by creating dummy entries after header resets.

Avoid unnecessary iprop full resyncs after resets

---

src/lib/gssapi/generic/gssapi_generic.c

In gssapi_generic.c, struct mech_attr_info_desc included some
gss_buffer_desc members whose length fields were never used.
Additionally, the STRING_BUFFER() macro's computation of the (unused)
length fields was incorrect, causing warnings in some versions of
clang.  Remove the problematic STRING_BUFFER() macro and adjust the
array and generic_gss_display_mech_attr() accordingly.

Remove STRING_BUFFER() macro in gssapi_generic.c

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_tkt_policy.c

krb5_ldap_get_value() takes a pointer to int, and should not be passed
a pointer to any integral type which might have a different width.
Use an intermediate variable for each call.
The erroneous calls in ldap_misc.c were passing pointers to int32_t,
which is harmless on all common platforms.  The calls in
ldap_tkt_policy.c were passing pointers to long; on big-endian LP64
platforms, the result would be written to the high 32 bits of the long
value.

Fix LDAP ticket policies on big-endian LP64

---

doc/formats/keytab_file_format.rst
src/include/k5-int.h
src/include/kdb.h
src/lib/kadm5/kadm_rpc_xdr.c
src/lib/kadm5/srv/adb_xdr.c
src/lib/kdb/kdb_convert.c
src/lib/kdb/kdb_cpw.c
src/lib/krb5/asn.1/ldap_key_seq.c
src/lib/krb5/keytab/kt_file.c
src/plugins/kdb/ldap/libkdb_ldap/princ_xdr.c
src/tests/t_keytab.py

This started out as a plan to just implement the 32-bit keytab kvno extension, but wound up becoming a larger overhaul as I discovered other limitations.  Each of the five commits is still fairly short.  For more background, see:
http://k5wiki.kerberos.org/wiki/Projects/Larger_key_versions

Larger kvno support

---

src/plugins/kdb/db2/kdb_db2.c

Use the correct function to free the decoded principal entry in
curs_run_cb().

Fix memory leak in DB2 iteration

---

src/lib/krb5/ccache/cc_mslsa.c
src/lib/krb5/os/Makefile.in
src/lib/krb5/os/hostrealm.c
src/lib/krb5/os/hostrealm_registry.c
src/lib/krb5/os/os-proto.h
src/windows/installer/wix/athena/krb5.ini
src/windows/installer/wix/kfw.wxs
src/windows/installer/wix/site-local.wxi
src/windows/kerberos.ver
src/windows/leash/Leash.rc

A couple fixes that had been sitting around in my local branch, plus adding support for a registry value for the default realm, and bumping the release number to 4.1.x.  Notably, do not set allow_weak_crypto in the MIT-internal krb5.ini any more.

Kfw updates

---

src/lib/rpc/bindresvport.c

The sa_setport() helper handles conversion to network byte order, so
bindresvport_sa() should not itself call htons() on the port argument.
(This bug was introduced in commit
0d04b60d159ab83b943e43802b1449a3b074bc83 when adding
bindresvport_sa().  It was my fault, not Andreas Schneider's.)

Fix bindresvport_sa port byte swap bug

---

src/lib/gssapi/mechglue/g_acquire_cred_with_pw.c

The target_mechs array needs to be freed on successful return.

Fix leak in gss_acquire_cred_with_password

---

src/appl/gss-sample/t_gss_sample.py
src/lib/gssapi/krb5/acquire_cred.c

gss_acquire_cred_with_password() was originally introduced in Solaris.
When we introduced it in 1.9, we unfortunately gave it different and
less useful semantics.  Restore this function to the Solaris
semantics, which are to always get credentials and store them in a
private memory ccache.  The caller can use gss_store_cred() to make
the resulting creds visible to other processes if desired.

Use memory cache in gss_acquire_cred_with_password

---

src/plugins/preauth/pkinit/pkinit_clnt.c

crypto_retrieve_cert_sans() is allowed to set its princs output to
NULL, although the OpenSSL implementation rarely does.  Fix the
TRACE_PKINIT_CLIENT_SAN_KDCCERT_PERT for loop to allow this like other
parts of the function do, and also get rid of the unnecessary princptr
variable by using an integer index like other parts of the function.

Fix uncommon null dereference in PKINIT client

---

src/kdc/kdc_preauth.c

Commit be20a5f5cee8d6c4072d1b81712520dbf9f6eefd made
load_preauth_plugins() handle negative preauth type numbers.
get_plugin_vtables() also needs to handle negative preauth type
numbers, or it returns the wrong count.

Fix kdcpreauth counting bug

---

src/kadmin/server/ipropd_svc.c

kadmind should be quiet in nofork mode after it prints the
"starting..." sentinel line, or it can fill the pipe buffer when run
from k5test.py.  Since there is currently no run-time debuf flag,
conditionalize the DPRINT macro in ipropd_svc.c on DEBUG at compile
time.

Conditionalize iprop stderr output in kadmind

---

src/appl/gss-sample/gss-client.c
src/lib/gssapi/mechglue/g_acquire_cred.c
src/lib/gssapi/spnego/spnego_mech.c
src/tests/gssapi/t_spnego.c

Filter out mechs with the GSS_C_MA_DEPRECATED attribute from the set of mechanisms obtained by SPNEGO, and from the set used when gss_acquire_cred() is called with no desired_mechs attribute.
SPNEGO acceptors will still accept the old and wrong krb5 OIDs, but SPNEGO initiators will not offer them.  According to [MS-SPNG], only Windows 2000 does not recognize the standard krb5 OID, and it is client-only.
In gss-client.c, use the standard krb5 OID for the -krb5 option, as acceptors who call gss_acquire_cred()  with no desired_mechs to create an acceptor cred will no longer accept the old or wrong krb5 OIDs.
[There is also a first commit to make t_spnego.c work under the new regime.  Unfortunately it requires even more knowledge of SPNEGO encoding details in the test program.]

Limit use of deprecated krb5 mech OIDs

---

doc/admin/auth_indicator.rst
doc/admin/otp.rst
src/plugins/preauth/otp/otp_state.c
src/tests/t_otp.py

To better support integration with FreeIPA, allow authentication
indicators to be specified in the "otp" string attribute, overriding
any indicators in the token type.

Support OTP auth indicators in string attribute

---

src/include/krb5/krb5.hin

Use [out] instead of [in] for the output parameters of
krb5_c_prfplus() and krb5_c_derive_prfplus().  Also use "out" instead
of "output" for krb5_c_derive_prfplus() to match the parameter name in
the definition.

Fix new doxygen parameter lists

---

src/lib/krb5/krb/s4u_creds.c
src/tests/gssapi/t_s4u.py

When sending a S4U2Self query to a foreign realm, send an enterprise
server principal so that the foreign KDC can identify the home realm
of the server principal.
To make this work, adjust the memory management of
krb5_get_self_cred_from_kdc().  s4u_creds is now a shallow copy of
in_creds which owns no memory.  A new variable eprinc owns the
enterprise form of the server principal, constructed using a new
helper function convert_to_enterprise().  Since we have to set the
server realm for KDC-REQ encoding to work, a new temporary variable
sprinc holds a shallow copy of *eprinc with the realm pointing to the
realm we are currently querying.
Based on a patch by Sumit Bose.

Make cross-realm S4U2Self work

---

src/lib/gssapi/mechglue/g_accept_sec_context.c
src/tests/gssapi/t_spnego.c

After tickets #8021 and #8217, a GSS server app which calls gss_acquire_cred(..., GSS_C_ACCEPT, ...) and gss_accept_sec_context() will not accept tokens framed with the old or wrong krb5 OIDs or IAKERB tokens; the intention is that you have to ask for those mech OIDs specifically in order to use them.  However, a server which calls gss_accept_sec_context() with no acceptor cred still accepts any mech.  This pull request makes the behavior consistent between the two usages, and finishes removing IAKERB from the exposed surface of a default GSS server application.
t_spnego.c needs a change for this to work.  Microsoft clients which use the wrong krb5 OID still use the correct OID in the mech token, and our test needs to match that behavior or the mech token will be rejected by the inner …

Disallow IAKERB, old/wrong krb5 mechs in gss_accept_sec_context() with no acceptor cred

---

src/kdc/kdc_preauth.c
src/plugins/preauth/test/cltest.c
src/plugins/preauth/test/kdctest.c
src/tests/etinfo.c
src/tests/t_etype_info.py

These commits include etype-info2 information in a MORE_PREAUTH_DATA_REQUIRED error when the client performs optimistic preauth.  This is a preqrequisite for SPAKE preauth.

Send etype-info2 with MORE_PREAUTH_DATA_REQUIRED sometimes

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_trace.h

When a non-trivial OpenSSL function fails during PKINIT processing,
try to ensure that the error message includes an indication of the
what PKINIT was doing and the reason for the first queued OpenSSL
error, and flush all queued OpenSSL errors to the trace log.  For
certificate verification failures, also include the higher-level error
from the cert store.  Add new helper functions oerr() and oerr_cert()
to minimize the amount of code needed to handle each error.
(Inspired by http://mailman.mit.edu/pipermail/kerberos/2015-September/020946.html and http://mailman.mit.edu/pipermail/kerberos/2015-September/020951.html)

Improve PKINIT OpenSSL error reporting

---

doc/admin/admin_commands/kdb5_util.rst
src/kadmin/dbutil/Makefile.in
src/kadmin/dbutil/kdb5_util.c
src/kadmin/dbutil/kdb5_util.h
src/kadmin/dbutil/t_tdumputil.c
src/kadmin/dbutil/t_tdumputil.py
src/kadmin/dbutil/tabdump.c
src/kadmin/dbutil/tdumputil.c
src/kadmin/dbutil/tdumputil.h
src/tests/Makefile.in
src/tests/t_tabdump.py

This new kdb5_util tabdump command provides a reporting-friendly
tabular dump format for the KDC database.  This format is also
suitable for importing into relational databases for queries.  Output
is in tab-separated or CSV format.  The user can select an output
table with a fixed number of columns.
Currently, only provide tables for a subset of available principal
data.  This includes making visible some data that is hidden in
hexadecimal strings in the tl_data of the ordinary dump format.

Add tabular dump capability to kdb5_util

---

src/configure.in

We now require stdint.h to build this software.  Gracefully fail
during configure time if stdint.h is missing.
ticket: 8221
target_version: 1.14
tags: pullup

Fail during configure if stdint.h missing

---

src/aclocal.m4
src/kadmin/cli/ss_wrapper.c

The libss in e2fsprogs exports ss_execute_command(), but does not
prototype it (as of this writing; a patch has been submitted
upstream).  When using the system ss library, check if a prototype is
needed and provide one if so.

Fix kadmin with e2fsprogs libss

---

src/clients/ksu/main.c

Some older platforms (OS X 10.4, glibc 2.2.1) declare unsetenv() as
returning void, as does ksu's compatibility definition of unsetenv().
Don't use the return value in get_configured_defccname().

Make ksu work when unsetenv() returns NULL

---

src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/inq_context.c

Remove an unnecessarily strict check for ticket expiration from
kg_accept_krb5() and kg_accept_dce().  Instead, add the maximum
allowable clock skew to the reported lifetime of krb5 contexts.

Allow clock skew in krb5 gss_accept_sec_context()

---

src/include/k5-int.h
src/kdc/fast_util.c
src/lib/krb5/krb/kfree.c
src/lib/krb5/libkrb5.exports
src/plugins/preauth/test/kdctest.c

I noticed the lack of sanitization when making the prototype SPAKE preauth module, and noticed a couple of memory leaks while fixing the sanitization issue.

Secure cookie memory hygiene and a couple of memory leak fixes

---

.gitignore
src/tests/Makefile.in
src/tests/deps
src/tests/icred.c
src/tests/localauth.c
src/tests/t_general.py
src/tests/t_localauth.py

I've been meaning to correct this minor annoyance for a while, and since I will be amending t_init_creds.c for SPAKE preauth tests, I figured now is a reasonable time.

Rename two test programs for consistency

---

src/configure.in
src/include/k5-int.h
src/lib/kdb/kdb_default.c
src/lib/krb5/keytab/kt_file.c
src/lib/krb5/keytab/kt_srvtab.c

As we no longer support pre-C89 platforms, assume that the fopen "b"
flag is always allowed.
Supersedes PR #353.

Remove ANSI_STDIO conditional

---

src/lib/krb5/ccache/ccmarshal.c

Opinions are welcome on whether this should get a ticket and be marked for backport.

Fix FILE ccache negative enctype unmarshalling

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c

Commit ebcdf02f8ec212555b1762007fa8454615900f36 incorrectly used
k5_prependmsg() in an error handling clause in
krb5_ldap_get_principal().  Use k5_wrapmsg() instead.
ticket: 8301
tags: pullup

Correctly use k5_wrapmsg() in ldap_principal2.c

---

src/lib/crypto/nss/enc_provider/enc_gen.c

I ran across a bug in the NSS k5crypto back end while running it through the test suite.  I don't think anyone uses this back end, but here is a fix.

Fix NSS k5crypto iov procesing bug

---

src/lib/gssapi/spnego/gssapiP_spnego.h
src/lib/gssapi/spnego/spnego_mech.c

Nico's IAKERB/SPNEGO patches contained two small SPNEGO code cleanup commits; this pull request combines them into one commit since they are thematically similar.  The unused fields are also present and unused in 1.5 and in my checkout of the Solaris code.  I assume they are development vestiges from when the code was first written.

Remove unused SPNEGO context fields

---

src/aclocal.m4
src/lib/kadm5/srv/server_acl.c
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.c

gcc has no option (short of -Werror) to error on "makes pointer from
integer without a cast" warnings, but clang does.  In aclocal.m4, add
"error=int-conversion" to the warning flags we try to use.

Error on int-conversion with clang

---

src/include/k5-utf8.h

[This should hopefully fix the build under gcc 5.x, which appears to have been broken by PR #364.]
krb5 contains some Unicode code adapted from OpenLDAP.  OpenLDAP uses
unsigned types for UCS-2 and UCS-4 code points, but the adapted code
uses signed types, which creates pointer-sign warnings when we call
uccompatdecomp() and similar functions.  To match the OpenLDAP code,
use unsigned types.

Make krb5_ucs2 and krb5_ucs4 unsigned

---

src/lib/kdb/kdb_cpw.c
src/lib/krb5/krb/chpw.c

Some password-changing library functions take a const char * parameter
but try to assign it to krb5_data.data, which isn't const.  PR #364
causes some compilers to produce errors in such situations, so cast
away the constness.  This is almost certainly safe because of the
nature of the code that consumes these krb5_data values.
The first commit in this PR is already included in #367.

Cast away constness when assigning to krb5_data

---

src/config/pre.in
src/config/shlib.conf

Cross compilation environments might not be using the default nm
command.  Rather than try to communicate the correct value to
util/export-check.pl, only run export-check.pl in maintainer mode.
This supersedes PR #271.

Only run export-check.pl in maintainer mode

---

.gitignore
src/util/support/Makefile.in
src/util/support/t_utf8.c
src/util/support/utf8.c

Unicode and ISO/IEC 10646 now agree that the maximum valid code point
is U+10FFFF.  (Unicode 8.0 Appendix C.2 implies that ISO/IEC
10646:2011 aligned the extent of the code space.)
Adjust src/util/support/utf8.c accordingly, mostly by
deleting code.
Also delete the unused macro KRB5_UCS_UTF8LEN().

Modernize UTF-8 conversions

---

src/lib/krb5/ccache/cc_kcm.c

Some versions of clang erroneously detect use of an uninitialized
variable reply_len in kcmio_call() when building on non-Mac platforms.
Initialize it to work around this warning.
ticket: 8335 (new)

Work around uninitialized warning in cc_kcm.c

---

src/appl/simple/client/sim_client.c
src/kadmin/server/ipropd_svc.c

Testing in Travis CI reveals that sim_client and iprop don't deal well with FQDNs longer than MAXHOSTNAMELEN.

MAXHOSTNAMELEN is too short for some FQDNs

---

.travis.yml

Do Travis CI testing with clang and gcc, on 64-bit Ubuntu Trusty.
Performance would probably be better using the container-based Travis
infrastructure, but that is currently limited to Precise, and we would
need some important apt packages whitelisted, e.g., dejagnu.

Add .travis.yml [KRB-42]

---

src/clients/ksu/krb_auth_su.c

Commit 5fd5a67c5a93514e7d0a64425baa007ad91f57de switched ksu from
using krb5_get_in_tkt_with_password() to
krb5_get_init_creds_password(), but did not supply a prompter
argument.  Pass krb5_prompter_posix so that clpreauth modules can
prompt for additional information during authentication.

Make ksu work with prompting clpreauth modules

---

src/lib/gssapi/spnego/spnego_mech.c

After the initial call to spnego_gss_init_sec_context(), the context
handle can leak if init_ctx_cont() returns an error, because the
cleanup handler assumes that spnego_ctx contains the value of
*context_handle.  Fix this leak by setting spnego_ctx before the if
block which contains that call.  Reported by Adam Bernstein.

Fix memory leak in SPNEGO gss_init_sec_context()

---

src/lib/kadm5/logger.c

gcc 4.6.3 erroneously detects uninitialized use of the variable f
after commit 9914b93516bbce9b1123ed5f9f796b7028944892.  Initialize it
to work around this warning.

Work around uninitialized warning in logger.c

---

src/kadmin/server/ipropd_svc.c

The ipropd stubs free client_name and server_name in the cleanup
handler, so should not free them in out-of-memory conditions.
Reported by Will Fiveash.

Fix iprop server stub error management

---

src/clients/kpasswd/ksetpwd.c

In ksetpwd (which we do not install), fix the loop which reads the new
password twice until they match.  Previously it would stop with a
dangling pointer to freed memory in new_password if they don't match
on the first try.  Reported by Will Fiveash.

Fix ksetpwd password reading loop

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c

The most recent commit introduced a new variable princ_ent in
populate_krb5_db_entry().  princ_ent is cleaned up by the function's
cleanup label, so it must be initialized before any "goto cleanup"
statements.
(Discovered by Coverity after PR #399 was pushed to master.)

Fix populate_krb5_db_entry() princ_ent init

---

src/include/k5-thread.h
src/lib/apputils/net-server.c
src/lib/crypto/ISSUES
src/lib/crypto/builtin/des/ISSUES
src/lib/crypto/builtin/md4/ISSUES
src/lib/crypto/builtin/md5/ISSUES
src/lib/crypto/builtin/sha1/ISSUES
src/lib/kadm5/logger.c
src/lib/kadm5/srv/server_acl.c
src/lib/krb5/ccache/ser_cc.c
src/lib/krb5/keytab/kt_file.c
src/lib/krb5/krb/chk_trans.c
src/lib/krb5/krb/ser_actx.c
src/lib/krb5/krb/ser_adata.c
src/lib/krb5/krb/ser_addr.c
src/lib/krb5/krb/ser_auth.c
src/lib/krb5/krb/ser_cksum.c
src/lib/krb5/krb/ser_ctx.c
src/lib/krb5/krb/ser_key.c
src/lib/krb5/krb/ser_princ.c
src/lib/krb5/krb/serialize.c
src/lib/krb5/krb/str_conv.c
src/lib/krb5/rcache/ser_rc.c
src/plugins/preauth/pkinit/pkcs11.h
src/util/et/ISSUES
src/util/t_array.pm
src/util/t_bimap.pm
src/util/t_enum.pm
src/util/t_tsenum.pm
src/windows/lib/cacheapi.h

Some older code in the tree uses form feed characters.  kdevelop does
not appear to preserve them, and it is not our current practice to use
them, so get rid of them in almost all files under src.  Leave alone
lib/gssapi/krb5/3des.txt, which is a formatted internet draft.

Remove form feed characters

---

src/lib/krb5/krb/gic_opt.c

struct extended_options in gic_opt.c extends krb5_get_init_creds_opt.
On Mac OS X, for historical reasons, we define krb5_get_init_creds_opt
with an alignment/packing of 2, conflicting with the compiler default.
This results in alignment change warnings from clang on Mac OS X.
Ensure that extended_options has the same packing.

Harmonize struct packing for gic_opt.c

---

src/lib/apputils/udppktinfo.c
src/lib/apputils/udppktinfo.h

Move is_socket_bound_to_wildcard() into an #if block so it doesn't get
build when it isn't used.  Avoid using the identifier "socket" as it
can produce shadowed declaration warnings.  Make the definition of the
fallback send_to_from() conform to the declaration.

Fix compilation issues in udppktinfo.c

---

src/lib/krb5/os/dnsglue.c

In dnsglue.c (which is used to look up SRV and TXT records), increase
the initial buffer size guess from 2048 to 4096 to accomodate DNSSEC
signatures.  Suggested by Daniel Colascione.

Increase initial DNS buffer size

---

src/plugins/kdb/db2/kdb_db2.c

In 1.11 we switched from non-blocking to blocking locks in the DB2
module, but we missed one call to krb5_lock_file() in ctx_create_db().
This non-blocking lock can cause krb5_db_promote() to fail if the
database is locked when we try to promote the DB, in turn causing
kdb5_util load to fail.  Correct this call to make krb5_db_promote()
more robust.
ticket: 8367 (new)
tags: pullup

Use blocking lock when creating db2 KDB

---

src/tests/t_kprop.py

The listprincs check was at the wrong indentation level and had the
wrong argument grouping; fix it so we actually verify the propagation.
Stop using the -t (runonce) flag to kpropd, so that kpropd continues
to run until k5test.py terminates it.  Quit out of the read loop when
we see that the load process is completed, instead of looking for end
of input.  This change is needed in order to add hooks in k5test.py
for checking daemons for memory leaks before terminating them.

Fix and adjust t_kprop.py

---

src/lib/Makefile.in
src/windows/kfwlogon/Makefile.in

The new Makefile conditionals in commit
4552159e97007a45370dd49fa6b9fb963bb7d160 don't behave properly if
VISUALSTUDIOVERSION isn't set, probably due to the way nmake orders
macro expansion and boolean short circuiting.  Use nested conditionals
instead.

Fix Makefiles for VS2010 KfW build

---

src/lib/crypto/krb/verify_checksum.c

Not sure how I missed this in 07d68eec2788bfe80686608813f644838707c168.

Use k5_bcmp in krb5_k_verify_checksum()

---

src/include/krb5/krb5.hin
src/lib/crypto/crypto_tests/t_cf2.c
src/lib/crypto/crypto_tests/t_cksums.c
src/lib/crypto/crypto_tests/t_cmac.c
src/lib/crypto/crypto_tests/t_decrypt.c
src/lib/crypto/crypto_tests/t_derive.c
src/lib/crypto/crypto_tests/t_fork.c
src/lib/crypto/crypto_tests/t_kperf.c
src/lib/crypto/crypto_tests/t_prf.c
src/lib/crypto/crypto_tests/t_prng.c
src/lib/crypto/crypto_tests/t_str2key.c
src/lib/crypto/krb/verify_checksum.c

A checksum type of 0 means to use the mandatory checksum type in
krb5_k_make_checksum(), krb5_k_make_checksum_iov(), and
krb5_k_verify_checksum_iov().  Extend this meaning to
krb5_k_verify_checksum() for the checksum type in the krb5_checksum
argument.  This change also applies to krb5_c_verify_checksum().
Add code to t_cksums.c to test checksum verification, including with
checksum type 0 for applicable test cases.

Allow zero cksumtype in krb5_k_verify_checksum()

---

src/lib/gssapi/mechglue/g_mechattr.c

[Tom: I'm putting this in ticket: 8358 along with the previous change to gss_inquire_attrs_for_mech(), since we haven't yet included ticket 8358 in any release.  Let me know if I should use a separate ticket instead.]
In gss_inquire_attrs_for_mech(), if the mech does not implement RFC
5587, return success with empty mech_attrs and known_mech_attrs sets
to indicate a lack of knowledge for all attributes.  The previous
behavior of returning an error caused gss_indicate_mechs_by_attr() to
fail out in the presence of an old mechanism, in turn causing
gss_acquire_cred() and SPNEGO to break.

Revisit inquire_attrs_for_mech on old mechs

---

doc/formats/keytab_file_format.rst
src/lib/krb5/keytab/kt_file.c

The key length and count of principal components are 16-bit fields.

Fix keytab file format description

---

appveyor.yml
src/Makefile.in
src/util/wshelper/resource.rc
src/windows/Makefile.in

appveyor.com is a hosted continuous integration service for Windows.
Add an appveyor.yml file containing build instructions.  The appveyor
virtual machines do not include the MFC libraries, so change
util/wshelper/resource.rc to avoid including <afxres.h> (which it does
not need) and add a build conditional for leash.
Right now we do not build the installers; the appveyor VMs do not
appear to have the version of the WiX toolkit we need, and we would
also have problems with the missing leash executable.

Integrate with appveyor for Windows CI

---

appveyor.yml

The directory that AppVeyor does checkouts into can vary.  Use the
documented APPVEYOR_BUILD_FOLDER environment variable instead of
hardcoding a value.

Use APPVEYOR_BUILD_FOLDER

---

src/plugins/kdb/ldap/ldap_util/kdb5_ldap_services.c
src/plugins/kdb/ldap/ldap_util/kdb5_ldap_services.h

kdb5_ldap_util stashsrvpw has several inconsistencies with the
password file determination in libkdb_ldap, and could try to fopen() a
NULL filename in some cases.  Factor out the determination of the
configured password file and make it consistent with libkdb_ldap.
DEF_SERVICE_PASSWD_FILE is no longer used after these changes, as it
is not respected by libkdb_ldap.

Fix kdb5_ldap_util stashsrvpw password file logic

---

src/include/krb5/krb5.hin

[Unfortunately I didn't catch these issues on my final pass over PR #423.]
In the Doxygen comments for the new APIs and types, include @version
tags indicating that they are new in 1.15, and put @param declarations
just after the brief message for consistency with other comments.

Amend KDC hook documentation

---

src/lib/krb5/krb/gic_pwd.c
src/util/k5test.py

I think I've seen people complain about printing com_err messages on keyboard interrupts in the past, but we don't seem to have an existing ticket for it, so maybe it was out of band.  Anyway, it's been annoying me for years, so the first commit fixes that.  (I thought we also did fallback-to-master on keyboard interrupts, therefore attempting to read the password twice, but I can't reproduce this and we explicitly avoid fallback on KRB5_LIBOS_PWDINTR in gic_pwd.c, so I must be misremembering.)
The second commit also fixes a personal annoyance in the test suite.  Displaying stack traces on keyboard exit is a universal problem for Python scripts which don't explicitly avoid it.  Fortunately, we can solve this problem in k5test.py by installing a signal handler, and avoid having to wrap …

Cleaner handling of keyboard interrupts

---

doc/admin/admin_commands/kadmin_local.rst
src/kadmin/cli/getdate.y
src/kadmin/cli/kadmin.c
src/kadmin/cli/kadmin.h
src/tests/Makefile.in
src/tests/t_kadmin_parsing.py

When parsing time intervals in kadmin commands, try
krb5_string_to_deltat() first, then fall back to subtracting the
current time from get_date().  If we do fall back, treat "never" as a
zero interval, and error out rather than yield a huge interval if
get_date() returns a time in the past.
Notable behavior differences: bare numbers of seconds and suffixed
numbers (e.g. "5m" or "6h") are now supported for all intervals;
HH:MM:SS and HH:MM are now treated as intervals rather than absolute
times with the current time subtracted.

Improve kadmin parsing of time intervals

---

src/lib/gssapi/krb5/gssapiP_krb5.h
src/lib/gssapi/krb5/gssapi_krb5.c
src/lib/gssapi/krb5/gssapi_krb5.h
src/util/gss-kernel-lib/kernel_gss.c

gssapi_krb5.h declared some well-known OID constants as pointers to
const gss_OID_desc, which can't be assigned to application-declared
gss_OID variables or passed to GSSAPI functions without causing
warnings.
Declare these OID constants without the const qualifier on
gss_OID_desc, at the expense of some type safety.  (Fixing this
"correctly" probably requires some standards revision.)
ticket: 8399 (new)

Unconstify some krb5 GSS OIDs

---

doc/admin/conf_files/kdc_conf.rst
src/configure.in
src/include/k5-int.h
src/lib/kadm5/logger.c

Two commits here: one to remove some unnecessary conditionalization in logger.c, and another to add the debug relation.

Add debug message filtering to krb5_klog_syslog

---

src/util/cstyle-file.py

emacs_reindent() is intended to fail gracefully when emacs is not
installed, but instead subprocess.call() throws an OSError.  Check for
this error and return normally.

Fix cstyle-file.py when emacs is not installed

---

src/lib/Makefile.in
src/windows/kfwlogon/Makefile.in

When building with VS2015 and NODEBUG is not set, link with the
debugging versions of ucrt.lib and vcruntime.lib.  Based on work by
Chris Kingsley.

Link correct VS2015 C libraries for debug builds

---

src/include/kdb.h
src/kadmin/dbutil/dump.c
src/kadmin/dbutil/kdb5_create.c
src/lib/kadm5/srv/svr_policy.c
src/lib/kadm5/srv/svr_principal.c
src/lib/kdb/encrypt_key.c
src/lib/kdb/kdb5.c
src/lib/kdb/kdb_convert.c
src/lib/kdb/kdb_cpw.c
src/lib/kdb/t_stringattr.c
src/plugins/kdb/db2/db2_exp.c
src/plugins/kdb/db2/kdb_db2.c
src/plugins/kdb/db2/kdb_db2.h
src/plugins/kdb/db2/kdb_xdr.c
src/plugins/kdb/db2/lockout.c
src/plugins/kdb/ldap/ldap_exp.c
src/plugins/kdb/ldap/ldap_util/kdb5_ldap_realm.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal.h
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_pwd_policy.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_pwd_policy.h
src/plugins/kdb/ldap/libkdb_ldap/libkdb_ldap.exports
src/plugins/kdb/ldap/libkdb_ldap/lockout.c
src/plugins/kdb/test/kdb_test.c
src/tests/create/kdb5_mkdums.c

See http://mailman.mit.edu/pipermail/krbdev/2016-May/012583.html
This will have some conflicts with PR #446, so whichever one is merged first, the other will need adjusting.

Use library allocator, not module allocator, for principal/policy entries

---

.gitignore
src/lib/krb5/krb/Makefile.in
src/lib/krb5/krb/sname_match.c
src/lib/krb5/krb/t_sname_match.c

krb5_sname_match() can read past the end of princ's component array in
some circumstances (typically when a keytab contains both "x" and
"x/y" principals).  Add a length check.  Reported by Spencer Jackson.
There is also a second commit to add unit tests.

Check princ length in krb5_sname_match()

---

src/lib/krb5/krb/Makefile.in

Add a missing "$" to t_sname_match$(EXEEXT) in the clean rule in
lib/krb5/krb/Makefile.in.

Clean t_sname_match in lib/krb5/krb

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_principal.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal.h
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c

krb5_ldap_rename_principal() must free bersecretkey.

Fix memory leak in LDAP rename

---

src/tests/t_sn2princ.py

Relax t_sn2princ.py check of the reverse resolution of the test
hostname.  The new requirement is that it be different from the
forward resolved hostname.  (There is also an existing implicit
requirement that it be in the mit.edu domain.)  This makes
t_sn2princ.py more robust against changes in the reverse resolution of
the test hostname.
ticket: 8422 (new)
tags: pullup

Relax t_sn2princ.py reverse resolution test

---

src/lib/krb5/krb/get_in_tkt.c

In add_padata(), reset the caller's pointer as soon as realloc()
succeeds, to ensure that the old pointer isn't left behind if a later
allocation fails.
(Note to self: after merging this, make a note in the RT ticket about the 1.14/1.13 backport, since it won't be a trivial merge.)

Fix unlikely pointer error in get_in_tkt.c

---

src/plugins/kdb/test/kdb_test.c

sprinc and tprinc must be freed.  Reported by Will Fiveash.

Fix leak in test_check_allowed_to_delegate()

---

src/plugins/kdb/test/kdb_test.c

Remove the conditional return from so that sprinc and tprinc are
always freed.  Reported by Will Fiveash.

Fix test_check_allowed_to_delegate() leak for real

---

src/kadmin/server/misc.c
src/tests/t_policy.py

In kadmind, self-service key changes require a check against the
policy's min_life field.  If the policy does not exist, this check
should succeed according to the semantics introduced by ticket #7385.
Fix check_min_life() to return 0 if kadm5_get_policy() returns
KADM5_UNK_POLICY.  Reported by John Devitofranceschi.

Fix kadmin min_life check with nonexistent policy

---

src/lib/krb5/os/locate_kdc.c

Commit ce112dec844e4650b5ad174bd40f21c32aebe1d1 introduced a memory
leak in locate_srv_conf_1() by moving the free(realmstr) call to the
cleanup handler, because there was an early return after realmstr is
allocated.  Convert that early return to a goto.

Fix recent memory leak in locate_kdc.c

---

src/util/k5test.py

In _onexit() in k5test.py, output an absolute path to the testlog
file, and output explicit directions on re-running the script with the
-v flag.

Clarify directions when a Python test fails

---

src/util/profile/prof_file.c
src/util/profile/prof_test1

In write_data_to_file(), do not clear the profile data object's flags.
If the call to this function resulted from profile_flush_to_file(), we
do not want to clear the DIRTY flag, and we especially do not want to
clear the SHARED flag for a data object which is part of
g_shared_trees.  Instead, clear the DIRTY flag in
profile_flush_file_data().
Add a test case to prof_test1 to exercise the bug in unfixed code.
Also modify test1 to abandon the altered profile after flushing it to
a file, to preserve the external behavior of the script before this
fix.

Fix profile_flush_to_file() state corruption

---

doc/admin/conf_ldap.rst
doc/admin/lockout.rst

The KDC now needs write access to the LDAP KDB, unless password
lockout and tracking of the last successful authentication time are
disabled.  Update the example LDAP access control text in
conf_ldap.rst to reflect this.  Reported by Will Fiveash.

Update LDAP docs for password lockout

---

src/lib/krb5/os/expand_path.c

In k5_expand_path_tokens_extra(), don't throw away non-zero return
statuses in the cleanup handler.

Fix error handling in k5_expand_path()

---

src/kdc/kdc_util.c
src/lib/krb5/krb/preauth2.c
src/tests/t_pkinit.py

The first commit fixes a bug where S4U2Proxy can fail on the client side when the KDC is configured to support PKINIT.
The second commit fixes a KDC crash when restrict_anonymous_to_tgt is set and an S4U2Self request is received.  The test case added in the second commit relies on the first commit; if the first commit is not present, it will fail on the client side (causing the test script to fail) before exercising the KDC fix.

Fix S4U2Self KDC crash when anon is restricted

---

src/kdc/main.c

When I integrated PR #380, I made a change to the last commit to ensure sure that kdc_ports and kdc_tcp_ports would still work inside [kdcdefaults].  Through a fascinating COPY_PASTE_ERROR heuristic, Coverity detected a bug in that change.  This commit fixes the bug.

Fix recent change to kdcdefaults processing

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/tests/t_pkinit.py

This branch steals the first testing commit from PR #447, and then simplifies and improves the PKCS7 EnvelopedData decoding function.

Minimize timing leaks in PKINIT decryption

---

src/clients/kinit/kinit.c
src/lib/krb5/krb/preauth_otp.c

The first commit on this branch sets prompt types in OTP client preauth.  I noticed this omission while testing an earlier version of the second commit.  I also noticed that clpreauth modules can invoke the prompter but currently have no way of setting prompt types, so I think code which calls krb5_get_prompt_types() needs to expect a possible NULL result.
The second commit implements a change we talked about on last Tuesday's dev call, which is to display "Password incorrect" in kinit if we get a preauth-failed error from the KDC and witnessed a password prompt.  I didn't expand this change to other programs which perform AS requests; I think it's not as big of a deal to see a "Preauthentication failed" error from another utility like kadmin or kpasswd.

Improve bad password inference in kinit

---

src/include/k5-queue.h
src/kdc/replay.c
src/lib/krad/attrset.c
src/lib/krad/client.c
src/lib/krad/remote.c

Some BSD-derived systems (e.g., FreeBSD and Mac OS X) inappropriately
include sys/queue.h from some non-kernel network-related headers that
we include (net/if.h is one example).  Because our k5-queue.h is a
copy from a BSD sys/queue.h, many compilers will warn about macro
redefinitions on those systems.  Rename the queue macros to have a K5_
prefix.
ticket: 8466 (new)

Rename k5-queue.h macros

---

src/Makefile.in
src/configure.in
src/plugins/locate/python/Makefile.in
src/plugins/preauth/cksum_body/Makefile.in
src/plugins/preauth/wpse/Makefile.in
src/tests/Makefile.in
src/tests/threads/Makefile.in
src/util/Makefile.in
src/util/collected-client-lib/Makefile.in

In PR #498 we noted that "make distclean" still leaves behind nine files, three of which distclean is supposed to leave alone and six of which are Makefiles generated by configure and not visited by recursive make.  We discussed possible solutions to the six Makefiles but didn't implement them in that PR.
Of the six orphaned Makefiles, one is for the securid_sam2 preauth plugin and the other five are for sort of questionable directories which we could maybe do without.  We clearly can't remove the securid_sam2 directory (at least until SPAKE is implemented and deployed at MIT, which is many years away), so I figured it would act as a model for the other five.  However, it turns out that securid_sam2 should be handled by conditionally generating the Makefile, as we do for PKINIT, LDAP, and …

Remove all makefiles in make distclean

---

doc/admin/admin_commands/kdb5_util.rst
src/kadmin/dbutil/dump.c

kdb5_util dump -recurse hasn't behaved as documented since krb5-1.5,
when the DAL was integrated.  Restoring it is a nontrivial amount of
work, so just document it for now.
ticket: 8470 (new)
tags: pullup

Warn about dump -recurse nonfunctionality

---

.gitignore
src/Makefile.in

Remove unused stuff from the top-level Makefile.in, and also make Emacs tags file generation actually work.

Decruft top-level Makefile.in

---

src/lib/krb5/os/changepw.c
src/lib/krb5/os/locate_kdc.c
src/lib/krb5/os/sendto_kdc.c
src/lib/krb5/os/t_locate_kdc.c
src/lib/krb5/os/t_std_conf.c

[This PR is intended to supersede #505.]
Commit c89587b4476139f05f34aa2323bd7c7db348c44c introduced a bug in
the handling of KDC specifications using the default port, by passing
it to k5_parse_host_string() in network byte order.  Fix this by
removing all of the port byte order transformations in locate_kdc.c,
and storing the struct serverlist port field in host byte order.
Adjust other consumers of struct serverlist to expect the port to be
in host field to be in host byte order.
Reported by Isaac Boukris.

Fix and simplify locate_kdc.c port byte order

---

doc/admin/admin_commands/kadmin_local.rst

The user from debian bug 828976 noted that the documentation has an example that does not escape the quotes.
Maybe this should get an RT ticket for pullup...

Properly escape quotes for otp set_string example

---

src/util/verto/ev.c

The upgrade to libev 4.22 introduced the use of "memory fences" for
more reliable signal processing.  Memory fences are usually
implemented using assembly or compiler primitives, but may be
implemented using pthreads as a last resort.  The unmodified libev
errors out at compile time if pthreads is used, but notes that this
error can be removed if relying on pthreads is okay.  Because the
project's nightly build infrastructure includes an old Solaris machine
whose toolchain is too old for any of the non-pthreads memory fence
implementations, remove the error to allow the build to succeed.  (A
dependency on pthreads functions on Solaris does not require linking
with libpthread.)

Allow libev to use pthreads on old platforms

---

src/lib/krb5/krb/get_in_tkt.c
src/tests/t_general.py

The first commit fixes RT issue 8454 in a minimal way and adds a test case.  It adds a noticeable amount of code to an already overly long and complicated function, so I included a second refactoring commit.

Use responder in non-preauth AS reqs

---

.gitignore
src/tests/Makefile.in
src/tests/forward.c
src/tests/t_authdata.py

Prior to the fix for #8139, forwarded TGTs obtained across a krbtgt
re-key could fail if the preferred krbtgt enctype changed, because
krb5_c_verify_checksum() returns an bad-enctype error due to the
mismatched checksum.  Add a test case for this scenario, using a new
test harness program which obtains a forwarded TGT.

Add another AD-SIGNTICKET corner case test

---

src/lib/gssapi/spnego/spnego_mech.c

[I ran into this while running a test program under valgrind when looking into something else.]
In spnego_gss_import_cred(), use create_spnego_cred() to create the
SPNEGO credential structure.  Prior to this change, an imported SPNEGO
cred did not initialize the no_ask_integ field (added by commit
cf39ed349976908626cad3e05e17788f8334bce9, ticket #6938).

Fix SPNEGO imported cred initialization

---

src/Makefile.in

Commit 0db097ba8b605ea7a6e0364ad786da6528868179 accidentally removed
the $(SKIPTESTS) line from check-pytests-no, causing a syntax error
when running "make check" when python is missing or not sufficiently
new.

Fix check-pytests-no

---

src/include/k5-thread.h
src/util/support/threads.c

threads.c failed to build on Solaris afer commit
17932091cc0d5981c5a78d389ffa4a5c7b532bd6 because k5-thread.h did not
define the conditional k5_once_t structure (because NO_WEAK_PTHREADS
is defined) but threads.c tried to build the conditional k5_once()
function.
Use a single preprocessor symbol, USE_CONDITIONAL_PTHREADS, to
determine whether to use and define pthreads functions which
conditionalize on whether pthreads is loaded.  In threads.c, move the
new k5_once() definitions into the USE_CONDITIONAL_PTHREADS block,
defining a stub function if other code will not refer to it.
Also move #pragma weak declarations from k5-threads.h into threads.c,
as we should no longer be conditionally referring to those symbols
outside of threads.c.
Also eliminate some missing-prototype warnings where …

Fix thread support for Solaris and simplify

---

src/slave/Makefile.in
src/slave/deps
src/slave/kprop.c
src/slave/kprop.h
src/slave/kprop_util.c
src/slave/kpropd.c

In kprop and kpropd, factor out the duplicated implementation of
sn2princ_with_realm() into kprop_util.c.  Rename it to
sn2princ_realm(), remove the type parameter, and require the sname
parameter to be specified.  Rewrite the function to use
krb5_expand_hostname(), avoiding an unnecessary hostrealm lookup.
[There is also a prior commit to rename kprop_sock.c to kprop_util.c.]

Consolidate sn2princ_realm() in kprop and kpropd

---

src/lib/krb5/os/sendto_kdc.c
src/tests/asn.1/trval.c

Ubuntu runs ppc64el builds with -O3, which elicited a few warnings
from gcc that were not generated elsewhere, as documented at
https://bugs.launchpad.net/ubuntu/+source/krb5/+bug/1592841 .
Initialize the output variable at the top of a couple helper functions
to silence the uninitialized-variable warnings.

Fix build with -O3 on ppc64el

---

src/plugins/kdb/db2/libdb2/btree/bt_debug.c
src/plugins/kdb/db2/libdb2/btree/bt_split.c
src/plugins/kdb/db2/libdb2/test/run.test

In the libdb2 btree back end, splitting a page at an overflow key
could result in an unaligned access, causing a crash (and data
corruption) on platforms with strict alignment.  This probably occurs
only rarely in practice.
Also includes regression test and debugging improvements.

Fix unaligned accesses in bt_split.c

---

src/plugins/kdb/db2/libdb2/btree/bt_debug.c
src/plugins/kdb/db2/libdb2/btree/bt_delete.c
src/plugins/kdb/db2/libdb2/btree/bt_put.c
src/plugins/kdb/db2/libdb2/btree/bt_search.c
src/plugins/kdb/db2/libdb2/btree/bt_split.c
src/plugins/kdb/db2/libdb2/btree/btree.h
src/plugins/kdb/db2/libdb2/hash/hash.c
src/plugins/kdb/db2/libdb2/hash/hash.h
src/plugins/kdb/db2/libdb2/hash/hash_page.c
src/plugins/kdb/db2/libdb2/hash/page.h
src/plugins/kdb/db2/libdb2/mpool/mpool.c
src/plugins/kdb/db2/libdb2/recno/rec_close.c
src/plugins/kdb/db2/libdb2/recno/rec_put.c
src/plugins/kdb/db2/libdb2/test/run.test

Clean up many pointer alignment warnings by casting through (void *).
Clean up many signed-unsigned comparison warnings by casting to
unsigned types as appropriate.

Clean up libdb2 warnings

---

src/util/mkrel

Shipping a 10MB+ doc/CHANGES file in the release tarball doesn't make
much sense in a modern context where historical information is readily
available in a distributed version control system.
ticket: 8488 (new)

Stop generating doc/CHANGES

---

src/lib/rpc/xdr.c
src/lib/rpc/xdr_sizeof.c

Cast through (void *) in xdr.c to silence pointer target width
warnings.  In xdr_sizeof.c, use x_private and x_base as proper
pointers as in xdr_mem.c instead of trying to store an integer in a
pointer.

Silence warnings in lib/rpc

---

src/configure.in
src/lib/crypto/openssl/crypto_mod.h
src/lib/crypto/openssl/enc_provider/aes.c
src/lib/crypto/openssl/enc_provider/camellia.c
src/lib/crypto/openssl/enc_provider/des.c
src/lib/crypto/openssl/enc_provider/des3.c
src/lib/crypto/openssl/enc_provider/rc4.c
src/lib/crypto/openssl/hash_provider/hash_md4.c
src/lib/crypto/openssl/hash_provider/hash_md5.c
src/lib/crypto/openssl/hash_provider/hash_sha1.c
src/lib/crypto/openssl/hmac.c
src/lib/crypto/openssl/sha256.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h
src/plugins/tls/k5tls/openssl.c

This PR supersedes PR #442.  I have added a PKINIT RSA test case and split up the OpenSSL 1.1.0 compatibility changes into three commits: libk5crypto, k5tls, and PKINIT.

OpenSSL 1.1.0 compatibility

---

src/kdc/do_as_req.c

In prepare_error_as(), if krb5_us_timeofday() fails and error pa-data
was supplied, the FAST cookie and a shallow copy of the error padata
can be leaked.  Reported by Will Fiveash.

Fix unlikely leak in KDC AS-REQ error path

---

doc/user/user_commands/kinit.rst

Describe the principal selection behavior of kinit when the principal
argument is absent.
ticket: 8403
tags: pullup

Clarify kinit principal selection

---

src/lib/krb5/os/locate_kdc.c

profile_get_boolean() outputs an int, not a krb5_boolean.  Adjust the
local variable "use" to match, or we get a warning.  Reported by Will
Fiveash.

Fix use_dns_uri() type safety

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

When using a smart card and constructing a DigestInfo to pass to the
CKM_RSA_PKCS mechanism, make sure to set the AlgorithmIdentifier
parameters correctly.  This is typically an ASN.1 NULL value.
Reported to Ubuntu in Launchpad #1629370.
ticket: 8506
tags: pullup

Set alg param correctly for PKCS1

---

src/lib/crypto/builtin/pbkdf2.c

In F() in the builtin implementation of PBKDF2, use make_data() to
fully initialize sdata and out; otherwise we (harmlessly) copy an
uninitialized magic field in hmac().  Also simplify out the local
variable tlen.

Improve builtin PBKDF2 code hygiene

---

src/aclocal.m4

[Will Fiveash asked for this, but since it isn't a bug he reported, I didn't credit him in the commit message.]
If a function call passes a const pointer to a function accepting the
same pointer type without the const qualifier, that should be treated
as an erorr if possible.  In sufficiently recent gcc, pass
-Werror=discarded-qualifiers.  (In clang, this is already covered by
-Werror=incompatible-pointer-types which we recently added.)

Error on discarded qualifiers in gcc

---

src/lib/krb5/ccache/cccursor.c

If krb5_cc_start_seq_get() fails inside the loop, close the current
credential cache before continuing to the next one.  Reported by Todd
Lipcon.
To fix this in a minimal way, I broke the coding standards rule of "do not get to the point of freeing the same resource in several different places within a function depending on the exit path".  So there is a second refactoring commit which breaks out the implementation of "does this ccache have any content" into a helper function.

Fix rare leak in krb5_cccol_have_content()

---

doc/admin/database.rst

In database.rst when discussing the procedure for master key rollover,
suggest using unlocked iteration for large databases.  Also make it
clear that unavailability due to locking during iteration is specific
to DB2.

Suggest unlocked iteration for mkey rollover

---

src/include/krb5/krb5.hin

Explicitly say to use krb5_kt_close() like we do for most other
allocating API calls.  Note the default type.  Instead of saying "The
key table is not opened," say that the keytab file for FILE keytabs is
not opened by this call.

Clarify krb5_kt_resolve() API documentation

---

src/include/krb5/krb5.hin

The aes-sha2 specification has been published as RFC 8009.  Add
Doxygen comments to the #defines for its enctype and checksum type
comments.  Also add comments for the RC4 enctype and checksum type
constants referring to RFC 4757.

Add doxygen comments for RFC 8009, RFC 4757

---

src/configure.in

The symbol we need is SD_Init(), not sd_init().

Fix detection of libaceclnt for securid_sam2

---

src/aclocal.m4
src/include/k5-int.h
src/kadmin/dbutil/kdb5_create.c
src/kdc/main.c
src/lib/crypto/builtin/enc_provider/rc4.c
src/lib/gssapi/krb5/delete_sec_context.c
src/lib/gssapi/krb5/export_sec_context.c
src/lib/gssapi/krb5/lucid_context.c
src/lib/gssapi/mechglue/g_initialize.c
src/lib/kadm5/srv/svr_principal.c
src/lib/krb5/krb/authdata.c
src/lib/krb5/krb/pac.c
src/util/support/zap.c

The first commit here improves the reliability of zap() with current and (we hope) future compilers, in particular by using memset_s() when we can.  There's a potential technique not used here, which is to make a call to memset through a volatile function pointer, but I don't know that it's any more likely to work than a shared library call to a function using a volatile char *.
The second commit uses zap() in places where we currently use memset().
I tried creating an automated test for zap() by creating a core file and looking through it for a sentinel string, but so far I haven't been able to get the test to fail with gcc 5.4.0-6ubuntu1~16.04.2 or clang 3.8.0-2ubuntu4, even using just free() with no zap or memset.

Memory scrubbing improvements

---

src/aclocal.m4
src/lib/crypto/builtin/sha1/t_shs3.c

Adds (conditional) build support for -Werror-implicit-int and fixes where this broke my build.
I would appreciate the first commit landing in 1.15, but I'm carrying it as a patch already so it's not hugely important.

Error on declarations without type specification

---

src/include/k5-trace.h
src/lib/krb5/os/dnsglue.h
src/lib/krb5/os/dnssrv.c
src/lib/krb5/os/locate_kdc.c
src/lib/krb5/os/t_locate_kdc.c

To help admins troubleshoot DNS records without resorting to strace/gdb.

Add KRB5_TRACE calls for DNS lookups

---

src/clients/ksu/main.c

The original declaration is in unistd.h with a different
signature.
This caused an issue building with clang fortify on Chrome OS.
Caused the following error;
main.c:858:15: error: redeclaration of 'ttyname' must have the 'overloadable' attribute
char *p, *ttyname();
^
/build/samus/usr/include/unistd.h:784:14: note: previous overload of function is here
extern char *ttyname (int __fd) __THROW __CLANG_NO_MANGLE (ttyname);

Remove redeclaration of ttyname.

---

src/configure.in
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.h
src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c

Solaris 11 provides an OpenLDAP library (which we don't auto-detect,
but should) in addition to the old Mozilla LDAP library; this will
become the default LDAP library in the next release.  As there is no
longer a need to build against the Mozilla LDAP library, and as we
have unwittingly relied on some OpenLDAP-specific features since 1.13,
remove the compatibility code for the Mozilla LDAP library and just
require OpenLDAP 2.1 (which added ldap_str2dn).

Simplify LDAP module by relying on OpenLDAP 2.1

---

src/tests/t_kdb.py

The upstream OpenLDAP installs slapd in libexec, which is not
typically in the path.  Also, copying the binary can sometimes cause
it to fail; for instance, in the OpenCSW package,
/opt/csw/libexec/slapd is a script which chooses a binary based on the
system architecture and the path to the script.  Allow the test runner
to set the SLAPD environment variable to specify the slapd location
and avoid the copy.

Allow slapd path configuration in t_kdb.py

---

NOTICE
doc/notice.rst
src/ccapi/common/win/OldCC/autolock.hxx

With permission from Danilo Almeida, change the license on
autolock.hxx to the 2-clause BSD license used by MIT krb5.
ticket: 8520 (new)
target_version: 1.15-next
tags: pullup

Relicense ccapi/common/win/OldCC/autolock.hxx

---

src/plugins/kdb/ldap/libkdb_ldap/kerberos.ldif

When LDAP backend support for policy extensions was added by 5edafa0532,
kerberos.ldif update was incomplete.
When kerberos.ldif is used to setup LDAP schema, this breaks policy:
root@servera:~# kadmin -p tomas/admin -w aaaa -q 'addpol -history 4 pol1'
Authenticating as principal tomas/admin with password.
add_policy: Database store error while creating policy "pol1".
slapd debug output:
58358d7e Entry (cn=pol1,cn=EXAMPLE.COM,cn=krbcontainer,dc=example,dc=com),
attribute 'krbPwdAttributes' not allowed
58358d7e mdb_add: entry failed schema check: attribute 'krbPwdAttributes' not
allowed (65)
58358d7e send_ldap_result: conn=1001 op=3 p=3
58358d7e send_ldap_result: err=65 matched="" text="attribute
'krbPwdAttributes' not allowed"

kerberos.ldif: Add missing krbPwdPolicy attributes

---

src/lib/krb5/rcache/rc_dfl.c

[No ticket, as this is not a bug.]
In the error cleanup for krb5_rc_io_fetch(), null out rep->msghash
after freeing it, like we do with rep->client and rep->server.  This
omission is currently harmless because krb5_rc_io_fetch() never sets
rep->msghash before failing, but it could result in a double-free or
use after free if the code changes.

Improve cleanup in krb5_rc_io_fetch()

---

src/include/krb5/kdcpreauth_plugin.h

Commit 7b12eb4757f8dd05b79c9b49d4289f0caf1f6eec erroneously changed
the documented kdcpreauth minor version from 2 to 3.  Only the
callback version changed in that commit; the interface minor version
remains at 2 (from commit 83b4ecd20e50ad330cd761977d5dadefe30a785b
which added the loop method).

Fix documented kcpreauth minor version

---

src/tests/t_authdata.py

Add another regression test for #8139 using renewed tickets.
[Although it's hard to back out the 8139 fix or directly backport this test case to 1.13, I created a variant of this test case in krb5 1.13's t_general.py and verified that it fails with "KDC returned error string: HANDLE_AUTHDATA" as expected.]

Add AD-SIGNTICKET test for renewing tickets

---

doc/admin/auth_indicator.rst
doc/appdev/gssapi.rst

The correct attribute name is "auth-indicators".

Fix GSSAPI authind attribute name in docs

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

[As discussed in PR #563]
Fix some long lines in crypto_retrieve_X509_sans() by returning early
if X509_get_ext_by_NID() returns a negative result.  Also ensure that
return parameters are always initialized.

Deindent crypto_retrieve_X509_sans()

---

src/tests/responder.c

"PKCS12:" has seven characters, not five.  Reported by Dorian Ducournau.

Fix minor bug in responder.c test program

---

src/lib/apputils/net-server.c

Here are fixes for the two problems discussed in ticket 8530.  (I created ticket 8531 to track the IPv4-only startup issue.)

Fix KDC and kadmind network setup issues

---

src/include/socket-utils.h
src/lib/apputils/net-server.c
src/lib/apputils/udppktinfo.c

The first two commits are PR #587.  The next two commits remove some redundancy introduced by PR #587 by introducing the sa_is_wildcard() helper and using it.  The final two commits clean up some constructs made unnecessary when we removed the workaround for non-pktinfo platforms.

net-server.c cleanups

---

src/aclocal.m4

Without it, clang ("Apple LLVM version 8.0.0 (clang-800.0.38)" on Mac
OS X 10.11.6) will warn for unrecognized -W options like
"-Werror=discarded-qualifiers" but won't return a nonzero exit status,
leading configure to think the options are supported and thus include
them during the build, leading to a rather noisy log.
This option isn't needed during the build, though it won't hurt
anything either.  It is desirable during the testing of other -W
options for cleaner results, but the existing code tests each option
independently, requiring different handling for this option than for
other -W options.

Use -Werror=unknown-warning-option during configuration if supported.

---

src/plugins/kdb/db2/kdb_db2.c

Commit 03d34fcfa329fbc2f686a0b34e2731e37f483a34 (ticket 8414) removed
the prototype and all uses of krb5_db2_free_policy(), but neglected to
remove the function definition, resulting in a warning.  Remove the
definition now.

Clean up krb5_db2_free_policy()

---

src/tests/t_pkinit.py

In t_pkinit.py, add a PKINIT test case where the KDC sends
KDC_ERR_DH_KEY_PARAMETERS_NOT_ACCEPTED and the client retries with the
KDC's TD_DH_PARAMETERS value, using the clpreauth tryagain method.
Use the trace log to verify that the renegotiation actually takes
place.
[I don't think k5_preauth_tryagain() was covered by the test suite before this test case, and I want to make sure I don't break it while improving continue-after-preauth-failure behavior.]

Add test case for PKINIT DH renegotiation

---

src/include/kdb.h
src/lib/kdb/kdb5.c

There are projects out there which provide kdb modules and use a
different memory allocator than malloc. One example is Samba which uses
talloc. Those projects should to be able to free e_data using their
memory allocation functions.

Add a free_e_data function pointer to krb5_db_entry

---

.gitignore
src/include/k5-int.h
src/include/k5-trace.h
src/include/krb5/krb5.hin
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/preauth2.c
src/tests/Makefile.in
src/tests/icinterleave.c
src/tests/t_preauth.py

It should be possible to successfully use multiple initial credentials
contexts with the same library context.  Create a new internal type
krb5_preauth_req_context containing per-request preauth state,
including the clpreauth modreq handles and the list of preauth types
already tried.  Remove this state from clpreauth_handle and
krb5_preauth_context.
[There is also a preliminary commit to make krb5_preauth_context a pointer type, and follow-up commits to add tests and to check that the same library context is used for each step of an initial credentials context.]

Fix per-request preauth scoping

---

src/lib/krb5/krb/preauth2.c
src/tests/t_pkinit.py

[This will be tested in the preauth fallback work.  I want the change reviewed separately as it's a behavior change independent of improving preauth fallback.]
When trying again after a mechanism-specific error, we should send the
KDC cookie for conformance with RFC 6113.
ticket: 8539

Echo KDC cookies in preauth tryagain

---

doc/admin/pkinit.rst

In pkinit.rst, note that the extensions.client file only works for
single-component client principals, and describe how to modify it for
multi-component principals.
[Prompted by http://mailman.mit.edu/pipermail/krbdev/2017-January/012705.html and http://mailman.mit.edu/pipermail/kerberos/2014-June/019937.html ]

Document multi-component PKINIT client certs

---

src/include/k5-trace.h
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/preauth2.c

Here are four commits which simplify the preauth framework in preparation for better fallback behavior.  I am putting these up for review separately to make it easier to review the main body of the preauth fallback work later on.
The changes to k5_preauth_tryagain() do change how that part of the preauth framework works, by only consulting the module that we previously selected.  Preauth tryagain is used exclusively by PKINIT, so this should not be a risky change.

Cleanups for preauth fallback work

---

src/plugins/preauth/pkinit/pkinit.h
src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_trace.h
src/tests/t_pkinit.py

If a KDC offers both RFC 4556 and draft 9 PKINIT, and we experience a
client-side failure trying RFC 4556 PKINIT (e.g. due to the user
entering the wrong PKCS #11 PIN), do not try to use draft 9 PKINIT.

Avoid draft 9 fallback after PKINIT failure

---

src/lib/krb5/ccache/ccselect.c
src/tests/gssapi/t_ccselect.py

This follows the discussion at http://mailman.mit.edu/pipermail/krbdev/2017-January/012708.html
Note that the test output changes seem to be only a result of the default domain appearing as a fallback, so we might need a more specific KDC discovery test.

Try a fallback realm for GSSAPI ccache selection

---

src/plugins/preauth/pkinit/pkinit_matching.c

[As far as I can tell, we have no automated tests for PKINIT matching rules, and no described manual test procedure.  I may try to find time to create tests, but since we want to get a 1.15.1 out soon, I may decide not to.  The fix is pretty easy to verify by eye, and Sumit and I agreed on it in prior discussion.]
In pkinit_matching.c:parse_rule_set(), apply the default relation when
parsing the second component of a rule, not the third.  Otherwise we
apply no default relation to two-component matching rules, effectively
reducing such rules to their second components.  Reported by Sumit
Bose.

Fix PKINIT two-component matching rule parsing

---

src/lib/gssapi/krb5/naming_exts.c

In krb5_authdata_get_attribute(), check value and
display_value arguments before dereferencing them.
Signed-off-by: Isaac Boukris <iboukris@gmail.com>

Fix segfault in gss_get_name_attribute() call

---

src/config/post.in

autoconf normally avoids recreating files that it does not consider
obsolete.  Since it knows nothing about patchlevel.h (which we read at
autoconf time using m4's esyscmd()), changes to patchlevel.h won't be
reflected in configure unless another input to configure has changed,
and the maintainer rule will re-run autoconf over and over again.  Fix
this issue by passing the force flag to autoconf when we invoke it
from the maintainer rule.

Force autoconf rebuild in maintainer rules

---

doc/admin/admin_commands/kadmin_local.rst
doc/admin/conf_files/krb5_conf.rst
doc/admin/pkinit.rst
doc/plugindev/certauth.rst
doc/plugindev/index.rst
src/Makefile.in
src/configure.in
src/include/Makefile.in
src/include/k5-int.h
src/include/krb5/certauth_plugin.h
src/lib/krb5/krb/plugin.c
src/plugins/certauth/test/Makefile.in
src/plugins/certauth/test/certauth_test.exports
src/plugins/certauth/test/deps
src/plugins/certauth/test/main.c
src/plugins/preauth/pkinit/pkinit.h
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h
src/plugins/preauth/pkinit/pkinit_matching.c
src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h
src/tests/Makefile.in
src/tests/t_certauth.py
src/tests/t_pkinit.py

This PR implements the certauth plugin interface and builtin modules as outlined in https://k5wiki.kerberos.org/wiki/Projects/Certificate_authorization_pluggable_interface

PKINIT certificate authorization pluggable interface

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

[In my final review pass of PR #610 I fixed an omission in my revised crypto_encode_der_cert() code, but made a mistake in an error path.]
In crypto_encode_der_cert(), if the second i2d_X509() invocation
fails, make sure to free the allocated pointer and not the
possibly-modified alias.

Correct error handling bug in prior commit

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

[While looking over how pkinit_crypto_openssl.c uses i2d functions, I found some allocations for unused buffers in the PKCS11 signing code.]
In cms_signeddata_create(), alg_buf and digest_buf are allocated but
never used.  (Instead, a combined buffer is allocated and the alg and
digest objects are marshalled into it.)  Remove them.

Remove some unnecessary PKINIT code

---

doc/admin/conf_files/krb5_conf.rst
src/util/profile/prof_parse.c

[From list discussion.  I decided to mark this for pullup as it could be considered a bug, and so that we limit the number of different includedir behaviors in different release lines.]
Editors and filesystems may create artifacts related to .conf files
which don't change the file suffix; these artifacts generally begin
with "." so that they don't appear in normal directory listings
(e.g. ".#filename" for emacs interlock files).  Make sure to ignore
any such artifacts when processing a profile includedir directive.
ticket: 8563 (new)
target_version: 1.15-next
tags: pullup

Ignore dotfiles in profile includedir

---

src/util/verto/verto-k5ev.c

[Building less libev code reduces our library size a small amount, and also reduces the amount of third-party code seen by static analyzers.]
In verto-k5ev.c, turn off optional watchers in ev.c, and enable the
specific watcher types we use.

Compile less libev code

---

src/lib/crypto/krb/s2k_des.c
src/lib/crypto/krb/s2k_pbkdf2.c
src/lib/crypto/krb/string_to_key.c

The per-enctype string_to_key implementations are inconsistent about
whether a null salt is treated as empty or results in a null
dereference.  Since the original DES string-to-key allowed a null
salt, substitute an empty salt in krb5_c_string_to_key_with_params().
Eliminate conditionals on accessing salt in the per-enctype
implementations as they are on longer needed.  Based on a patch by
Martin Kittel.

Simplify null salt handling in string-to-key

---

src/lib/gssapi32.def

[Corrects an oversight in PR #601]
Add the new public data symbol GSS_KRB5_GET_CRED_IMPERSONATOR to the
gssapi DLL export list.

Export GSS_KRB5_GET_CRED_IMPERSONATOR on Windows

---

src/include/krb5/kdcpreauth_plugin.h
src/kdc/kdc_preauth.c
src/plugins/preauth/otp/main.c

Add the kdcpreauth callback client_name() to return the client DB
principal and use it when calling otp_state_verify().  This allows
canonicalization of the name before passing it along as the username
for RADIUS.

Use the client DB principal name for OTP

---

src/include/krb5/krb5.hin

[An alternative approach to one of the commits in PR #630.]
The kprop protocol uses cipher state via this call, perhaps along with
other.  As there is no replacement, the call should not be deprecated
in the API.

Un-deprecate krb5_auth_con_initivector()

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

there are still missing bits using old OpenSSL 1.0.x API in the DEBUG ifdefs. I ran into this one while building `pkinit` with `DEBUG` so I am providing a fix, but there might be others in other parts of the project.

Port pkinit debug code to OpenSSL 1.1.0 API

---

src/lib/krb5/krb/preauth_ec.c

If we reach the encrypted challenge clpreauth process method without
an armor key, error out instead of crashing.  This can happen if (a)
the KDC offers encrypted challenge even though the request doesn't use
FAST (the Heimdal KDC apparently does this), and (b) we fall back to
that preauth method before generating a preauthenticated request,
typically because of a prompter failure in encrypted timestamp.

Check for FAST in encrypted challenge client

---

doc/admin/conf_files/kdc_conf.rst
src/include/k5-int.h
src/kdc/kdc_preauth_ec.c
src/tests/gssapi/t_authind.py

Here's my attempt at adding AI capabilities to the FAST ec module. The configuration option may be inadequate as only a kdcdefaults section option, but currently the module does not use any realm-specific moddata in order to handle separate FAST AIs.

Add FAST encrypted challenge auth indicator

---

src/lib/crypto/krb/s2k_rc4.c

krb5int_utf8cs_to_ucs2les() can read slightly beyond the end of the
input buffer if the buffer ends with an invalid UTF-8 sequence.  When
computing the RC4 string-to-key result, make a zero-terminated copy of
the input string and use krb5int_utf8s_to_ucs2les() instead.

Make RC4 string-to-key more robust

---

src/include/k5-utf8.h
src/lib/crypto/krb/s2k_rc4.c
src/lib/krb5/krb/pac.c
src/lib/krb5/krb/pac_sign.c
src/util/support/libkrb5support-fixed.exports
src/util/support/utf8_conv.c

This is an outgrowth of #630 (and is based on those commits).  So far:
* Removed several unused functions, and thereby moved to little endian only
* Changed `k5_ucs2s_to_utf8s()` to operate on a byte array
* Using `load_16_le()` to load bytes
* Changed `k5_ucs2s_to_utf8s()` to operate in a single pass

Modernize utf8_conv.c

---

src/include/k5-input.h
src/lib/krb5/ccache/ccmarshal.c
src/lib/rpc/deps
src/plugins/preauth/pkinit/deps
src/tests/deps
src/tests/gssapi/deps
src/util/support/deps

[I want to use k5-input.h in utf8_conv.c, and there's a restriction that you can't use libkrb5 headers in libkrb5support.]
Avoid using the krb5_error_code type (using int32_t instead), and
include k5-platform.h instead of k5-int.h, so that we can use
k5-input.h in libkrb5support.

Reduce dependencies of k5-input.h

---

.travis.yml

Update the Travis CI OS distribution to Ubuntu 16.04 LTS (Xenial Xerus). The current OS distribution, Ubuntu 14.04 LTS (Trusty Tahr), was chosen before 16.04 LTS was released and, presumably, the update was simply overlooked.

Update Travis CI distribution to Xenial

---

.gitignore
src/include/k5-utf8.h
src/lib/crypto/krb/s2k_rc4.c
src/lib/krb5/krb/pac.c
src/lib/krb5/krb/pac_sign.c
src/util/support/Makefile.in
src/util/support/deps
src/util/support/libkrb5support-fixed.exports
src/util/support/t_utf16.c
src/util/support/utf8.c
src/util/support/utf8_conv.c

[This will be kind of dense to review, but it isn't a lot of code, and I tried to comment and structure it well enough that it isn't an impenetrable wall of magic numbers.  The wikipedia article on UTF-16 contains a nice summary of the encoding.]
Where we convert between UTF-8 and UCS-2 (RC4 string-to-key and PAC
client info), use UTF-16 instead of UCS-2.  Add a test program for
the conversion functions.

Add UTF-16 conversions in place of UCS-2

---

src/lib/krb5/os/sendto_kdc.c

We apply (as of ticket #7604) a ten-second minimum delay after a TCP
connection is accepted before creating new connections or sending UDP
packets.  Apply this timeout to HTTPS connections as well, by removing
the transport check in get_endtime().  As the endtime field is only
set by service_tcp_connect(), it will always have the value 0 for UDP
connection state objects, so there is no need to check the transport
type.

Apply TCP timeouts to HTTPS (KKDCP) transport

---

src/lib/gssapi/krb5/context_time.c

[I had no idea that gss_context_time() existed until I started combing the source tree for y2038 issues.  It seems like a special case of gss_inquire_context(), maybe still present in the API for historical reasons.]
Commit b496ce4095133536e0ace36b74130e4b9ecb5e11 (ticket #8268) adds
the clock skew to krb5 acceptor context lifetimes for
gss_accept_sec_context() and gss_inquire_context(), but not for
gss_context_time().  Add the clock skew in gss_context_time() as well.
ticket: 8581 (new)
target_version: 1.15-next
tags: pullup

Allow clock skew in krb5 gss_context_time()

---

src/kdc/kdc_preauth_ec.c
src/kdc/kdc_preauth_encts.c
src/lib/krb5/krb/gc_via_tkt.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/int-proto.h

While working on the y2038 stuff I noticed five occurrences of ``labs(timestamp1 - timestamp2) < context->clockskew``, which is a somewhat awkward construction that gets more awkward after accounting for post-2038 stuff.  These commits reduce that pattern to two occurrences.
There are a couple of changes in the fencepost case where the timestamps being checked are exactly context->clockskew seconds apart.  I don't think that's important enough to warrant a ticket or a mention in the commit messages.

Factor out clock skew checks

---

src/lib/krb5/ccache/cc_mslsa.c

**Symptom:**
Using MSLSA CC sometimes fails with error:
major: 851968='Unspecified GSS failure.  Minor code may provide more information',
minor: 2529639055='Request did not supply a ticket'
This manifests itself on Windows 10 with production build and using MSVC and
works on Windows 7 or using debug build (again with MSVC).
**Problem:**
krb5_lcc_data.flags is not initialized when krb5_lcc_data is allocated so
flags content is random. krb5_lcc_next_cred() checks if flags has
KRB5_TC_NOTICKET bit set and returns error if it is.
**Fix:**
Initialize flags to 0.

Fix uninitialized krb5_lcc_data.flags in cc_mslsa

---

src/lib/krb5/krb/get_creds.c
src/tests/t_crossrealm.py
src/tests/t_referral.py

[More information at http://krbdev.mit.edu/rt/Ticket/Display.html?id=8579 ]
During a TGS request, if we get a TGT response that we didn't directly
ask for (a referral TGT or an alternate TGT), don't cache it.  It
would have limited value in the cache as similar operations won't look
for that TGT.  If the overall TGS operation fails and is repeated, we
could wind up caching the same entry multiple times, which doesn't
work well with our current ccache implementations.

Don't cache referral and alternate TGT replies

---

src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/send_tgs.c

[KDC-REQ nonces equal to the current timestamp won't work reliably after 2038, because of a disagreement between RFC 4120 and MIT krb5/Heimdal on whether the nonce field is signed.  Of course we could mask off the high bit from the timestamp just as easily as from random bytes, but this is better.]
Commit ae0fee058ad883b2e82fa2b34f4e5f059e827a1b (ticket #5425) changed
the AS client code to use a random nonce, but left the TGS client code
using the current timestamp.  Use a random nonce for TGS requests as
well.

Use a random nonce in TGS requests

---

src/tests/t_referral.py

Commit 1dc619624421002b1e64d3b8c7e270508381b3e6 included a stray
"exit(0)" for debugging.  Remove it.

Remove stray exit in t_referral.py

---

src/clients/klist/klist.c
src/include/k5-int.h
src/kadmin/server/misc.c
src/kdc/dispatch.c
src/lib/kadm5/srv/server_acl.c
src/lib/kadm5/srv/server_kdb.c
src/lib/kadm5/srv/svr_principal.c
src/lib/krb5/krb/gen_save_subkey.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/os/c_ustime.c
src/lib/krb5/os/toffset.c
src/lib/krb5/os/trace.c
src/lib/krb5/os/ustime.c
src/lib/krb5/rcache/rc_dfl.c
src/tests/create/kdb5_mkdums.c

While doing the y2038 work I noted that some code used krb5_int32 directly instead of krb5_timestamp to hold timestamp values, and figured that would be simplest to treat as a cleanup opportunity for later.  It turns out I should have done it as part of the original PR, because in searching for those uses I found four areas of timestamp manipulation code that I had missed.  This PR has three commits:
1. Fix up the untouched timestamp manipulations.
2. krb5_int32 -> krb5_timestamp where needed
3. Clean up some really ancient libkadm5 code that should have been deleted rather than stuck inside ``#if 0``.

y2038 followup work

---

src/include/kdb.h
src/kdc/kdc_log.c
src/lib/kdb/Makefile.in
src/lib/kdb/kdb5.c
src/plugins/kdb/db2/db2_exp.c
src/plugins/kdb/db2/kdb_db2.c
src/plugins/kdb/db2/kdb_db2.h
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.c
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.h
src/tests/kdbtest.c

In Samba we've added an audit logging system. To be able to call that from the Samba KDB module I need the client address. We have that information but it is not passed down to the KDB module.
As this is an incompatible change to the API also raise the DAL version.

Pass the address from the connecting client to audit_as_req

---

src/lib/gssapi/krb5/init_sec_context.c

In nomal course of execution, md5.contents allocated by
kg_checksum_channel_bindings() in make_ap_req_v1() is freed in
make_gss_checksum(). But when there is a failure in
krb5_mk_req_extended() or in make_gss_checksum() before free is called,
the memory leaks.
This patch frees the memory unconditionally in make_ap_req_v1().

Free checksum data deterministically.

---

doc/admin/conf_files/kdc_conf.rst

The functional portion of this change was made in d1ec317288278d10ae34fde9b2414e4fca5c52dd.
(As an additional note, looking at the generated kdc.conf.man file, it looks like this may not have been regenerated recently - in addition to a lot of formatting churn, I see a note about the sha2 enctypes being new in 1.15, so I'm not sure it was updated prior to release.  I'd update it with this PR but for the churn.)

kdc.conf(5): aes-sha2 enctypes are part of the aes family

---

src/util/support/gmt_mktime.c

[One of our nightly test machines runs an old enough Solaris not to have timegm(), and its 64-bit variant picked up this omission in the y2038 work.]
gmt_mktime() is used as a fallback when the platform does not have
timegm().  Make it work for dates in the unsigned 32-bit range, not
the signed 32-bit range.

Fix gmt_mktime for y2038

---

src/include/kdb.h
src/include/net-server.h
src/kadmin/server/schpw.c
src/kdc/dispatch.c
src/kdc/do_as_req.c
src/kdc/kdc_log.c
src/kdc/kdc_util.h
src/lib/apputils/net-server.c
src/lib/kdb/kdb5.c
src/plugins/kdb/db2/db2_exp.c
src/plugins/kdb/db2/kdb_db2.c
src/plugins/kdb/db2/kdb_db2.h
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.c
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.h
src/tests/kdbtest.c

As we already broke the API it might be useful to know over which IP address the client connection came in.
It also does some code cleanup to have consistent naming (local_addr, remote_addr) and use const when passing the buffer down.

Pass down the local address to the KDB AS request audit functions

---

.gitignore

The t_sha2 test case binary was missing from .gitignore. 
Thanks,
Alex

.gitignore: t_sha2

---

src/kadmin/ktutil/ktutil.c
src/lib/krb5/keytab/kt_file.c
src/lib/krb5/keytab/kt_memory.c
src/lib/krb5/keytab/kt_srvtab.c

[I updated Luke's old patch from ticket 3349 and prepared it as a pull request.  The keytab side of this bugs me, I think just because of the inherent complexity of keytab matching with this new feature added.  In the file keytab type, adding the new chekc to any of the three existing match conditionals will basically work, but none of them feel precisely appropriate, and the edge-case semantics are slightly different if we treat it as an exact match like Luke's patch did.]
In ktutil, make "-k 0" work when creating a keytab entry.  In the
keytab implementations, treat entries with unspecified kvnos as
low-priority matches.
[ghudson@mit.edu: adjusted to current file keytab code; added logic
for other keytab types; wrote commit message]

Allow unspecified kvno in keytab entries

---

doc/admin/admin_commands/ktutil.rst
src/kadmin/ktutil/ktutil.c
src/kadmin/ktutil/ktutil.h
src/kadmin/ktutil/ktutil_funcs.c
src/man/ktutil.man

This change adds ability to specify an optional argument salt to the ktutil add_entry command. This helps in creating user keytabs where the salt is not derived from the user principal name. Some uses of this are in creating keytabs for IPA which uses random salting and for Active Directory where enterprise UPNs are used. If the salt argument is not specified then the original behavior of deriving salt from principal is used.

Add option to specify salt to ktutil add_entry command

---

src/aclocal.m4
src/lib/krb5/krb/deltat.c
src/lib/krb5/krb/x-deltat.y

In gcc, maybe-uninitialized gives different warnings depending on the
optimization level, and in our experience usually gives false
positives.  We don't ask for it (except implicitly through -Wall), but
gcc bundles it into the error behavior of -Werror=uninitialized.
Explicitly turn it off so that builds with -Og and -Os don't error
out.

Turn off -Wmaybe-uninitialized

---

src/tests/gssapi/t_gssapi.py

The GSSAPI time_t tests do not run correctly on 32-bit Solaris because
time_t conversions are involved in the "kinit -l 8500d" step.
Suppress the GSS y2038 tests when time_t is 32-bit.

Suppress y2038 GSS tests when time_t is 32-bit

---

src/lib/kadm5/srv/server_acl.c

In kadm5int_acl_get_line(), increment *lnp after skipping a blank or
comment line, so that kadm5int_acl_load_acl_file() correctly reports
the line number if it fails to parse a line.
In acl_syn_err_msg, use %.10s to limit the amount of the line included
in the error message, not %10s to left-pad it with spaces if it is
shorter than ten characters.

Fix kadm5.acl error reporting

---

doc/conf.py

Commit d1ec317288278d10ae34fde9b2414e4fca5c52dd added aes-sha2 to the
default permitted enctype lists and the aes family, but didn't update
the documentation.  Commit 33a500ea14286b0d42c3ad63df8b88b3849b33a3
updated the documentation for the aes family, but not for the default
enctype lists.  Reported by Weijun Wang.

Add aes-sha2 to default enctypes in docs

---

src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.h
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap_conn.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_handle.c

The server_info_update_pending field of krb5_ldap_server_handle was
never set to true, and we never define ASYNC_BIND.  Noted by Will
Fiveash.

Remove unused async binding code in LDAP

---

src/lib/kadm5/srv/svr_principal.c

[The comments in these changes aren't properly capitalized or punctuated, because they're copies of similar comments in other functions.  The non-setv4key part of this change was tested by Frank, and it's not a great time for me to create a setkey test harness that we could use in t_kdb.py, so for now I'm not going to worry about automated tests to go with the fix.]
Add mask assignments to kadm5_setv4key_principal() and
kadm5_setkey_principal_4() so that their changes to the principal are
properly written to KDB modules which use the mask flag, such as the
LDAP KDB module.  Reported by Frank Lonigro.

Fix kadm5 setkey operation with LDAP KDB

---

src/kadmin/server/Makefile.in
src/kadmin/server/auth_acl.c
src/kadmin/server/auth_acl.h
src/kadmin/server/deps
src/kadmin/server/ipropd_svc.c
src/kadmin/server/misc.c
src/kadmin/server/ovsec_kadmd.c
src/kadmin/server/server_stubs.c
src/lib/kadm5/srv/Makefile.in
src/lib/kadm5/srv/deps
src/lib/kadm5/srv/libkadm5srv_mit.exports
src/lib/kadm5/srv/server_misc.c

These commits move and refactor the kadm5.acl code in preparation for adding the kadm5_auth interface.  There is a minor functional difference in the third commit, so I split it out and assigned it a ticket number.
The second commit doesn't leave much of the original code intact, so the changes to auth_acl.c will be difficult to review as a diff.  It's not a lot of code, so reviewing the refactored code as if it were new is probably the best approach.

kadm5.acl code refactoring

---

doc/admin/conf_files/kadm5_acl.rst

[A recent discussion on the Heimdal list led me to review how we express privileges now that we have an extract-keys operation which requires explicit authorization.  I think we are in a slightly better place because we use "*" or "x" rather than "all" to mean "all privileges except extracting keys", but our documentation is a little misleading.]
In the kadm5.acl example, be more careful about saying "all
privileges", as the recently added extract privilege is not covered by
"*" or "x".

Clarify "all privileges" in kadm5.acl docs

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.c

Assign status values if S4U2Self padata fails to decode, if an
S4U2Proxy request uses invalid KDC options, or if an S4U2Proxy request
uses an evidence ticket which does not match the canonicalized request
server principal name.  Reported by Samuel Cabrero.
If a status value is not assigned during KDC processing, default to
"UNKNOWN_REASON" rather than failing an assertion.  This change will
prevent future denial of service bugs due to similar mistakes, and
will allow us to omit assigning status values for unlikely errors such
as small memory allocation failures.
[There is a second non-backport commit to remove status assignments for error conditions which don't look practically reachable to me.]

Prevent KDC unset status assertion failures

---

src/lib/kdb/kdb5.c

If krb5_db_fetch_mkey() prompts for a master key and needs to
determine the kvno, check that the master entry contains any key data
before dereferencing the first element.  Reported by Joshua Schaeffer.

Prevent null dereference with keyboard master key

---

src/aclocal.m4

aclocal.m4 is modified to allow WARN_CFLAGS/WARN_CXXFLAGS to be
externally set to override the default values.

Allow WARN_CFLAGS/WARN_CXXFLAGS override for Solaris compiles

---

src/clients/kdestroy/kdestroy.c
src/clients/klist/klist.c
src/tests/t_ccache.py

[I didn't mark this for backport and I could have split it into a minimal change and cleanup, although it's not a large patch even with the code simplifications.]
In klist and kdestroy, if a ccache name is specified, set it as the
default ccache name, simplifying the code and making klist -l, klist
-A, and kdestroy -A can work with a specified ccache name.  Reported
by Robbie Harwood.

Make ccache name work for klist/kdestroy -A

---

doc/admin/conf_files/kdc_conf.rst
src/man/kdc.conf.man
src/plugins/preauth/pkinit/pkinit.h
src/plugins/preauth/pkinit/pkinit_identity.c
src/plugins/preauth/pkinit/pkinit_srv.c

pkinit_kdc_ocsp is non-functional in the OpenSSL backend, so remove most
traces of it, including its man page entry.  Detect its presence and error out
instead of silently ignoring the realm entirely.
I'm happy to leave the man page entries around if that would make it more clear.  If we want to add support back into the KDC in the future, it may also make sense to leave the struct entries and such around.

Display an error message if pkinit_kdc_ocsp is specified

---

src/include/k5-thread.h

Unfortunately compilers will often eat these return codes and so even if I get a coredump, I don't get the return value.  Presenting upstream something I use for debugging downstream.

Log failure details on mutex error assertions

---

doc/plugindev/index.rst
doc/plugindev/kdcpolicy.rst
src/Makefile.in
src/configure.in
src/include/Makefile.in
src/include/k5-int.h
src/include/k5-trace.h
src/include/krb5/kdcpolicy_plugin.h
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/main.c
src/kdc/policy.c
src/kdc/policy.h
src/kdc/tgs_policy.c
src/lib/krb5/krb/plugin.c
src/plugins/kdcpolicy/test/Makefile.in
src/plugins/kdcpolicy/test/main.c
src/plugins/kdcpolicy/test/policy_test.exports
src/tests/Makefile.in
src/tests/t_kdcpolicy.py

Add the header include/krb5/kdcpolicy_plugin.h, defining a pluggable
interface for a single module to control AS+TGS request behavior.  This
replaces the policy.c functions with handles for pass/fail as well as
ticket lifetime and session key encryption type.
Add against_local_policy_as() and against_local_policy_tgs() as entry
functions.  Move against_local_policy_as() to finish_process_as_req() so
that both can have authentication indicator information available.
Add a test module in plugins/policy/test.  Create t_kdcpol.py with basic
policy tests.  Add plugin interface documentation in
doc/plugindev/policy.rst.
Also-authored-by: Matt Rogers <mrogers@redhat.com>

Add KDC policy pluggable interface

---

src/include/krb5/certauth_plugin.h
src/plugins/certauth/test/main.c
src/plugins/preauth/pkinit/pkinit_srv.c

Repeating an identical typedef is allowed by C11, but not C99 or C89.
Use the underlying structure type in certauth_plugin.h so that it can
safely be included along with kdb.h.

Avoid repeating typedef in certauth_plugin.h

---

doc/admin/conf_files/krb5_conf.rst
src/kadmin/server/auth_acl.c

[Coverity found this.  Incorporating Coverity into pre-merge CI isn't really practical at this time, unfortunately, although we could consider an integration which uses a manual step.]
Commit 92a1a7efe2fc43337416098f2227038a72f1e35a uses line after it is
freed in load_acl_file().  Move the k5_setmsg() call earlier to fix
it.

Fix recent use-before-free in kadmin ACL code

---

src/include/krb5/certauth_plugin.h

Each pluggable interface header needs to include some boilerplate text
to make it clear what a module implementor needs to provide.  Include
that text in certauth_plugin.h.

Use standard comment in certauth plugin header

---

src/lib/gssapi/mechglue/g_accept_sec_context.c
src/lib/gssapi/mechglue/g_complete_auth_token.c
src/lib/gssapi/mechglue/g_context_time.c
src/lib/gssapi/mechglue/g_delete_sec_context.c
src/lib/gssapi/mechglue/g_exp_sec_context.c
src/lib/gssapi/mechglue/g_init_sec_context.c
src/lib/gssapi/mechglue/g_inq_context.c
src/lib/gssapi/mechglue/g_prf.c
src/lib/gssapi/mechglue/g_process_context.c
src/lib/gssapi/mechglue/g_seal.c
src/lib/gssapi/mechglue/g_sign.c
src/lib/gssapi/mechglue/g_unseal.c
src/lib/gssapi/mechglue/g_unwrap_aead.c
src/lib/gssapi/mechglue/g_unwrap_iov.c
src/lib/gssapi/mechglue/g_verify.c
src/lib/gssapi/mechglue/g_wrap_aead.c
src/lib/gssapi/mechglue/g_wrap_iov.c

[@frozencemetery: please run interposer tests against this PR]
After gss_init_sec_context() or gss_accept_sec_context() has created a
context, don't delete the mechglue context on failures from subsequent
calls, even if the mechanism deletes the mech-specific context (which
is allowed by RFC 2744 but not preferred).  Check for union contexts
with no mechanism context in each GSS function which accepts a
gss_ctx_id_t.

Preserve GSS context on init/accept failure

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c

Setting the error ctime field to the client nonce assumes that the
client used its system time as the nonce, which is not recommended by
RFC 1510 and is prohibited by RFC 4120.  Omit the field instead, by
setting the structure field to 0.

Don't set ctime in KDC error replies

---

src/kdc/kdc_util.c
src/tests/t_renew.py

The second commit here is a trivial y2038 fix that I noticed while preparing the first commit.  The impact of the bug would have been miniscule.
The first commit addresses some feedback we got years ago about KDC behavior around issuing renewable tickets, and a recent observation from Weijun that we have a minor bug where we issue inconsistent renewed tickets.  I don't think the bug is important enough for a backport so I combined the fix with the behavior change.

Renewable ticket processing changes

---

src/util/verto/README
src/util/verto/libverto.exports
src/util/verto/verto-k5ev.c
src/util/verto/verto-libev.c
src/util/verto/verto.c
src/util/verto/verto.h

Local changes:
- Update upstream URL for fedorahosted deprecation.
- Add verto_cleanup() to exports.
Upstream changes:
- Strict c89 compliance.
- Remove local asprintf() implementation.
- Fix memleak when memory allocator is realloc().
- Fix leaks of filenames during load.
- Fix many unused variable warnings.
- Factor out mutability check.
- Properly handle _GNU_SOURCE checking.

Bump bundled libverto for 0.3.0 release

---

doc/admin/conf_files/krb5_conf.rst
src/lib/krb5/ccache/Makefile.in
src/lib/krb5/ccache/cc-int.h
src/lib/krb5/ccache/ccselect.c
src/lib/krb5/ccache/ccselect_hostname.c
src/tests/gssapi/t_ccselect.py

Extend fallback logic to prefer the ccache for which the predicted
realm is the closest subdomain.  This causes, for instance, a service
service1/foo.bar.example.com to prefer ccaches for, in order,
BAR.EXAMPLE.COM, EXAMPLE.COM, and COM.  Previously this behavior was
gated solely by the `realm_try_domains` setting (for DNS-discovered
realms) and the [domain_realm] mappings in krb5.conf.

Add ccselect module based on server hostname

---

src/tests/dejagnu/pkinit-certs/make-certs.sh

The openssl req commands in make-certs.sh contain -subj options which
were ignored in favor of the config file prior to OpenSSL 1.1.  When
they are used, they remove elements of the subject which are now
required by t_pkinit.py.

Fix make-certs.sh for OpenSSL 1.1

---

src/clients/ksu/ccache.c
src/include/k5-int.h
src/kdc/kdc_util.c
src/kdc/replay.c
src/kdc/t_replay.c
src/lib/krb5/krb/gc_via_tkt.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/valid_times.c
src/lib/krb5/os/timeofday.c

Although timestamps above 2^31-1 are now valid, intervals must not
exceed 2^31-1 seconds.  The initially computed interval in
kdc_get_ticket_endtime() could be negative, causing the function to
yield an incorrect result.  (With the new larger value of
kdc_infinity, this could specifically happen if an KDC-REQ contains a
zero till field.)  Cap the interval at the maximum valid value.
Reported by Weijun Wang.
Also use a y2038-safe timestamp comparison in set_request_times() when
comparing the requested renewable end time to the requested ticket end
time.

Limit ticket lifetime to 2^31-1 seconds

---

src/appl/simple/client/sim_client.c
src/appl/simple/server/sim_server.c
src/include/k5-platform.h
src/lib/krb5/os/expand_path.c
src/lib/krb5/os/localaddr.c

In k5-platform.h, only test for SHARED and define the finalizer as
static if we don't expect linker options to be used for finalizers.
SHARED is not a robust test (it isn't defined when building objects
for shared libraries on AIX, OSF/1, or sometimes IRIX because they
don't use separate PIC objects), and as linker finalizer options are
only applied when shared libraries are created, we don't have to worry
about finalizers happening for static libraries.
In expand_path.c, remove the unnecessary structure tag from "struct
token" as it conflicts with <net/if_arp.h> on AIX.
In localaddr.c, initialize output parameters at the beginning of
get_ifreq_array().  Otherwise, gcc cannot be sure that they are always
set when get_ifreq_array() returns 0, because we use errno as a return
value in one …

Fix AIX build issues

---

doc/admin/admin_commands/kpropd.rst
src/slave/kprop.c
src/slave/kpropd.c

All of the intuitive single-letter option names for pid-file in kpropd were already taken, so I made it a long option, which necessitated converting kpropd to getopt.  I converted kprop while I was there.  The currently supported option syntax appears to be a subset of the POSIX syntax, so I don't think anything should break.

Add kpropd pid-file option

---

src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/preauth2.c

Continuing client preauth after a keyboard interrupt is unexpected and
can manifest bugs (such as the one in ticket 8596) by invoking preauth
mechs we wouldn't ordinarily reach.  Based on a patch by Marc Dionne.

Abort client preauth on keyboard interrupt

---

src/kdc/extern.c
src/kdc/extern.h
src/kdc/main.c

Improves startup of the KDC slightly by no longer generating a DES-MD5
key which isn't used for anything.

Remove unused SAM setup code

---

doc/conf.py

Commit 4c234d8754c063177bc627c6298b85020d91c223 added the aes-sha2
enctypes to the documented default enctypes, but in the wrong order.
Reported by Weijun Wang.

Fix default enctype order in docs

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

Rewrite X509_NAME_oneline_ex() and its call sites to use dynamic
allocation and to perform proper error checking.

Fix PKINIT cert matching data construction

---

src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h

3ff426b9048a8024e5c175256c63cd0ad0572320 attempted to display an error
when OCSP support was requested, but this error message was suppressed
in pkinit_server_plugin_init().  Other error messages from
pkinit_init_kdc_profile(), missing pkinit_identity or pkinit_anchors,
are also now exposted.

Expose context errors in pkinit_server_plugin_init

---

doc/build/index.rst

web.mit.edu has two problems for distributing the krb5 code: first, if we point people to https://web.mit.edu/, people inside MITnet will be asked for a client certificate; and second, it serves .tar.gz files with "Content-Encoding: x-gzip" which can cause clients to uncompress them when saving (but generally not change the filename).
I made a "dist" link at kerberos.org pointing to the same AFS content as web.mit.edu/kerberos/dist contains.  This commit updates the documentation reference there.
We also have a fair amount of content at http://web.mit.edu/kerberos (not under "dist") including the per-release documentation.  It didn't seem as elegant to have something like "https://kerberos.org/kerberos" pointing to that content, so for now I'm just treating that as a separate and less …

Point to kerberos.org/dist

---

NOTICE
README
doc/conf.py
doc/copyright.rst
doc/notice.rst
src/prototype/prototype.c
src/prototype/prototype.h
src/windows/version.rc

Update copyright years to 2018 where appropriate given the new year

Update copyright years to 2018

---

src/kdc/kdc_preauth.c
src/plugins/preauth/securid_sam2/grail.c
src/plugins/preauth/securid_sam2/securid2.c

If a principal has the requires_hwauth bit set, include PA-ETYPE-INFO or PA-ETYPE-INFO2 padata in the PREAUTH_REQUIRED error, as preauth mechs involving hardware tokens may also use the principal's Kerberos password.
When looking up the client long-term key in the securid_sam2 preauth module, look for any salt type, not just the default salt type.

Hardware preauth salt fixes

---

doc/admin/conf_files/kdc_conf.rst
doc/plugindev/general.rst
src/include/adm_proto.h
src/include/k5-buf.h
src/kdc/main.c
src/lib/kadm5/clnt/libkadm5clnt_mit.exports
src/lib/kadm5/logger.c
src/lib/kadm5/srv/libkadm5srv_mit.exports
src/util/support/k5buf.c
src/util/support/libkrb5support-fixed.exports

Background is here: http://krbdev.mit.edu/rt/Ticket/Display.html?id=8630
This PR cleans up the logging behavior of com_err() from KDC/kadmind plugin modules, allowing us to expand its use without adding lots of weirdly formatted messages to log files.  If we later determine a need for a logging facility with a closer fit to krb5_klog_syslog(), we can add a kdcpreauth callback (or two) to handle it, but for now I think com_err() should be adequate.

Improve com_err() logs from KDC plugin modules

---

.travis.yml

Travis appears to have deployed a testing xenial environment which
runs a daemon that sometimes interferes with apt commands.  Remove the
"dist: xenial" line so we run in the default, supported distribution
(currently trusty).
[Evidence that "dist: xenial" is hurting us with locking failures:
* https://github.com/mlpack/mlpack/blob/master/.travis.yml uses "dist: xenial" and has several iterations of workarounds for the same locking failure we've been having
* https://github.com/travis-ci/travis-ci/issues/9080
]

Back off Travis build to default dist

---

src/include/k5-trace.h
src/lib/krb5/os/sendto_kdc.c

If sendto_kdc fails to establish an MS-KKDCP connection because the
k5tls module cannot be loaded, output a trace log before closing the
connection.  Reported by Jochen Hein.

Trace log on k5tls load failure

---

src/lib/kadm5/logger.c

As a variable argument, buf.data won't be automatically cast from
void * to char * when passed to krb5_klog_syslog(), so to be correct
we must do it manually.
[Coverity caught this.  gcc issued a warning but I didn't notice, and we don't have a warning-clean gcc build restriction as yet.  clang didn't catch it for some reason.  Of course testing didn't catch it since void * and char * generally have the same representation.]

Fix type error in klog com_err hook

---

src/lib/krb5/krb/appdefault.c

Without this change, a build with gcc 7 fails with:
```
appdefault.c: In function 'krb5_appdefault_string':
appdefault.c:163:20: error: 'string' may be used uninitialized in this function [-Werror=maybe-uninitialized]
*ret_value = string;
~~~~~~~~~~~^~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [appdefault.so] Error 1
```

Initialize uninitialized variables (make gcc 7 happy)

---

src/windows/leash/LeashView.h

Commit a9cbbf0899f270fbb14f63ffbed1b6d542333641 changed three
parameters in AddDisplayItem() from long to time_t, but did not change
the corresponding declaration in LeashView.h.  Fix that now.
[http://krbdev.mit.edu/rt/Ticket/Display.html?id=8640 for context.]

Fix Leash AddDisplayItem() declaration

---

src/include/krb5/krb5.hin
src/lib/gssapi/generic/gssapi.hin

The C standard allows undefined symbols in #if statements, giving them
the value 0 (C99 section 6.10.1).  However, some software builds with
gcc -Wundef, which issues a warning on undefined symbols in
preprocessor expressions.  Make the public headers safe for that
environment by using #ifdef instead of #if for TARGET_OS_MAC.
Reported by Ben Kaduk.

Make public headers work with gcc -Wundef

---

src/lib/gssapi/generic/gssapi_ext.h

Move gss_import/export_cred to be with the rest of the GGF extensions.
Also adds clarifying comments that gss_set_cred_option and
gssspi_mech_invoke are not part of the GGF extensions.

Fix grouping of GGF extensions in gssapi_ext.h

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

Same patch has been sent to [krbdev](http://mailman.mit.edu/pipermail/krbdev/2018-February/012898.html) few days ago from my Alexandr.Nedvedicky company address.

client_pubkey always leaks in server_process_dh()

---

src/kdc/do_tgs_req.c

Same patch has been sent to [krbdev](http://mailman.mit.edu/pipermail/krbdev/2018-February/012903.html) few days ago from Alexandr.Nedvedicky company email

process_tgs_req() must release encrypting_key

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h

This is http://krbdev.mit.edu/rt/Ticket/Display.html?id=8636 converted to a PR, without any changes to the code diffs yet.
I want to poke around for less verbose approaches to converting from hex to binary, or possibly add something to libkrb5support for hex conversion.  Hex conversion is simple enough that just repeating it everywhere isn't totally unreasonable, but once you add in unit tests that stops being the case.
(It would be possible to use the OpenSSL bignum functions correctly, but by the time we added the necessary length adjustments it would be about as much code as converting from hex ourselves.  And semantically, converting a hex string to a bignum to a binary string isn't very elegant.)

PKINIT certid fixes

---

src/lib/krb5/krb/walk_rtree.c
src/tests/t_crossrealm.py

Commit b72aef2c1cbcc76f7fba14ddc54a4e66e7a4e66c (ticket 6966)
introduced k5_client_realm_path() for use on the client in place of
krb5_walk_realm_tree(), but failed to handle the special case of a
capaths "." value as is done in the latter function.  Correct that
omission and add a test case.
[In the long run it would be more elegant to handle the "." case in rtree_capath_vals(), but that's too invasive for a backport patch, and I haven't decided how much cleaning up of walk_rtree.c I want to do in a maintainability commit.]

Fix capaths "." values on client

---

src/kdc/fast_util.c
src/kdc/kdc_preauth.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h

This work is preliminary to PKINIT freshness.  It should not introduce any behavior changes.  The main goals are to eliminate the static preauth systems table so that we can explicitly decide when to add informational padata, and to incrementally allocate the hint and AS-REP padata lists instead of preallocating them.  (Preallocation is of course slightly more efficient, but it's risky unless we have a robust way of predetermining the maximum list size, and without the static preauth systems table we would be changing that each time we added a new piece of informational padata.)

KDC padata and preauth refactoring

---

src/kadmin/server/ovsec_kadmd.c

Typically, 0 denotes successful exit.  In particular, init systems
will complain if another different value is returned.  This presents a
problem for automated installation jobs which want to restart kadmind.
`service kadmin stop` typically sends SIGTERM, which is caught by
verto and passed to our handler.  Besides cleanup, we then call
verto_break(), which causes the verto_run() event loop to return.  The
weird return code has been present since the addition of the kadmin
code, which used a similar event model for signals.

Exit with status 0 from kadmind

---

src/kdc/kdc_preauth.c

sort_pa_data() could read past the end of pa_order if all preauth
systems in the table have the PA_REPLACES_KEY flag, causing a
dereference of preauth_systems[-1].  This situation became possible
after commit fea1a488924faa3938ef723feaa1ff12d22a91ff with the
elimination of static_preauth_systems; before that there were always
table entries which did not have PA_REPLACES_KEY set.
Fix this bug by removing the loop to count n_key_replacers, and
instead get the count from the prior loop by stopping once we move all
of the key-replacing modules to the front.
[I do not like sort_pa_data().  It does a complicated thing in a complicated way, mostly only affects hypothetical cases such as a client using multiple preauth requests in parallel in the same request, and does not clearly always produce …

Fix read overflow in KDC sort_pa_data()

---

src/include/k5-trace.h
src/lib/krb5/os/t_trace.ref
src/lib/krb5/os/trace.c
src/tests/t_pkinit.py
src/tests/t_preauth.py

During tracing, query the preauth context to convert the
krb5_preauthtype numbers into human-readable names for debugging.
Also add a new trace type for single padata numbers.
This is most definitely a hack.  However, since the whole preauth system is dynamic, I'm not sure how we can do better approach-wise.
A more invasive change to enable us to always have the name around a trace time is probably doable, if this/that is the correct approach.  (I'd want it in a separate commit though.)

Include preauth name in trace output where available

---

src/include/krb5/clpreauth_plugin.h
src/kdc/kdc_preauth.c
src/lib/krb5/krb/preauth2.c

These two commits clean up a couple of misbehaviors described at http://krbdev.mit.edu/rt/Ticket/Display.html?id=8642

etype-info behavior cleanups

---

src/util/profile/prof_file.c
src/util/profile/prof_int.h

If a profile file is a special device such as a pipe, then reloading
it will cause us to discard its contents.  Repurpose the first
PROFILE_FILE flag bit to indicate that the file should not be
reloaded.  In profile_update_file_data_locked(), set the flag on the
first load if stat() doesn't indicate a regular file, and check the
flag before testing whether we need to perform any subsequent reload.
Later on in profile_update_file_data_locked(), specifically unset the
DIRTY flag rather than unsetting all flags other than SHARED, so that
we don't clear the NO_RELOAD flag.
[The hardest part of this patch is figuring out what to do with that line "data->flags &= PROFILE_FILE_SHARED;".  The facts are these:
* Flags were first introduced in commit c04da8d90f3548ea66b5968e9a13fcc4a3f7c01f, with …

Avoid rereading non-regular profile files

---

src/clients/kinit/kinit.c

In kinit, if we recreate the context using kinit_kdb_init(), also
reset the global errctx so that we use the new context to retrieve
extended error messages.
[kinit should just use a global context variable like klist does.  But there are 50+ uses of "k5->ctx" which would need to be changed, which is far more than appropriate for a bugfix commit.  There is some other residual complexity left behind from supporting v4 and v5 kinit which should probably be simplified out at the same time as moving to a global context.]

Report extended errors in kinit -k -t KDB:

---

src/util/support/hex.c

hex_digit() accepts bval as an unsigned parameter, so we don't need to
test if bval >= 0.
[Coverity Scan has been down for an extended period of time due to a security breach.  When it finally came back up and we successfully ran a scan, it noticed a conditional-is-always-true defect in the new hex code.  We don't use compiler flags to detect this sort of thing, I think because we have some comparisons which are always true if char is signed, but not always true if char is unsigned, and compilers aren't smart enough to handle that.]

Remove unneeded conditional in hex.c

---

src/include/k5-buf.h
src/include/k5-int.h
src/include/k5-platform.h
src/lib/krb5/ccache/cc_file.c
src/lib/krb5/ccache/cc_keyring.c
src/util/support/k5buf.c
src/util/support/libkrb5support-fixed.exports
src/util/support/utf8_conv.c
src/util/support/zap.c

Dynamic string buffers are a good way to safely compose complex values, but when used with sensitive values, the potential to reallocate the buffer defeats our ability to correctly zero out the value after we are done with it.  These commits create a zapping k5buf variant for use with sensitive values.
(It's not great that the UTF-16 conversion function has to know that it is used for RC4 keys, but I don't have a good alternative.)

Add zapping k5buf variant

---

src/plugins/preauth/spake/openssl.c
src/plugins/preauth/spake/spake_kdc.c

[We run Coverity Scan over our code base a few times a week via a buildbot worker, but can't easily run it on pull requests at present.  For the SPAKE code, it found one memory leak and two harmless copies of krb5_data magic fields.]
In the NIST group implementations, ossl_fini() needs to free the
groupdata container as well as its fields.  Also in
spake_kdc.c:parse_data(), initialize the magic field of the resulting
data object to avoid a harmless uninitialized memory copy.

Fix SPAKE memory leak

---

src/lib/krb5/ccache/cc_kcm.c

When doing a `kdestroy -A` the current code does:
- Destroy the primary cache (by its name);
- Iterate over all the caches' uuids:
- Destroy each cache (by its uuid);
The problem with the following approach is that once the cache is
destroyed a follow GET_CACHE_BY_UUID using the primary cache's uuid will
simply fail as the uuid won't be found anymore (it's been destroyed
already).
In order to avoid such issues, let's relax the check for errors on
GET_CACHE_BY_UUID calls and when the cache is not found, let's just skip
it and continue looping over the other caches' uuid.
For some reason Heidmal's returns KRB5_CC_END when the cache is not
found and SSSD follows the very same implementation (that's the reason
we're checking KRB5_CC_END instead of KRB5_CC_NOT_FOUND).

KCM: Be tolerant to CC_END errors in ptcursor_next()

---

src/lib/krb5/krb/kfree.c

krb5_spake_factor structures will sometimes hold sensitive data when
second-factor SPAKE is implemented, so should be zapped when freed.

Zap data when freeing krb5_spake_factor

---

src/plugins/preauth/spake/spake_client.c

Asking for the AS key too early can result in password prompts in
situations where SPAKE won't proceed, such as when the KDC offers only
second factor types not supported by the client.
In spake_prep_questions(), decode the received message and make sure
it's a challenge with a supported group and second factor type
(SF-NONE at the moment).  Save the decoded message and use it in
spake_process().  Do not retrieve the AS key at the beginning of
spake_process(); instead do so in process_challenge() after checking
the challenge group and factor types.
Move contains_sf_none() earlier in the file so that it can be used by
spake_prep_questions() without a prototype.

Be more careful asking for AS key in SPAKE client

---

src/util/wshelper/dllmain.c

[I can't test this without a lot of setup, but it's really clear from code inspection that this shouldn't change the behavior apart from fixing the memory leak.  I checked that after this change there are seven initializations for seven handles; that is, the second initialization was actually a duplicate and not a failure to change a variable name.
We aren't using the Hesiod code in wshelper and could presumably rip the whole thing out, but doing that would definitely require setting up a test environment.]
Remove a double initialization of dwHesPwUidIndex in wshelper which
caused the first initialization to leak a thread-local storage handle.
Reported by Sergey Ilinykh.

Fix small leak in wshelper DLL

---

src/util/profile/prof_test1
src/util/profile/prof_tree.c
src/util/profile/test.ini

Modify profile_add_node() to return the existing node, rather than
making a new one, when adding subsection configuration.
This fixes an issue where the first instance of a subsection will hide
the second instance entirely.  In particular, it was previously
impossible to split realm-specific configuration across multiple
config files.
ticket: 7863

Merge duplicate subsections in profile library

---

src/kadmin/dbutil/kadm5_create.c

[I noticed this while debugging the LMDB KDB module I've been working on.  Normally it's not an issue because if the database is created successfully, kadm5_create() will be able to add the admin principals.]
In kadm5_create(), use the global context instead of a newly created
context, so that extended error messages are displayed properly by
extended_com_err_fn().

Display more extended errors in kdb5_util

---

src/appl/gss-sample/t_gss_sample.py
src/lib/krb5/ccache/t_cccol.py
src/lib/krb5/krb/t_vfy_increds.py
src/tests/t_authdata.py
src/tests/t_ccache.py
src/tests/t_crossrealm.py
src/tests/t_dump.py
src/tests/t_etype_info.py
src/tests/t_general.py
src/tests/t_hostrealm.py
src/tests/t_iprop.py
src/tests/t_kadmin_acl.py
src/tests/t_kdb.py
src/tests/t_keytab.py
src/tests/t_localauth.py
src/tests/t_mkey.py
src/tests/t_otp.py
src/tests/t_pkinit.py
src/tests/t_policy.py
src/tests/t_preauth.py
src/tests/t_proxy.py
src/tests/t_pwqual.py
src/tests/t_rdreq.py
src/tests/t_referral.py
src/tests/t_renew.py
src/tests/t_skew.py
src/tests/t_sn2princ.py
src/tests/t_spake.py
src/tests/t_y2038.py
src/util/k5test.py

When a Python test script fails, you get told what numbered command invocation fails and what the output was.  Usually the next step is to pull up the script in an editor and look near that command invocation for code context and/or comments to explain exactly what the script is testing.  When the test script is long and runs a lot of similar commands, it can sometimes be hard to find where the command invocation is.
These commits speed up that process by adding marks, which act as kind of categories for the test commands.  The marks do not have to be particularly meaningful; the important thing is that you can search for the last mark before a failed command and search for it in the script to quickly figure out where you should start looking.

Add marks to k5test scripts

---

src/kadmin/server/ovsec_kadmd.c

Commit 779a335f4e2deb2d76caf7d0dd3de847a040c050 added the
fail_to_start() helper in ovsec_kadmd.c, accidentally sending the
program name to stderr twice.  Remove one of them.

Fix doubled "kadmind:" in kadmind fail_to_start()

---

src/kadmin/server/Makefile.in
src/kadmin/server/deps
src/kadmin/server/ovsec_kadmd.c

setup_loop() does not need to peer into the server handle for network
parameters, as kadmind makes its own call to kadm5_get_config_params()
in main().  Use kadmind's copy of the parameters instead.
[Relevant history, which I decided not to inflict upon the commit message:
* Commit 416d9a774090ee78c30a844025887bd2b9e79d16 made kadmind aware of the internal structure of the server handle, in order to fetch the context for the KDB keytab.  That became unnecessary in commit 1b8c72b7ef064eabb37d726e831b4618cb37d2c7 when libkadm5 stopped creating internal krb5_contexts for server handles, but the code remained.
* Commit 17d926a4ce8bc2ede57a86f23948a3e9b68266a6 compounded the layering violation by pulling network params from global_server_handle even though the parameters are separately …

Avoid peeking into server handle in kadmind

---

src/kdc/Makefile.in
src/kdc/dispatch.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.h
src/kdc/t_bigreply.py

dispatch() doesn't necessarily initialize state->active_realm which
led to an explicit NULL dereference in finish_dispatch().
Additionally, fix make_too_big_error() so that it won't subsequently
dereference state->active_realm.
tags: pullup
target_version: 1.16-next
target_version: 1.15-next

Fix segfault in finish_dispatch()

---

src/clients/ksu/main.c

Most programs in the tree will perform a null dereference when argc is
zero, but as a setuid program ksu should be extra careful about memory
errors, even if this one is harmless.  Check and exit with status 1
immediately.

Check for zero argc in ksu

---

src/kadmin/server/ovsec_kadmd.c

I forgot to add 'iprop_enable = true' to kdc.conf for my test realm.
Then I tried to run kadmin with -proponly flag. It gave me message:
root@kdc1:~#  /usr/lib/krb5/kadmind -nofork -proponly
kadmind: kadmind: Invalid argument while initializing network, aborting
the message is not helpful much. My first idea was to let kadmin
fail with more user friendly message such as:
'-proponly requires to put 'iprop_enable = true' for realm in kdc.conf
thinking more about I believe the '-noprop' flag should just override
iprop_enable = false.

- better user experience with 'kadmin -proponly'

---

src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_matching.c
src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h
src/tests/t_pkinit.py

Commit 46ff765e1fb8cbec2bb602b43311269e695dbedc (for ticket 8528)
broke rule-based matching of UPN SANs using the <SAN> rule type.  To
fix this regression, make crypto_retrieve_cert_sans() return UPN SANs
in their original string form, and only parse them into principal
names in pkinit_srv.c:verify_client_san().  In
pkinit_cert_matching_data, store UPN SANs as strings separate from
PKINIT SAN principal names instead of concatenating them together, and
match original UPN strings against <SAN> rule regexps.  Add a test
case.
[This is a much larger change than I ordinarily like to backport.  I realized today that there is a pretty minimal change which would fix the regression, which is to check the name-types of principal names in the ``md->sans`` list and unparse with the NO_REALM flag if …

Fix PKINIT rule matching against UPN SANs

---

src/lib/krb5/ccache/cc_kcm.c

This matches the expected behavior from other ccache types.  Most
notably, the KEYRING equivalent was added in
c25fc42e8eac7350209df61e4a7b9960d17755ca

Set error message on KCM get_princ failure

---

src/tests/dejagnu/pkinit-certs/make-certs.sh
src/tests/dejagnu/proxy-certs/make-certs.sh

Apparently openssl never recognized this option, but previously didn't
complain about it.  Not using DES is the default, so it's safe to
remove.  This fixes make-certs.sh to run on openssl-1.1.0h.

Remove unrecognized "-nodes" argument from cert scripts

---

src/util/def-check.pl

[Fixes one of the Windows build issues mentioned in ticket 8672, but I believe we run def-check.pl on all platforms in enable-maintainer-mode so this would eventually crop up on Unix-like platforms as well.  I checked the other perl scripts in the source tree and none of them appeared to have the same problem.  Only line 89 actually causes an error, as Perl doesn't complain about open-braces in the first position (they can't introduce a quantifier there as there is nothing to quantify) or close-braces anywhere.]
Recent versions of Perl issue a warning or error when an unescaped
open curly brace is used in a position where it might introduce a
quantifier in a regular expression.  Escape all regexp literal curly
braces in dep-check.pl.

Escape curly braces in def-check.pl regexes

---

src/clients/ksu/main.c

If non-root user attempts to ksu but is denied by policy, log to
syslog at LOG_WARNING in keeping with other failure messages.
ticket: 8270

Log a message when non-root ksu authorization fails

---

appveyor.yml

Update appveyor.yml to build all of the Windows code including Leash
and the installers, using VS2017.
[Additional context for the PR:]
This change gives us much better compile-time coverage of the Windows code, which will let us avoid mistakes like the one we fixed in commit b1367abb2e2ff14446371155cb7e23a29b76aa87.  But this change is largely motivated by the SPAKE code; the edwards25519.c code borrowed from BoringSSL compiles without change in VS2017 but requires significant churn in VS2010 / SDK 7, which does not allow mixed declarations and code in C.  I will try to figure out where the cutoff point is for that (i.e. whether VS2013 and VS2015 can also build the edwards25519 code), in order to update the windows README when we add the SPAKE code.
With this update I am essentially …

Use Visual Studio 2017 in appveyor build

---

src/util/support/strerror_r.c

Commit 6351586a771e9a99e1e946cc9a0b6a87bbb14094 (ticket 7961)
introduced several variants of strerror_r().  The Windows one
contained a bug which made its return value undefined; fix that.

Fix Windows strerror_r() implementation

---

src/util/support/t_path.c

Correct all uses of side-effecting asserts in t_path.c so that it
works correctly when NDEBUG is defined.  Reported by Nehal J Wani.

Fix assert hygiene in t_path.c

---

doc/admin/conf_files/krb5_conf.rst
src/include/k5-platform.h
src/util/profile/prof_parse.c
src/util/support/Makefile.in
src/util/support/dir_filenames.c
src/util/support/libkrb5support-fixed.exports

This PR supersedes #724 using a new helper function to handle Windows.
k5_dir_filenames() is not especially general--it could be inefficient for large directories because it does a realloc() per entry, sorting with strcmp() isn't always desirable, and consumers could be interested in other dirent fields.  (For instance, when sorting for display purposes, using strcoll() to respect the locale would be better.  But if the goal is to have a predictable order, as it is in this case, strcmp() seems better.)  But we can always change it later.

Process profile includedir in sorted order

---

src/clients/kdestroy/kdestroy.c
src/clients/klist/klist.c
src/clients/kswitch/kswitch.c
src/clients/kvno/kvno.c
src/include/k5-platform.h
src/util/support/Makefile.in
src/util/support/getopt.c

Commit 8f9ade8ec50cde1176411085294f85ecfb2820a4 (ticket 8391) moved
the built-in getopt() and getopt_long() implementations from a static
library in util/windows to util/support, where (on Windows) it is
built into k5sprt32.dll or k5sprt64.dll.  The getopt() interface uses
global variables opterr, optind, optopt, and optarg, each renamed via
macro to have a k5_ prefix when we use the built-in implementation.
Data objects exported from DLLs need special handling in Windows; they
must be marked as DATA in the DLL .def file, and they must be declared
with "__declspec(dllimport)" in calling code.  Without this handling,
optind begins with a garbage value and getopt_long() returns -1
immediately, so client programs always behave as if they have no
arguments.
Stop unnecessarily declaring optind …

Fix option parsing on Windows

---

doc/admin/conf_files/krb5_conf.rst
src/Makefile.in
src/config/win-pre.in
src/include/osconf.hin
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/krb/plugin.c
src/lib/krb5_32.def
src/plugins/preauth/spake/Makefile.in
src/plugins/preauth/spake/spake.def
src/windows/README
src/windows/installer/wix/config.wxi
src/windows/installer/wix/features.wxi
src/windows/installer/wix/files.wxi
src/windows/installer/wix/platform.wxi

The first commit makes plugin auto-registration work, under the assumptions that auto-registered preauth modules will be named "modname32.dll" and "modname64.dll" and will be located in bin/plugins/preauth.  (bin because that's where the DLLs get installed.)
The second commit builds SPAKE for Windows without OpenSSL support, and adds it to "nmake install" and the installer.  Pleasantly, no code changes are required for VS2013 and later.  Some symbols are needed from libkrb5 that we don't yet export on Windows; I kept this list short by not building spake_kdc.c.
The third commit updates the README again to indicate that VS2013 or later is now required for the build, and adds support for VS2013 and VS2015 to the installer.

Windows spake support

---

doc/admin/conf_files/krb5_conf.rst
doc/admin/spake.rst
src/include/k5-int.h
src/include/k5-trace.h
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/preauth_encts.c
src/tests/t_referral.py

More at: http://krbdev.mit.edu/rt/Ticket/Display.html?id=8655
I decided to go with the simplest approach: a flag named disable_encrypted_timestamp to disable that one preauth mech on the client (not the KDC, since the necessary criteria for disabling it on the KDC are different).  Disabling SAM-2 on the client doesn't help as the KDC begins with a dictionary-attackable ciphertext in the client long-term key.  After thinking about various scenarios, disabling encrypted challenge doesn't seem necessary, whereas I can imagine a deployment wanting to disable encrypted timestamp because legitimate preauth (in that hypothetical deployment) will always use FAST.

Add flag to disable encrypted timestamp on client

---

src/lib/krb5/os/hostrealm_domain.c

In domain_fallback_realm(), if profile_get_integer() fails, uhost is
leaked.  Fix this bug by using the cleanup handler instead of
returning immediately.  Reported by Bean Zhang.

Fix minor leak in krb5_get_fallback_host_realm()

---

src/lib/krb5/krb/conv_princ.c

In krb5_524_conv_principal(), if the realm we read from the profile is
too long for the result buffer, free the profile value before
returning.
In krb5_425_conv_principal(), if krb5_get_realm_domain() fails, still
free any leftover allocated data using a cleanup label.  The only one
that could be left over is dummy_value which we could address easily
enough within the loop, but we shouldn't sidestep the cleanup code.

Fix minor leaks in principal conversions

---

src/lib/krb5/os/hostaddr.c

In k5_os_hostaddr(), if allocation of the result array fails, use the
cleanup handler so that the getaddrinfo() result is freed.  Also
initialize the pointers which are freed in the cleanup handler for
safety.  Reported by Bean Zhang.

Fix minor leak in k5_os_hostaddr()

---

src/lib/krb5/os/localauth_rule.c

In aname_replacer(), initialize current, null it when transferring
ownership to the caller, and free it on failure.  Otherwise it leaks
on failure.  Reported by Bean Zhang.

Fix minor leak in localauth RULE handling

---

src/lib/gssapi/krb5/inq_cred.c

If mechs is created but one of the generic_gss_add_oid_set_member()
calls fails, it leaks.  Initialize mechs and free it in the fail
label.  Also null mechs when we transfer ownership of it to the
caller, in case we later unify the success and failure exit paths.
Reported by Bean Zhang.

Fix minor leak in krb5_gss_inquire_cred()

---

src/kadmin/dbutil/kdb5_mkey.c

In kdb5_purge_mkeys(), if krb5_dbe_update_mkey_aux() fails, use the
cleanup label to free any allocated memory instead of returning
immediately.  Reported by Bean Zhang.

Fix minor leak in kdb5_util purge_mkeys

---

src/lib/rpc/svc_udp.c

[I checked libtirpc and this bug was already fixed before their initial import into their git repository.  Solaris also has it fixed.]
In svc_udp.c:cache_set(), if victim is allocated successfully but
allocation for newbuf fails, free victim before returning.  Reported
by Bean Zhang.

Fix minor leak in gssrpc UDP cache code

---

appveyor.yml
src/config/win-pre.in
src/lib/Makefile.in
src/windows/README
src/windows/installer/wix/Makefile
src/windows/installer/wix/config.wxi
src/windows/installer/wix/features.wxi
src/windows/installer/wix/files.wxi
src/windows/installer/wix/kfw.wxs
src/windows/installer/wix/lang/config_1033.wxi
src/windows/installer/wix/platform.wxi
src/windows/installer/wix/runtime.wxi
src/windows/leash/Makefile.in
src/windows/leashdll/Makefile.in

In the main build, set a variable BITS based on the detected CPU type,
and use it in library name expansions rather than repeatedly checking
for the same three 64-bit architectures.  Also remove an unused
variable WLIB, formerly used to name the winsock library.
In the installer build, detect the CPU type in the makefile and pass
it to candle with the -arch option.  This sets $(sys.BUILDARCH) in wix
scripts and also sets the default value of Win64 in components so we
don't have to set it for each one.
Update the build instructions and appveyor.yml to reflect that the
builder no longer needs to set CPU.

Clean up Windows build CPU detection

---

src/plugins/preauth/otp/otp_state.c
src/tests/t_otp.py

In otp_state.c:callback(), avoid invoking the failure callback on the
success path.  Since request_send() consumes the request, don't try to
free it.
(I've filed a ticket for this.)

Correctly handle success in otp_state.c's callback()

---

src/plugins/preauth/otp/otp_state.c

In read_secret_file() in the OTP kdcpreauth module, add a cleanup
label and free filename on exit.  Also fix the whitespace stripping
code to correctly find the end point, and use size_t rather than int
offsets.

Fix OTP secret file leak and whitespace removal

---

src/lib/kdb/kdb_log.c
src/slave/kproplog.c

[This change is far less minimal than I would make for a bugfix I plan to backport, but since this leak is trivial I am taking a more aggressive approach.]
Add a helper create_log_context() to initialize a krb5_context's
kdblog_context field, setting ulogfd to -1.  Use it in ulog_set_role()
and ulog_map().  In ulog_fini(), release ulogfd if it is not -1.
In ulog_map(), add a cleanup label and use it to finalize the log
context on failure, so that we don't (trivially) leak the mapped ulog.
To reduce the number of "retval = errno;" statements required for this
change, make extend_file_to() return a krb5_error_code.
The ulog leak on error was reported by Bean Zhang.

Improve ulog memory hygiene

---

src/tests/gssapi/t_ccselect.py

[Noticed while migrating my dev environment to an Ubuntu 18.04 VM where "localhost" canonicalizes to "localhost6.localdomain6".]
DNS canonicalization can interfere with the fallback tests by changing
"localhost" to have multiple components, or (less likely) changing the
parent domain of foo.krbtest.com or foo.krbtest2.com.

Disable canonicalization in ccselect tests

---

src/lib/krb5/krb/Makefile.in
src/plugins/preauth/spake/Makefile.in

I also looked into modifying travis.yml to detect future omissions in make clean.  I got as far as:
git ls-files -o -x Makefile -x "*.pc" -x config.log -x config.status -x autoconf.h -x krb5-config
which we would then have to check for non-empty output.  The various -x options could be replaced with -X filename if we wanted to add a file containing the patterns.  Integrating that into the .travis.yml script (which is a long sequence of "a && b && ..." because travis doesn't abort on error) seems a bit messy.

Fix some omissions in make clean

---

.travis-ci.sh
.travis.yml

[The name ``.travis-ci.sh`` is cribbed from the ocaml repository, found by googling for "travis.yml sh ex".]
Move the build commands to a shell script, run with the -e flag so any
failure causes the script to exit.  In the script, verify that "make
distclean" removes everything produced by "make" and "make check".

Check distclean target in Travis build

---

doc/admin/admin_commands/krb5kdc.rst
src/kdc/main.c

Now that the KDC listens for TCP connections by default (ticket 6731),
the "-p" flag should affect both UDP and TCP default listening ports.

Make krb5kdc -p affect TCP ports

---

src/util/k5test.py

With Python 3, sys.stdout.write() of a partial line followed by
sys.stdin.readline() does not display the partial line.  Add explicit
flushes to make prompts visible in k5test.py.

Fix k5test prompts for Python 3

---

doc/admin/admin_commands/kadmin_local.rst
doc/admin/conf_files/kdc_conf.rst
src/appl/user_user/t_user2user.py
src/kdc/tgs_policy.c

Here is the change to allow u2u tickets with -allow_svr.  As briefly discussed on the krbdev list, this trues up the code and the error message (the KDC errors for u2u requests with KDC_ERR_MUST_USE_USER2USER, which is confusing).  I also found an old bug for this issue while searching, so I've added that link below.
I've been testing this change in production for years on 1.9, and just recently ported it to the latest code.
One question: should I make the same check in check_tgs_svc_deny_all()?  It looks like it, but I never had to in my testing...I'm not exactly sure what that code is for, it looks like some kind of policy check function table?  It'd be a trivial fix to make obviously.
The other place KRB5_KDB_DISALLOW_SVR is checked is in kdc_get_server_key(), but there's no …

Allow u2u requests when KRB5_KDB_DISALLOW_SVR is set

---

src/appl/gss-sample/gss-misc.c

There are some GSS mechanisms (such as GSS EAP - RFC 7055) where User interaction is required and 10s is too little to allow users to eg. select the identity they want to use or type their password.

Extend waiting time from 10s to 30s

---

src/lib/krb5/ccache/cc_memory.c
src/lib/krb5/ccache/t_cccol.py

[This is preliminary to using a hash table for memory ccache resolution, which I've gotten a request for.]
In the MEMORY ccache implementation, only yield a cache in the
per-type cursor if it is the context default cache, matching the
behavior of FILE after commit 45360c9688ca963f75a2480f2cf818424fc3dc7b
(ticket 6955).

Don't include all MEMORY ccaches in collection

---

doc/user/user_commands/kdestroy.rst
src/clients/kdestroy/kdestroy.c
src/tests/t_ccache.py

[Requested by simo.]
Add an option to destroy a cache within a collection by principal
name.  This option can be used together with -c to specify the
collection.  Also document that kdestroy -A and -c can be used
together (ticket 8602).

Add kdestroy -p option

---

src/lib/krb5/krb/t_valid_times.c
src/lib/krb5/os/read_pwd.c
src/util/profile/prof_test1
src/util/profile/profile_tcl.c

A new dev machine means a new version of clang, which means new things detected by clang.  One of these is a harmless-in-practice memory bug in krb5_read_password() which has been present since 2004: if prompt2 is given, k5prompt.reply is pointed at a krb5_data object inside an inner scope, and then `k5prompt.reply->length`` is referenced just after that object goes out of scope.  Since there are no new stack allocations in the interim, it works.  I didn't make the fix minimal since there's no need to backport it.

asan fixes

---

doc/about.rst
doc/admin/conf_ldap.rst
doc/appdev/gssapi.rst
doc/build/doing_build.rst
doc/build_this.rst
doc/mitK5features.rst
doc/notice.rst
doc/plugindev/general.rst
doc/resources.rst

[web.mit.edu is supposed to change to not require client certs for https in two days.  I will not merge this until that cutover has finished.]
Use secure URLs in the documentation where possible.  The Sphinx web
site does not appear to have a valid server cert, but does have a more
official URL.

Update many documentation links to https

---

doc/user/user_commands/kswitch.rst

Fix a typo introduced by commit
fe44da52deea41483326debf2d9ad525f65e19f6.  Reported by Matthew
Krupcale.

Fix a typo in the kswitch man page

---

src/lib/gssapi/mechglue/g_export_cred.c

In gss_export_cred(), check the gssint_get_public_oid() result as well
as the gssint_get_mechanism() result.  There are probably no cases
where the former returns NULL and the latter does not, but it is easy
to be more obviously correct.  Reported by Bean Zhang.

Check public_oid in gss_export_cred()

---

.gitignore
src/include/k5-hashtab.h
src/kdc/replay.c
src/kdc/t_replay.c
src/lib/krb5/ccache/cc_memory.c
src/util/support/Makefile.in
src/util/support/deps
src/util/support/hashtab.c
src/util/support/libkrb5support-fixed.exports
src/util/support/t_hashtab.c

We got a request to use a hash table for resolving MEMORY ccaches so that they perform reasonably when a process contains many of them.  I could only find one other use of an in-memory hash table in the code.  Two uses is enough to justify a libkrb5support facility, so I added one.
I discovered that murmurhash3 isn't all that resistant to hash flooding attacks and that general-purposes languages with dictionaries now use siphash.  There some liberally-licensed implementations of siphash, but it's also easy to implement from the paper, and that way I could tailor the implementation to fit our platform primitives and the hash table code.
The hash table code is dead simple, partly because with only two callers it doesn't have to handle very diverse requirements.

Hash table for memory ccache resolution

---

doc/user/user_commands/kvno.rst
src/appl/user_user/t_user2user.py
src/clients/kvno/kvno.c
src/tests/Makefile.in
src/tests/t_u2u.py

[Will allow a proper test for #823.  Some subtleties:
* The server name has to match the u2u ccache default principal, which means we don't strictly need it to be given as an argument.  But deducing the server name from the u2u ccache would be awkward as it would break code symmetry with the other use cases.
* In principle we could decrypt the returned ticket using the session key from the u2u ccache, but there is no libkrb5 interface like krb5_server_decrypt_ticket_keytab() for doing so.
* At the protocol level, I don't see any reason why the second ticket can't be encrypted in a cross-realm TGT, although I can't think of any reason to do so and our KDC implementation doesn't allow it.  This kvno option only looks for a local TGT.
* I considered adding long options --enctype, --cache, …

Add kvno option for user-to-user

---

src/lib/krb5/ccache/cc_retr.c
src/lib/krb5/krb/gc_via_tkt.c
src/tests/t_u2u.py

Here is my fix for ticket 8718.  Review it commit-by-commit as the third commit is a style fix (the second commit is minimal but leaves the function in an awkward state).
Chris Hecker recently floated the idea of a kvno option to get user-to-user creds; if we had that, we could write a test case for this fix.  So there is a chance I will defer merging this until he or I implements that kvno option.

Stop matching u2u credentials on regular searches

---

src/lib/kadm5/alt_prof.c

When copying the realm string, if strdup() returns NULL, fail out with
ENOMEM instead of pretending the realm wasn't specified.  When copying
KRB5_DEFAULT_SUPPORTED_ENCTYPES, if strdup() returns NULL, fail out
with ENOMEM instead of crashing.  Reported by Bean Zhang.

Check strdup return in kadm5_get_config_params()

---

src/kadmin/cli/kadmin.c
src/kadmin/dbutil/kdb5_mkey.c
src/kadmin/ktutil/ktutil.c
src/kadmin/server/misc.c
src/lib/kadm5/chpass_util.c
src/lib/kadm5/logger.c
src/lib/krb5/krb/str_conv.c
src/slave/kproplog.c

Where ctime(), localtime(), or localtime_r() is used, check for
failure even if it is unlikely (reported by Bean Zhang).  Constify the
strdate() return type in kdb5_mkey.c and the ctime_uint32() return
type in kproplog.c.  Use localtime_r() unconditionally in str_conv.c
as there is already a wrapper in that file for the case where the
platform doesn't have it.  Remove an inoperative localtime() call in
ktutil.c.

Check return values of time functions

---

src/ccapi/test/Makefile.in

A few days ago, something changed about the appveyor build image (probably a MSVC update) which caused our builds to start failing with:
```
cl   /I..\.. /I..\..\include /I..\..\include\krb5   -I..\..\util\et /I. -I..\..\CCAPI\COMMON -I..\..\CCAPI\LIB -I.\..\..\include -I.\..\..\include\krb5 -DKRB5_DNS_LOOKUP=1 -DWIN32_LEAN_AND_MEAN -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE -D_CRT_SECURE_NO_DEPRECATE -DUSE_LEASH=1 -DDEBUG -D_CRTDBG_MAP_ALLOC  /EHsc -D_CRTAPI1=_cdecl -D_CRTAPI2=_cdecl -DWINVER=0x0501  -D_WIN32_WINNT=0x0501 -D_CRT_SECURE_NO_WARNINGS /Od /Zi /MDd -nologo /EHsc /W3 -Fdobj\AMD64\dbg\\ -FD  -Fe.\ccapi_test\tests\test_cc_ccache_iterator_next.exe -Fd.\ccapi_intermediates\test_cc_ccache_iterator_next.obj test_cc_ccache_iterator_next.c obj\AMD64\dbg\test_ccapi_ccache.obj …
```

Fix name of .pdb file in ccapi/test/Makefile.in

---

src/lib/kadm5/logger.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c

[Coverity pointed out a couple more of these that I had missed.]
In logger.c:klog_vsyslog(), check the return value of localtime().  In
ldap_principal2.c:getstringtime(), check the strftime() result and
don't leak strtime on error.

Check more time function results

---

src/lib/gssapi/mechglue/g_inq_cred.c

[Discovered while working on gss_add_cred() fixes, because I want to use gss_inquire_cred_by_mech() with non-present mechs in the test cases.  RFC 2744 doesn't say anything explicit about what this behavior should be, but our behavior is clearly wrong.  The Solaris mechglue returns GSS_S_DEFECTIVE_CREDENTIAL in this case, but I decided to be consistent with Heimdal.]
If gss_inquire_cred_by_mech() is called with a mechanism and there is
no corresponding mechanism credential in the union cred, return
GSS_S_NO_CRED (as Heimdal does) instead of interrogating the mechanism
about the default credential.

Check mech cred in gss_inquire_cred_by_mech()

---

.gitignore
src/lib/gssapi/mechglue/g_acquire_cred.c
src/tests/gssapi/Makefile.in
src/tests/gssapi/t_add_cred.c
src/tests/gssapi/t_gssapi.py

If gss_add_cred() is called with no input_cred_handle, it creates a
new credential with one element.  At the end of the function, use the
created credential as the output container, rather than creating a
second one and leaking the first.
Add a test program for gss_add_cred() and run it.

Fix memory leak in gss_add_cred() creation case

---

src/lib/gssapi/mechglue/g_acquire_cred.c
src/tests/gssapi/t_add_cred.c

If gss_add_cred() is called with both an input_cred_handle and an
output_cred_handle, it creates a new credential with the elements of
the input credential plus the requested element.  Making a shallow
copy of mechs_array and cred_array from the old credential creates
aliased pointers which become invalid when one of the two credentials
is released, leading to use-after-free and double-free errors.
Instead, make a full copy of the input cred for this case.  Make this
copy at the beginning so that union_cred can always be modified in
place (and freed on error using gss_release_cred() if we created it),
removing the need for new_union_cred, new_mechs_array, and
new_cred_array.  Use a stack object for target_mechs to simplify
cleanup and reduce the number of failure cases.
GSSAPI provides no …

Fix memory bugs in gss_add_cred() extension case

---

src/lib/rpc/clnt_udp.c

gcc warns that the `if` statement doesn't guard the length
assignment, which is true.  However, it wouldn't make sense for the
length assignment to be guarded by the `if` clause anyway, since the
previous statement is a `goto`.  De-indent for clarity.

Fix misleading indentation in clnt_udp.c

---

src/lib/gssapi/mechglue/g_acquire_cred.c
src/tests/gssapi/t_add_cred.c

Remove the conditionalization around the desired_name processing in
gss_add_cred_from(), so that we always honor the requested name.

Always honor desired_name in gss_add_cred()

---

src/Makefile.in
src/plugins/kdb/ldap/deps
src/plugins/kdb/ldap/libkdb_ldap/deps
src/plugins/kdb/ldap/libkdb_ldap/lockout.c
src/plugins/kdb/ldap/libkdb_ldap/princ_xdr.c
src/plugins/kdb/ldap/libkdb_ldap/princ_xdr.h

[Yang Xiao reported that the LDAP version of xdr_nullstring() didn't contain the same fix to check for terminating null bytes as the libkadm5srv version.  This doesn't manifest as a bug because we only call the LDAP version on marshalled tl-data values we created ourselves based on the normalized policy name and password history attributes.  But there's no reason to have the duplicate version of these marshalling functions at all, so here is a PR to get rid of them.]
The LDAP KDB module contained a duplicate set of functions to marshal
osa_princ_ent_ret structures, perhaps to avoid a circular dependency
on libkadm5srv before KDB modules were dynamically loaded.  We have
been using the libkadm5srv versions of those functions from the DB2
KDB module since release 1.8.  Use them from the …

Remove LDAP osa_princ_ent_rec XDR functions

---

src/kadmin/cli/getdate.y

Commit 28fd0a934cdc7b3b42ce213c6d334d4edf1ab591 muted a warning from bison
about shift/reduce conflicts in the grammer.  However, the extension for
suppressing the warning is bison-only.  Revert that portion of the change and
live with the warning rather than adding additional conditionalization.
Reported by Michael Osipov.

Fix getdate.y compatability with POSIX yacc

---

src/util/ss/listen.c

readline() is careful not to read more bytes from fd 0 than it has to.
Do the same in the dummy libss readline() by disabling stdin
buffering.

Disable stdin buffering in libss dummy readline

---

.gitignore
doc/admin/admin_commands/ktutil.rst
doc/appdev/refs/api/index.rst
src/include/krb5/krb5.hin
src/kadmin/ktutil/ktutil.c
src/kadmin/ktutil/ktutil.h
src/kadmin/ktutil/ktutil_funcs.c
src/lib/krb5/krb/Makefile.in
src/lib/krb5/krb/get_etype_info.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/preauth2.c
src/lib/krb5/krb/t_get_etype_info.c
src/lib/krb5/krb/t_get_etype_info.py
src/lib/krb5/libkrb5.exports
src/lib/krb5_32.def
src/tests/t_keytab.py

AS_REQ message is sent to KDC and enctype, salt and s2kparams are retrieved from AS_REP/ERROR
message sent back from KDC.
This function will help ktutil use the correct salt and s2kparams associated with the principal when creating keytabs.

Public function to retrieve enctype, salt and s2kparams from KDC

---

src/lib/krb5/os/changepw.c

When password changes are performed over UDP, spotty networks may
cause the client to retransmit.  This leads to replay errors if the
kpasswd server receives both requests, which hide the actual request
status and make it appear that the password has not been changed, when
it may in fact have been.  Use TCP instead with UDP fallback to avoid
this issue.
~~Modernize change_set_password and make a helper function,
change_set_password_proto.~~
ticket: 7905

Prefer TCP to UDP for password changes

---

src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h

as needed for cross realm protocol-transition to work.
See MS-SFU 3.2.5.1.1 for details.
This has been previously explicitly disabled in order
to preserve old behaviour which seem like a bug.
See discussion at:
http://mailman.mit.edu/pipermail/krbdev/2018-September/012992.html

Allow referrals for S4U2Self requests

---

src/include/port-sockets.h
src/lib/krb5/os/net_write.c

Add casts to ensure that the result type of SOCKET_WRITEV() on Windows
can represent -1.  Otherwise it will be treated as 2^32-1 when cast to
ssize_t on 64-bit Windows.

Fix 64-bit Windows socket write error handling

---

src/include/kdb.h

[As noted in PR #857, the alternative here is to change kdc_process_s4u2self_req() to pass ALIAS_OKAY to get_principal when looking up the requested client principal.  We always use the client's requested name for the ticket, so there probably wouldn't be any harm in that.]
Enterprise principals are always aliases.  In most contexts when we
see them we pass KRB5_KDB_FLAG_ALIAS_OK to the KDB module's
get_principal method, but for S4U2Proxy clients we currently do not.
Document that a KDB module may return an alias for enterprise
principals regardless of flags.

Document aliases for enterprise get_principal

---

src/lib/krb5/ccache/cc_kcm.c

Commit 33634a940166d0b21c3105bab8dcf5550fbbd678 accidentally changed
the return value from kcmio_unix_socket_write to be the result of the
write call.  Most commonly this resulted in it returning 8, which led
to many commands failing; for instance:
kinit: Exec format error while getting default ccache
tags: pullup
target_version: 1.17-next

Fix spurious errors from kcmio_unix_socket_write

---

src/tests/kcmserver.py
src/tests/t_ccache.py

[I originally wrote the testing KCM server in C, handling just one connection at a time, but discovered that some of the commands run by t_ccache.py open multiple connections.  I then switched to Python, reasoning that it would be a lot of code to handle multiple connections in C, and that a KCM server can mostly get away with saving the marshalled forms of principal names and credentials without unpacking them.
I am 90% comfortable with that decision, but there are a few things that could push me back towards C.  First, if we ever need this testing server to implement remove_cred, we need to be able to unpack a "cred tag" (matching credential) and match it against previously stored creds.  Second, the C code probably wouldn't be _that_ bad, since in a testing server we can block while …

Add tests for KCM ccache type

---

src/kdc/kdc_util.c
src/lib/krb5/krb/s4u_creds.c
src/tests/gssapi/t_s4u.py

This allows protocol transition to work even if
the password has expired or needchange (same as
in Windows implementation).
Also, when looking up an enterprise principal with an
AS request, treat ERR_KEY_EXP as a sign that the realm
was found, and proceed with S4U2Self TGS request.
Signed-off-by: Isaac Boukris <iboukris@gmail.com>

Ignore password attributes for S4U2Self requests

---

doc/user/user_commands/ksu.rst
src/clients/ksu/main.c

Add ksu -F and -P options to explicitly not request forwardable and
proxiable tickets.

Add ksu option for non-forwardable tickets

---

src/clients/ksu/heuristic.c

if list_union fails, then close_time will attempt to fclose users_fp
and login_fp a second time.  However, the only way this can occur is
via an allocation failure in list_union, which being of fixed size is
highly unlikely.
This was originally introduced in
be95b52c2d0c21b1fe92f9f90166fc2fa8eecc95, meaning it has been present
in every krb5 release since 1.1.

Fix double-close in ksu's get_authorized_princ_names

---

src/kdc/kdc_preauth.c
src/tests/gssapi/t_s4u.py

The assertion in return_enc_padata() is reachable because
kdc_make_s4u2self_rep() may have previously added encrypted padata.
It is no longer necessary because the code uses add_pa_data_element()
instead of allocating a new list.
CVE-2018-20217:
In MIT krb5 1.8 or later, an authenticated user who can obtain a TGT
using an older encryption type (DES, DES3, or RC4) can cause an
assertion failure in the KDC by sending an S4U2Self request.
[ghudson@mit.edu: rewrote commit message with CVE description]

Remove incorrect KDC assertion

---

doc/admin/conf_files/krb5_conf.rst
src/include/k5-int.h
src/include/k5-trace.h
src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/krb/t_copy_context.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sn2princ.c
src/tests/gcred.c
src/tests/t_sn2princ.py

Turns it into a three-state that allows the value "fallback" on top
of the true/false booleans supported previously.
When the option is set to fallback we dealy canonicalization and attempt
it only in krb5_get_credentials() if the KDC responds that the requested
server principal name is unknown.

Change dns_canonicalize_hostname profile option

---

src/configure.in
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
src/plugins/preauth/spake/edwards25519.c
src/plugins/preauth/spake/util.c
src/util/support/Makefile.in

gcc we use on Solaris complains about empty initialization. This small patch
makes it happy.
I gave a try to krb5-1.17-beta2

imporomper initialization breaks compilation on Solaris

---

src/clients/ksu/krb_auth_su.c
src/lib/gssapi/krb5/iakerb.c
src/lib/kadm5/srv/svr_principal.c
src/lib/krb5/asn.1/asn1_k_encode.c

Ilja Van Sprundel reported a list of memset() calls which gcc
optimizes out.  In krb_auth_su.c, use zap() to clear the password, and
remove two memset() calls when there is no password to clear.  In
iakerb.c, remove an unnecessary memset() before setting the only two
fields of the IAKERB header structure.  In svr_principal.c, use
krb5_free_key_keyblock_contents() instead of hand-freeing key data.
In asn1_k_encode.c, remove an unnecessary memset() of the kdc_req_hack
shell before returning.

Address some optimized-out memset() calls

---

src/configure.in
src/include/k5-platform.h

See https://bugs.llvm.org/show_bug.cgi?id=15495

k5-platform: Avoid allocating a register for protecting memset()

---

src/clients/klist/klist.c
src/include/k5-int.h
src/kadmin/cli/kadmin.c
src/kdc/kdc_log.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/main.c
src/kprop/kpropd.c
src/lib/crypto/krb/crypto_int.h
src/lib/crypto/krb/enctype_util.c
src/lib/crypto/krb/etypes.c
src/lib/crypto/libk5crypto.exports
src/lib/krb5/krb/rd_req_dec.c
src/lib/krb5_32.def
src/tests/gssapi/t_enctypes.py
src/tests/t_keyrollover.py
src/tests/t_sesskeynego.py

First commit augments the constants with their human-readable names.
Second commit augments that logging with all-caps information that the etype in question is deprecated.  I didn't mark the PKINIT etypes as deprecated because I couldn't find formal docs that they are, but am happy to change that.

enctype logging updates

---

doc/tools/docmodel.py
doc/tools/doxybuilder_funcs.py
doc/tools/doxybuilder_types.py
src/doc/Makefile.in

[Commit a7c6d98480f1e33454173f88381921472d72f80a updated the doc build to work with python3-sphinx, but the code that translates from Doxygen XML output to RST was still in Python 2, so "make html" in a build tree fails now that we look for Python 3 in configure.in.
The Python 3 version of the Cheetah templating engine is not present in Ubuntu before 18.10, so I grabbed it with pip for now.  Given the resources, we might consider moving to Mako or not using a template engine, but I don't have immediate plans to do either.]
Also remove a debugging print from DocModel.__repr__.

Update doxygen-RST bridge to Python 3

---

doc/appdev/h5l_mit_apidiff.rst
doc/appdev/refs/api/index.rst
src/include/krb5/krb5.hin
src/lib/krb5/ccache/cc-int.h
src/lib/krb5/ccache/cc_dir.c
src/lib/krb5/ccache/cc_file.c
src/lib/krb5/ccache/cc_kcm.c
src/lib/krb5/ccache/cc_keyring.c
src/lib/krb5/ccache/cc_memory.c
src/lib/krb5/ccache/cc_mslsa.c
src/lib/krb5/ccache/ccapi/stdcc.c
src/lib/krb5/ccache/ccapi/stdcc.h
src/lib/krb5/ccache/ccbase.c
src/lib/krb5/ccache/cccursor.c
src/lib/krb5/ccache/ccfns.c

r20743 (part of 1.7) added new ccache functions to krb5.h, but not
either exports list.  Though ad5aa12f13aad7ec4cafcffeec4f2e84e56c9c78
exported krb5_cc_move, the rest remain unexported.
krb5_cc_lock, krb5_cc_unlock, krb5_cccol_lock, and krb5_cccol_unlock
are used internally, so remove them from krb5.h and rename k5_cc_lock,
k5_cc_unlock, k5_cccol_lock, and k5_cccol_unlock, respectively.
krb5_cccol_last_change_time is not used, so remove it.
krb5_cc_last_change_time is also not used, so remove it as well.
Update ccache interface to reflect removal.  Of particular note, this
function didn't behave as documented for MEMORY or KEYRING ccaches at
time of removal.
ticket: 7765

Match ccache functions in krb5.h with export list

---

src/lib/gssapi/spnego/gssapiP_spnego.h
src/lib/gssapi/spnego/spnego_mech.c
src/tests/gssapi/t_err.c
src/tests/gssapi/t_gssapi.py

Fixes an issue where if a SPNEGO initiator receives a `NegTokenResp` where `negState` is `reject`, it will immediately return to the caller, rather than processing any (mechanism-specific) context error tokens from the acceptor.
NB: still checking I have read RFC4178 correctly and it is OK to return a `responseToken` with a reject response.

SPNEGO: Pass mechanism error token status to application

---

src/lib/krb5/ccache/ccbase.c

The cleanup code only could get executed in the USE_CCAPI_V3 case, so
move it inside that block.  Reported by Coverity.

Properly size #ifdef in k5_cccol_lock()

---

src/lib/krb5/rcache/rc_none.c

Commit 0f06098e2ab419d02e89a1ca6bc9f2828f6bdb1e fixed part of a memory
leak in the 'none' replay cache type by freeing the outer container,
but we also need to free the mutex.
[ghudson@mit.edu: wrote commit message]

Fix memory leak in 'none' replay cache type

---

src/config/post.in
src/configure.ac
src/include/Makefile.in
src/util/check-ac-syms
src/util/getsyms

autotools plans to drop support for the name configure.in.
(automake's NEWS file expresses plans to drop support for it in
autoconf 2.0; autoconf added a warning in commit
560f16b52d3d3db1536d9ca5b863ce9b1a5c9e35, indicating in the commit
message that support will be dropped in a future version.)

Rename configure.in to configure.ac

---

src/tests/asn.1/ktest_equal.c

One of the comparisons in ktest_equal_secure_cookie() was
tautological.  Use scalar_equal() for consistency with other tests.

Fix ASN.1 test secure cookie comparison

---

src/include/k5-trace.h
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/preauth2.c
src/lib/krb5/krb/s4u_creds.c
src/tests/gssapi/t_s4u.py

Realm identification for S4U2Self requests ([MS-SFU] 3.1.5.1.1.1) uses
the AS code path with some differences: we might want to include a
subject certificate in pa-data, we want to stop as soon as we get a
reply indicating which realm the client is in, and we want to
communicate that realm to the caller.  The current method of making
these changes is fragile--it uses an optimistic preauth type but does
not actually pre-authenticate, and it assumes that the AS code will
terminate with a predictable error if there is no prompter and a
trivial GAK function.
Instead, add fields to krb5_get_init_creds_context for realm
identification, and support them in the AS state machine, making sure
never to invoke preauth modules.  Add a new library-internal function
k5_identify_realm() to set up an …

Improve S4U2Self realm identification internals

---

doc/basic/ccache_def.rst

Referencing the comment here: https://github.com/krb5/krb5/blob/444a15/src/lib/krb5/ccache/cc_dir.c#L38

Document the double-colon behavior of DIR ccaches

---

src/include/k5-int.h
src/lib/krb5/krb/mk_cred.c
src/lib/krb5/krb/mk_priv.c
src/lib/krb5/krb/mk_safe.c
src/lib/krb5/krb/rd_safe.c

This feels a bit niche (only five uses, all in the libkrb5 message-handling code) but it seems like a reasonable helper to have on principal.  The proximal motivation is to squelch the Coverity false positive referred to in PR #900.

zapfreedata

---

src/lib/krb5/krb/auth_con.c
src/lib/krb5/rcache/t_memrcache.c

This was an unusually bad botch.  asan would have caught it, but I didn't run it against the memory replay cache code.  Coverity caught it.

Fix free of auth context memory replay cache

---

src/plugins/kdb/test/kdb_test.c

[Also caught by Coverity.]
test_get_s4u_x509_principal() needs to free canon before exiting.

Fix memory leak in test KDB module

---

doc/build/options2configure.rst
src/aclocal.m4
src/configure.ac

- There are instances where it is advantageous to be able to
turn off the keyring ccache feature when compiling on Linux.
This patch adds --disable-keyring-ccache as an option to
the configure script.
Signed-off-by: Robert Marshall <rmarshall@gitlab.com>

Add option to build without libkeyutils

---

src/windows/leash/KrbListTickets.cpp

[This relates to reports from a couple of users at MIT.  Ordinarily I like to have a better understanding of problems before patching around them, but in this case I can't easily investigate further.]
Under some circumstances (perhaps related to a February Windows 10
update), Leash can get past the krb5_cc_get_principal() step when
processing an empty MSLSA ccache, and get a KRB5_CC_NOMATCH error from
krb5_cc_start_seq_get().  Do not display a modal error dialog if this
happens.

Suppress krb5_cc_start_seq_get() popups in Leash

---

src/include/krb5/krb5.hin
src/lib/krb5/ccache/cc_file.c
src/lib/krb5/ccache/cc_keyring.c
src/lib/krb5/ccache/cc_memory.c
src/lib/krb5/ccache/t_cc.c

Previously, only KCM and MSLA implemented credential removal.  Add
support for MEMORY and FILE (and therefore DIR), matching Heimdal's
implementations.  Also add a new implementation for KEYRING.

Implement krb5_cc_remove_cred for remaining types

---

src/lib/krb5/ccache/cc_file.c

[I missed this in review, but Coverity found a forward-null and reverse-null defect on the same line.  We should never use C string functions on krb5_data values as they are not guaranteed to be zero-terminated.]
Use data_eq_string() to check the server realm, and do not check if
cred->server is NULL since it is not expected to be (and
k5_marshal_cred() would have already crashed if it were).

Fix config realm change logic in FILE remove_cred

---

src/lib/krb5/ccache/cc_file.c

As part of error handling in d3b39a8bac6206b5ea78b0bf6a2958c1df0b0dd5,
an error path in delete_cred() may result in close(-1).  While this
shouldn't be a prolblem in practice (just returning EBADF), it does
upset Coverity.

Fix potential close(-1) in cc_file.c

---

doc/appdev/gssapi.rst

The example code for gss_get_mic_iov() using a caller-provided buffer
calls gss_wrap_iov_length() and gss_wrap_iov() instead of
gss_get_mic_iov_length() and gss_get_mic_iov() as intended.  Reported
by Frank Filz.

Fix gss_get_mic_iov() example code

---

src/configure.ac

[We got a report from someone who had built a custom system where readline was built against libncursesw instead of libncurses.  This approach will generate better shared library dependencies.  It won't work well on platforms which use all static libraries or don't have shared library dependencies, but I'm not too concerned about that since linking against libreadline isn't the default.  People can set LIBS to compensate in a pinch.  There is an AX_LIB_READLINE in the autoconf archive, but it's a little annoying to use within the source code so I'm going to pass on that until it seems like there's a need.  Unfortunately readline doesn't seem to participate in pkg-config so that's not an option.]
If configure is explicitly asked to build with libreadline, look for
and link against only …

Simplify libreadline configure support

---

src/lib/crypto/openssl/hmac.c
src/lib/crypto/openssl/pbkdf2.c

[https://github.com/openssl/openssl/pull/6674 was set to cause OpenSSL's PBKDF2 to return an error on empty salt, which was caught by the inclusion of the MIT krb5 test suite in OpenSSL's CI.  In the process I noted that our code wasn't checking the return value, which runs the risk of returning successfully with uninitalized memory in the string-to-key result.  Today I did a review of the OpenSSL backend and found that we also don't check errors for some calls within krb5int_hmac_keyblock().]
In krb5int_hmac_keyblock() and krb5int_pbkdf2_hmac(), check for errors
from previously unchecked OpenSSL function calls and return
KRB5_CRYPTO_INTERNAL if they fail.
HMAC_Init() is deprecated in OpenSSL 1.0 and later; as we are
modifying the call to check for errors, call HMAC_Init_ex() instead.

Check more errors in OpenSSL crypto backend

---

src/configure.ac
src/include/k5-platform.h
src/lib/kadm5/alt_prof.c
src/lib/krb5/ccache/ccselect_k5identity.c
src/lib/krb5/os/ccdefname.c
src/lib/krb5/os/expand_path.c
src/lib/krb5/os/init_os_ctx.c
src/lib/krb5/os/ktdefname.c
src/lib/krb5/os/trace.c
src/lib/krb5/rcache/rc_base.c
src/lib/krb5/rcache/rc_io.c
src/plugins/preauth/pkinit/pkinit_identity.c
src/plugins/tls/k5tls/openssl.c
src/util/profile/prof_file.c
src/util/support/Makefile.in
src/util/support/secure_getenv.c

The first commit is a placeholder for now.  I'm submitting this early to have a place to discuss implementation details (or at least record my own thoughts on them).
The goal here is to automatically ignore environment variables in our libraries when the process has higher privileges than its environment.  Currently we have a programmatic way to create "secure" krb5_contexts which ignore most environment variables; we have no story for GSS.
On glibc 2.17+, secure_getenv() solves the problem.  Its semantics seem solid as far as I can tell.  None of the other platforms I looked at have secure_getenv(), and I don't think other libc implementations for Linux have it.
On Windows there is, as far as I know, never a need to ignore the process environment.
An imperfect but simple fallback to …

Secure getenv

---

src/lib/krb5/krb/preauth_sam2.c

[Prompted by one of the changes in PR #922]
The ctx->gak_fct() call in sam2_process() used an empty salt instead
of the default salt when the KDC did not supply an explicit salt.
Commit bc096a77ffdab283d77c2e0fc1fdd15b9f77eb41 changed the contracts
around salts but did not adjust the SAM-2 code.  Commit
e9aa891fcdb4c08d39902ab89afb268042b60c86 fixed the resulting bug, but
mistakenly did not adjust the gak_fct call to use the correct salt.
Later on, the code contains a redundant call to krb5_c_string_to_key()
in the non-USE_SAD_AS_KEY modes, replacing ctx->as_key with the same
value as gak_fct had already suppplied.  This call was properly
adjusted by commit e9aa891fcdb4c08d39902ab89afb268042b60c86, so the
improper gak_fct call did not manifest as a bug.
Fix the gak_fct call to supply the …

Simplify SAM-2 as-key handling

---

src/lib/crypto/builtin/pbkdf2.c

NetBSD's libc includes a hmac() function as well; this avoids a
build problem on NetBSD.

Rename hmac() function.

---

.travis-ci.sh
.travis.yml
src/lib/crypto/openssl/enc_provider/rc4.c

This matches closely the job that OpenSSL uses ([krb5.sh](https://github.com/openssl/openssl/blob/master/test/recipes/95-test_external_krb5_data/krb5.sh)) and is part of the one I use in Fedora ([krb5.spec](https://github.com/frozencemetery/krb5.fedora/blob/master/krb5.spec#L299)).
I considered making this a full "non-builtin" job, but that didn't seem especially useful given what Travis is running.

Add a Travis job for building with OpenSSL crypto exclusively

---

src/clients/ksu/Makefile.in

Include the /usr tree and .../sbin variants.  Drop nonstandard /local.
Also-authored-by: Nalin Dahyabhai <nalin@redhat.com>
(This patch has been carried in Fedora since 2011 against 1.10.)

Set the default ksu PATH to match login

---

src/kadmin/dbutil/kdb5_util.c

kdb5_util could issue an unexplained error if a command argument
matched a command name, such as when trying to load a dump file named
"dump".  It could also mysteriously work if the command name and its
arguments were misordered, such as "kdb5_util kdb.dump load".
In the main option loop, build cmd_argv without special-casing command
names; then look up cmd_argv[0] after the loop.

Simplify kdb5_util global argv processing

---

src/util/support/errors.c

We have about four dozen NEGATIVE_RETURNS defects in Coverity scan, most of which are of the form "hey, I noticed that com_err codes can be negative, and you're passing one to k5_get_error() via krb5_get_error_message() or something, and that function can use strerror(), which can't accept a negative number".
This is aggravating because:
* As far as I can tell Coverity is wrong.  strerror() and strerror_r() have defined behavior for any integer, and will say "Unknown error -1" or similar on negative numbers.
* The relevant code in k5_get_error() only triggers if fptr is NULL, which we do not expect to happen in practice.  libkrb5 sets fptr to error_message() at library initialization time and back to NULL at finalization time.  libkrb5support has no public API, so k5_get_error() should …

Squashing Coverity NEGATIVE_RETURNS strerror defects

---

doc/admin/conf_files/kdc_conf.rst

The default severity was removed by commit
6ce8fd4cfa2e9b1e92debd204a5b2ddf053cca55 (ticket 8630) but the example
still talks about it; remove that text.  Add a note about the default
being syslog if nothing else is specified, and a note on how to
disable logging.

Improve logging documentation

---

src/include/k5-int.h
src/kdc/fast_util.c
src/kdc/kdc_preauth.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/lib/krb5/krb/Makefile.in
src/lib/krb5/krb/fast.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/padata.c
src/lib/krb5/libkrb5.exports

After recent discussion in PR #912 I came up with this.  The pattern here is that we only claim memory on success, but null out the caller's pointer when we do so, allowing the caller to free unconditionally.
I am particularly fond of k5_add_pa_data_from_data(), as it simplifies many call sites where we just constructed an ASN.1 encoding.  I wish its name weren't so long, as every call also includes a relatively long constant name for the pa-data type and that eats up 80 columns very quickly.  But it's hard to come up with a shorter name which is even vaguely evocative of what it does.
k5_free_pa_data_element() is a slightly awkward name when compared to k5_alloc_pa_data().  My intent is to avoid confusion with krb5_free_pa_data() which frees a whole list.
I didn't touch preauth2.c, even …

libkrb5 padata helper functions

---

src/kprop/deps
src/kprop/kproplog.c

[Noticed while reviewing PR #912]
Remove the local flags table in kproplog.c and instead use
krb5_flags_to_strings(), as was done for kadmin.c in commit
971fae8285427b27dfd8c9a535a18eb588ee0689.

Use krb5_flags_to_strings() in kproplog

---

src/lib/krb5/keytab/kt_file.c

When acquiring credentials using a keytab, krb5 examines each entry in
the keytab to check for a better match.  Relax the check on enctypes so
that the presence of removed enctypes (like DES) in the keytab doesn't
cause failure in kinit.

Don't require all enctypes in a keytab to be valid

---

src/lib/gssapi/krb5/set_allowable_enctypes.c

Instead of erroring out when any invalid enctypes are present in the
caller's list, filter out the invalid ones and only error if no
enctype remains.
[See also:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932000
https://krbdev.mit.edu/rt/Ticket/Display.html?id=8819 ]

Filter enctypes in gss_set_allowable_enctypes()

---

doc/admin/conf_files/krb5_conf.rst
src/util/profile/Makefile.in
src/util/profile/final.expected
src/util/profile/final1.ini
src/util/profile/final2.ini
src/util/profile/final3.ini
src/util/profile/final4.ini
src/util/profile/final5.ini

The documentation for krb5.conf explaining how tags are marked as final
is incorrect.
http://mailman.mit.edu/pipermail/krbdev/2019-July/013131.html

Fix doc for krb5.conf file

---

src/appl/simple/server/sim_server.c
src/kadmin/testing/scripts/qualname.plin
src/tests/gssapi/t_ccselect.py
src/tests/resolve/Makefile.in
src/tests/resolve/resolve.c

In the utilities used by the dejagnu test suites, use
getaddrinfo()/getnameinfo() instead of
gethostbyname()/gethostbyaddr(), as the results can vary when the
local hostname appears in multiple lines in /etc/hosts.
In t_ccselect.py, don't cause an error if the canonicalized local
hostname is "localhost".  The tests will continue to run in this case,
as long as we don't try to create duplicate principals.
In sim_server.c, bind to the wildcard address instead of the resolved
local hostname, to resolve a mysterious problem observed in Travis
where the second of three sim_client send() operations fails with
ECONNREFUSED.

Fix test suite issues affecting Travis images

---

src/Makefile.in
src/util/cstyle-file.py
src/util/cstyle.py
src/util/krb5-check-copyright.py
src/util/krb5-mark-cstyle.py
src/util/testrealm.py

Commit e23d24beacb73581bbf4351250f3955e6fd44361 missed some Python
scripts, in part because of the "PYTHON = python" line in
src/Makefile.in from commit 7be2ef2b6c8c491781251a5023db48d7690f5fa8.
Remove that line and convert the remaining scripts.  Also fix the
check-pytests-no warning to mention Python 3 instead of Python 2.5.

Convert remaining Python scripts to Python 3

---

src/Makefile.in
src/configure.ac

In Python 3 releases before 3.2.4, the subprocess.Popen.communicate
method does not accept string inputs when universal_newlines=True is
set (see https://bugs.python.org/issue16903).
Also substitute the minimum Python version displayed by "make
check-pytests-no" from configure.ac to help keep it in sync with the
minimum version we check for.
[One of the buildbot workers runs Ubuntu 12.04, which maxes out at Python 3.2.3.  The alternatives to bumping the minimum version are unattractive, as Python 3.3+ doesn't accept bytes input to subprocess.Popen.communicate() when universal_newlines is set.  We could check the Python version, or we could stop using universal_newlines=True and explicitly encode inputs and decode outputs.  We'd have to do that in at least three places--twice in t_kdb.py …

Require Python 3.2.4 for test scripts

---

src/lib/krb5/os/Makefile.in
src/tests/softpkcs11/main.c

resolve_wrapper uses RTLD_DEEPBIND to load libresolv, triggering a
failure in the asan runtime.

Skip URI tests when using asan

---

src/tests/dejagnu/config/default.exp

[Very rarely I would see "make check" fail in tests/dejagnu with "FAIL: des3: kpasswd testprinc/instance anothertest", which would go away on another test run.  Today I tracked it down to kpasswd trying to use an expired ccache as FAST armor.  The ccache is ordinarily removed at the end of the dejagnu test suite (simply because standalone.exp does a kdestroy at line 254 and nothing gets tickets after that), so the failure would only happen if the dejagnu tests were interrupted or failed badly and then some hours elapsed before the next make check.]
The dejagnu test suite could fail due to a leftover tmpdir/tkt ccache
containing expired tickets.  Remove the ccache file along with the
keytab in delete_db.  (The file cpw_keytab, formerly written as
cpw_srvtab, is not used in the dejagnu …

Clean up default ccache in dejagnu test suite

---

src/kdc/policy.c

A value of 0 indicates that the plugin doesn't wish to modify lifetimes.
Make this the default, rather than requiring all plugins to set these
values themselves.

Initialize life/rlife in kdcpolicy interface

---

src/lib/krb5/ccache/cc_kcm.c

An inverted status check in get_kdc_offset() would cause querying the
offset time from the ccache to always fail (silently) on KCM.  Fix the
status check so that KCM can properly handle desync.

KCM: fix k5_input status check in get_kdc_offset()

---

src/util/profile/prof_parse.c

In parse_quoted_string(), only process an escape sequence if there is
a second character after the backlash, to avoid reading past the
terminating zero byte.  Reported by Lutz Justen.

Don't skip past zero byte in profile parsing

---

src/kdc/cammac.c
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/fast_util.c
src/kdc/kdc_authdata.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h

[One of the commits in PR #912 wants to provide the first local TGT key to the KDB sign_authdata method for PAC signing, adding a fourth consumer of this key to the existing three.  This commit extracts that key at a higher level so that we aren't doing it multiple times per request.]
Decrypt the first local TGT key in get_local_tgt() and save it in the
AS and TGS processing functions.  (As we now sort key data by
descending kvno, this is guaranteed to be the most recent key.)  Pass
this key to the authdata and FAST cookie functions to simplify cookie
encryption and authdata signing.  Decryption and verification
functions must still sometimes decrypt earlier keys to process tickets
predating the last local TGT key rollover.

Track first local TGT key in KDC code

---

src/include/kdb.h
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_authdata.c
src/kdc/kdc_util.h
src/lib/kdb/Makefile.in
src/lib/kdb/kdb5.c
src/plugins/kdb/test/kdb_test.c
src/tests/t_authdata.py

Amend the sign_authdata method signature to include a modifiable
auth_indicators array.  Bump the DAL major version and the libkdb5
soname.
[This overlaps with PR #912 which also adds a parameter to sign_authdata, but the merge should be straightforward.  I will likely want to add a test case by having the test KDB module do something to the auth indicators in its sign_authdata method before merging, but this should be enough to get feedback from Samba developers.]

Allow the KDB to see and modify auth indicators

---

src/lib/kdb/kdb_default.c

Key data is now sorted in descending kvno order (since commit
44ad57d8d38efc944f64536354435f5b721c0ee0) and key enctypes can be
compared with a simple equality test (since single-DES support was
removed in commit fb2dada5eb89c4cd4e39dedd6dbb7dbd5e94f8b8).  Use
these assumptions to simplify krb5_dbe_def_search_enctype().
The rewrite contains one probably-unnoticeable bugfix: if enctype,
salttype, and kvno are all given as -1 in a repeated search, yield all
key entries of permitted enctype, not just entries of the maximum
kvno.

Simplify krb5_dbe_def_search_enctype()

---

doc/appdev/gssapi.rst
doc/appdev/refs/api/index.rst
src/clients/kvno/kvno.c
src/include/k5-int.h
src/include/kdb.h
src/include/krb5/krb5.hin
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_authdata.c
src/kdc/kdc_preauth.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/init_sec_context.c
src/lib/gssapi/krb5/s4u_gss_glue.c
src/lib/kdb/kdb5.c
src/lib/kdb/libkdb5.exports
src/lib/krb5/asn.1/asn1_k_encode.c
src/lib/krb5/krb/gc_via_tkt.c
src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/pac.c
src/lib/krb5/krb/s4u_creds.c
src/lib/krb5/libkrb5.exports
src/lib/krb5_32.def
src/plugins/kdb/test/kdb_test.c
src/tests/gssapi/t_s4u.py

This is work-in-progress, following the discussion on krbdev:
http://mailman.mit.edu/pipermail/krbdev/2019-March/013083.html
I'm still not happy with the chase-referral commit, which is a cleaned-up version of the prove-of-concept code. I wanted to move more logic to s4u_creds.c, implement a chase-referral loop that calls krb5_get_cred_via_tkt_ext() in each iteration, and call this loop two or three time to get the job done. It also depends whether or not we want krb5_get_credentials() to work with RBCD or the caller code can be adapted. Anyway, for now I'll start working on the KDC side (and tests) to get a better picture.

Implement resource-based-constrained-delegation support

---

doc/conf.py

In commit 38a31852c3e58f6e2f6b3b035a87f817d1db5537, aes-sha1 enctypes
became the only defaults, but the documentation was not updated.

Update documentation for default keysalts

---

src/kdc/kdc_util.c

[It doesn't look like there's any existing way to send PKINIT enctypes in an AS or TGS request with the current code.  I tested manually by changing krb5int_parse_enctype_list() to add the enctype I wanted.
While testing this I noted that new enctypes will generate strings like "DEPRECATED:(5000)" in the KDC log, because krb5int_c_deprecated_enctype() returns true for unknown enctypes.  This requires some thought; an enctype we don't recognize could be either too old or too new to be on the list.  PKINIT enctypes are also marked as deprecated because they were never in the libk5crypto list, and it's unclear whether this is correct.]
Commit a649279727490687d54becad91fde8cf7429d951 introduced a KDC crash
bug due to transposed strlcpy() arguments.  Fix the argument order.
This bug does not …

Fix KDC crash when logging PKINIT enctypes

---

doc/admin/database.rst

Commit 969331732b62e73d1e073ff3ad87bf1774ee9fd1 (ticket 7369) removed
the code to return UPDATE_BUSY if the database was modified within the
last ten seconds, but did not remove the corresponding documentation
text.  Remove it now.

Remove some outdated iprop documentation

---

src/kdc/kdc_util.c

[This part is easy, but I may also want to change the behavior on PKINIT enctypes after discussion.]
Commit 8d8e68283b599e680f9fe45eff8af397e827bd6c logs both invalid and
deprecated enctypes as "DEPRECATED:".  An invalid enctype might be too
old or marginal to be supported (like single-DES) or too new to be
recognized.  For clarity, prefix invalid enctypes with "UNSUPPORTED:"
instead.

Log unknown enctypes as unsupported in KDC

---

src/tests/t_otp.py

[The good news is that pyrad is getting maintained.  The bad news is that a release on Saturday caused t_otp.py to start through an exception.  Here is a fix.]
pyrad 2.2 throws a KeyError exception in DecodePacket if any
attributes from the packet are not defined in the dictionary.  Add a
dictionary entry for Service-Type so this doesn't happen.

Fix t_otp.py for pyrad 2.2

---

doc/admin/host_config.rst

/etc/gss/mech lines begin with a name field, but this field was not
included in the format documentation.

Fix missing field in /etc/gss/mech documentation

---

src/lib/gssapi/mechglue/g_accept_sec_context.c

[Starting with release 1.14 we began filtering mechs like IAKERB out of the default credential, based on mechanism attributes.  As a bad side-effect, we can reject a mechanism which doesn't implement RFC 5587.
This is the most conservative fix, but it is possible that the problem should be fixed at a lower level.  It seems broken that RFC 5587 defines gss_inquire_attrs_for_mech() such that it may use GSS_C_NO_OID_SET for the empty attribute set, while gss_test_oid_set_member() does not accept that value.  (Heimdal's gss_test_oid_set_member() will actually crash on a null oid set; MIT's returns an error.)  There are contexts where GSS_C_NO_OID_SET is not equivalent to an empty OID set; for instance, in gss_acquire_cred() it asks for the default mechanism set.  Tagging @nicowilliams in case …

Accept GSS mechs which don't supply attributes

---

src/lib/gssapi/mechglue/g_initialize.c

[This leak is minor as it can only happen once per dynamically loaded GSS mech, but it happens in the common case (because loaded GSS mechs typically do not define gss_mech_initialize()) and trips asan or valgrind leak detection.]
When gssint_get_mechanism() loads a GSS mech, it must clear errinfo if
krb5int_open_plugin() or krb5int_get_plugin_func() returns an error.

Fix minor leak when loading GSS mechanisms

---

src/lib/gssapi/generic/gssapi_generic.c
src/lib/gssapi/mechglue/g_authorize_localname.c
src/lib/gssapi/mechglue/g_complete_auth_token.c
src/lib/gssapi/mechglue/g_del_name_attr.c
src/lib/gssapi/mechglue/g_export_name_comp.c
src/lib/gssapi/mechglue/g_get_name_attr.c
src/lib/gssapi/mechglue/g_initialize.c
src/lib/gssapi/mechglue/g_inq_context_oid.c
src/lib/gssapi/mechglue/g_inq_cred_oid.c
src/lib/gssapi/mechglue/g_inq_name.c
src/lib/gssapi/mechglue/g_map_name_to_any.c
src/lib/gssapi/mechglue/g_mechattr.c
src/lib/gssapi/mechglue/g_prf.c
src/lib/gssapi/mechglue/g_rel_name_mapping.c
src/lib/gssapi/mechglue/g_saslname.c
src/lib/gssapi/mechglue/g_set_context_option.c
src/lib/gssapi/mechglue/g_set_cred_option.c
src/lib/gssapi/mechglue/g_set_name_attr.c
src/lib/gssapi/mechglue/g_set_neg_mechs.c

The prevailing discpline of public GSS APIs is to set output
parameters to default values, then validate input parameters.  Some
more recent APIs did not do this consistently, leading to the
possibility of minor_status retaining its previous value or similar
issues.

Improve argument validation in some GSS APIs

---

src/lib/gssapi/generic/gssapi_alloc.h

gss_inquire_sec_context_by_oid(GSS_C_INQ_SSPI_SESSION_KEY) fails on
Windows because generic_gss_add_buffer_set_member() relies on the
ability to realloc() a null pointer.  Unlike realloc(), HeapReAlloc()
requires an input pointer that (from the MSDN documentation) "is
returned by an earlier call to the HeapAlloc or HeapReAlloc function".
So gssalloc_realloc() must test for null inputs and call HeapAlloc()
instead.
Reported by Eric Pauly.

Fix gssalloc_realloc() on Windows

---

src/util/support/plugins.c

[This seems like the least worst option to get the negoex tests to work on old-but-not-ancient versions of Linux distributions.]
When building against glibc 2.24 or earlier, suppress calls to
dlclose() to prevent the assertion failure "_dl_close: Assertion
`map->l_init_called' failed" at process exit.  We need this workaround
to enable automated tests that load GSSAPI modules.

Work around glibc bug 11941 (dlclose assertion)

---

src/lib/krb5/krb/get_in_tkt.c
src/tests/t_kdb.py

if we verified returned PA-REQ-ENC-PA-REP, per RFC 6806.
I'm working on a test, see also related work in samba:
https://gitlab.com/samba-team/samba/merge_requests/840

Allow names to be canonicalized in non-krbtgt AS reply

---

src/kdc/do_as_req.c
src/kdc/kdc_util.h

If you want to know how long an authication takes for auditing, we
should note the time earlier as looking up the principal is part of it.

kdc: Record the kdc_time and authtime earlier

---

src/lib/gssapi/spnego/spnego_mech.c

When the default cred is used, the SPNEGO initiator restricts the list
of negotiable mechanisms to those we can acquire a cred for, so that
we don't propose a mech we know can't work.  The acceptor should do
the same.

Restrict SPNEGO acceptor mechs by cred acquisition

---

src/lib/gssapi/mechglue/g_accept_sec_context.c
src/lib/gssapi/mechglue/g_init_sec_context.c
src/lib/gssapi/spnego/gssapiP_spnego.h
src/lib/gssapi/spnego/spnego_mech.c

When accepting, do not leak a name if the underlying mech reports a
src_name twice.  Record mech_type and delegated_cred_handle and report
them to the caller at the final SPNEGO step, not when the underlying
mech reports them.
When initiating or accepting, report ret_flags at every step, and
filter out PROT_READY as required by RFC 4178 section 3.1.  Report a
time_rec value at the final step even if we didn't call into the
underlying mech, using a call to gss_context_time() if necessary.
In the mechglue, initialize ret_flags and time_rec for both
gss_initialize_sec_context() and gss_accept_sec_context().

Fix SPNEGO output parameter bugs

---

doc/admin/conf_files/krb5_conf.rst
src/include/k5-int.h
src/lib/gssapi/krb5/init_sec_context.c
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/krb/t_copy_context.c
src/man/krb5.conf.man

If this flag is set to true, then GSSAPI credential delegation will be
disabled when the "ok-as-delegate" flag is not set in the service ticket.

Implement enforce_ok_as_delegate libdefaults boolean

---

src/lib/gssapi/spnego/spnego_mech.c

In init_ctx_call_init(), if gss_init_sec_context() fails while
producing the first SPNEGO initiator token, we remove the first
candidate mechanism from sc->mech_set and try again.  If
sc->ctx_handle is present after the error (more likely after commit
56f7b1bc95a2a3eeb420e069e7655fb181ade5cf), we must clear it before
falling back or it will cause subsequent attempts to fail.

Fix SPNEGO fallback context handling

---

src/include/k5-buf.h
src/lib/gssapi/mechglue/g_export_cred.c
src/lib/krb5/ccache/cc_file.c
src/lib/krb5/ccache/cc_kcm.c
src/plugins/kdb/lmdb/marshal.c
src/plugins/preauth/spake/spake_kdc.c
src/util/support/utf8_conv.c

This was prompted by the NegoEx code, but there are enough uses of k5_buf for integers to warrant the helpers already.
I left ccmarshal.c alone because its helpers have to conditionalize on the format version.

k5-buf.h integer helpers

---

src/lib/kadm5/srv/svr_principal.c

Commit f07bca9fc94a5cf2e3c0f58226c7973a4b86b7a9 made addprinc -randkey
use a single RPC request, but the server-side handling always creates
the random keys with kvno 1.  If a kvno is specified in the RPC
request, set the kvno of the key data after creating it.  Reported by
Andreas Ladanyi.

Fix kadmin addprinc -randkey -kvno

---

src/lib/gssapi/mechglue/g_accept_sec_context.c
src/lib/gssapi/mechglue/g_glue.c
src/lib/gssapi/mechglue/g_imp_sec_context.c
src/lib/gssapi/mechglue/g_init_sec_context.c
src/lib/gssapi/mechglue/g_set_context_option.c
src/lib/gssapi/mechglue/mglueP.h

The first commit is a bugfix extracted from Luke's NegoEx implementation.  gss_set_sec_context_option() is probably unused (particularly in the mode where you create a context with it) but I wanted the bugfix to be separate and backported.
The second commit factors out four instances of creating a union context (which will go up to six with NegoEx) into a helper function.

Factor out mechglue context creation

---

src/lib/gssapi/spnego/spnego_mech.c

[This is in the NegoEx PR, but is unrelated, so I'm extracting it for separate review.]
Exclude all negotiation mechanisms when getting the set of available
mechs, avoiding the need to make a copy and specifically exclude
SPNEGO.

Simplify SPNEGO get_available_mechs()

---

src/lib/gssapi/generic/Makefile.in
src/windows/installer/wix/files.wxi

Release 1.10 added gssapi_alloc.h, but only added it to "make install"
for Windows, not to the wix installer or to the regular install.

Install gssapi/gssapi_alloc.h properly

---

src/appl/gss-sample/gss-server.c
src/lib/gssapi/generic/gssapi_alloc.h
src/lib/gssapi/krb5/naming_exts.c
src/lib/gssapi/krb5/prf.c
src/lib/gssapi/mechglue/g_decapsulate_token.c
src/lib/gssapi/mechglue/g_encapsulate_token.c
src/lib/gssapi/mechglue/g_exp_sec_context.c
src/lib/gssapi/spnego/spnego_mech.c

[I did a DEBUG_GSSALLOC + asan pass over the negoex PR to look for gssalloc mistakes there.  I didn't find any, but I found a small pile of pre-existing mismatches that we had never caught before.]
The DEBUG_GSSALLOC version of gssalloc_realloc() must add the sentinel
size to the byte count.
The mechglue gss_decapsulate_token(), gss_encapsulate_token(), and
gss_export_sec_context() must use gssalloc_malloc() to allocate
output buffers.
The krb5 mech's gss_export_name_composite() and gss_pseudo_random()
implementations must use gssalloc_malloc() to allocate output buffers.
SPNEGO's gss_display_status() implementation must use gssalloc for the
output buffer.
The sample GSS server must use gss_release_buffer() to free the result
of gss_export_sec_context().

Various gssalloc fixes

---

doc/admin/conf_files/krb5_conf.rst
src/include/k5-int.h
src/lib/krb5/os/dnsglue.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sn2princ.c
src/tests/gssapi/t_ccselect.py
src/tests/t_sn2princ.py
src/util/k5test.py

[I promised to do this many months ago and got sidetracked.  It should make the `dns_canonicalize_hostname = fallback` configuration significantly more functional, so I pushed to do this before branching for 1.18.  I haven't tested this yet on Windows or MacOS but will make an effort to do so.]
When DNS forward canonicalization is turned off or fails, qualify
single-component hostnames with the first DNS search domain.  Add the
qualify_shortname relation to override this suffix.
For one of the tests we need to disable qualification, which is
accomplished with an empty value.  Adjust k5test.py to correctly emit
empty values when writing profiles.

Qualify short hostnames when not using DNS

---

doc/admin/admin_commands/kadmin_local.rst
doc/admin/database.rst
doc/admin/install_kdc.rst
src/kadmin/cli/kadmin.c
src/man/kadmin.man
src/po/de.po
src/po/mit-krb5.pot

Not having policy deined is a normal occurrence.  While it's a useful
message to log in case it's unexpected, the current form is
unnecessarily alarmist and would cause less concern without being
prefixed by "WARNING" or "NOTICE".
[I can see an argument against this change that it may break some scripts which check for this line.  If that's a greater concern, I'll withdraw this PR.]

Don't warn in kadmin when no principal policy is specified

---

src/include/kdb.h
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_preauth.c
src/kdc/kdc_util.c
src/lib/kadm5/srv/server_kdb.c
src/lib/kdb/kdb5.c
src/lib/kdb/kdb_default.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
src/plugins/kdb/test/kdb_test.c
src/tests/t_kdb.py

As discussed, i think it would be good to have this with the api change.

Do not assume KRB5_KDB_FLAG_CANONICALIZE for enterprise principals

---

src/lib/gssapi/spnego/negoex_ctx.c
src/lib/kadm5/kadm_rpc_xdr.c
src/lib/krb5/krb/ser_ctx.c
src/lib/rpc/auth_gssapi_misc.c
src/lib/rpc/authgss_prot.c

Two of these address Coverity defects (one real, one a false positive).  The third addresses warnings from clang under macOS.  (The macOS build is still not warning-clean because of deprecations warnings; macOS has decided that daemon() and the entire libldap API are deprecated.  We might be able to except deprecation warnings from -Werror.)
I still need to verify that the assert() squashes the false-positive defect by manually submitting a build to Coverity scan.  There's a regularly scheduled build in the queue right now so that will take a bit.

Three code hygiene fixes

---

src/lib/krb5/krb/authdata.c

[I looked into adding a test case, but it's difficult.  Since the CAMMAC service verifier uses the same key as the ticket is encrypted in, and the KDC will reject client-requested CAMMAC authdata, there is no obvious way to produce an invalid CAMMAC service verifier without code modification.  I did test the bug and the fix manually by temporarily modifying cammac_create() to zero out the service checksum.]
In extract_cammacs(), avoid a null dereference if the CAMMAC service
verifier is invalid or the CAMMAC is empty.

Fix handling of invalid CAMMAC service verifier

---

src/lib/kadm5/srv/svr_principal.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
src/tests/t_kdb.py

In only the LDAP backend, the change mask is used to determine what to
update.  As a result, password expiration was not set from policy when
running during addprinc, among other issues.  However, when the mask did
not contain KADM5_PRINCIPAL, pw_expiration would be applied regardless,
which meant that (for instance) changing the password would cause the
password application to be applied.
Remove this check, and fix the mask to contain KADM5_PW_EXPIRATION where
appropriate.  Add a regression test to the LDAP suite.

Fix LDAP policy enforcement of pw_expiration

---

src/lib/gssapi/mechglue/g_initialize.c

[Probably not the solution to https://krbdev.mit.edu/rt/Ticket/Display.html?id=8863 but uncovered while investigating.]
In the unlikely event that one of the functions called by
gssint_mechglue_init() returns an error, return that error to the
caller rather than continuing on and discarding the error status.
Returning success when some of the operations failed could fool the
library finalizer into thinking that initialization completed.
Reported by Spencer Malone.

Fix error handling in gssint_mechglue_init()

---

.gitignore
src/lib/krb5/krb/s4u_creds.c
src/tests/Makefile.in
src/tests/adata.c
src/tests/s4u2self.c
src/tests/t_authdata.py

I think this should suffice for now, skipping the realm identification part as I hope it would be simpler later. I'll try to add a test though. (see #983).

s4u2proxy: only send client authdata in initial request

---

src/plugins/kdb/test/kdb_test.c

Commit 94f7c9705879500b1dc8dda8592490efce05688f simplified the
generation of authdata elements, but left behind some unnecessary
conditionalization when assembling the elements into a list, causing a
Coverity defect.  Further simplify the code.

Further simplify test KDB module authdata code

---

src/lib/krb5/krb/rd_req_dec.c
src/tests/gcred.c
src/tests/t_crossrealm.py
src/util/k5test.py

[This came up during past discussion of PR #1005 on mailing lists.  It does not solve the problem, as Windows doesn't set the transited-policy-checked flag, but it seems like a good change and I'd like to get it into 1.18.]
For consistency with Heimdal and simplicity of server configuration,
do not check the transited field in krb5_rd_req() if the
transited-policy-checked flag is set in the ticket.
Add a cross-realm test using the gcred and rdreq harnesses to test
server transited processing.  Also fix the KDC capaths case so that
the client actually doesn't know the path to the server realm.  In
k5test.py, adjust _cfg_merge() to remove keys mapped to None in the
second dictionary (instead of mapping them to None in the result), so
that deleting whole sections works.  Remove the …

Honor transited-policy-checked flag in servers

---

src/include/k5-int.h
src/lib/krb5/krb/copy_ctx.c
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/krb/ser_ctx.c
src/lib/krb5/krb/t_copy_context.c
src/lib/krb5/krb/t_etypes.c
src/lib/krb5/libkrb5.exports
src/tests/etinfo.c
src/tests/t_etype_info.py

(Follow-up to https://github.com/krb5/krb5/pull/1025#issuecomment-576038319 )
krb5_set_default_in_tkt_ktypes() and krb5_set_default_tgs_ktypes() are
not publicly exposed, so remove them.  Also remove the now-unused
in_tkt_etypes field from krb5_context.  Update test suite consumers, and
remove etype info tests that no longer test anything.

Remove unexposed mutators for session enctype lists

---

src/kdc/kdc_authdata.c
src/plugins/kdb/test/kdb_test.c
src/tests/adata.c

See: http://mailman.mit.edu/pipermail/krbdev/2020-January/013200.html
This still needs some research, testing and tests, but that's basically the idea.
It is cleat that the PAC needs to proceed other ad-elements (at least unknown to Windows), while for other ad-elements, as far as i can tell the order doesn't matter.
With this patch:
```code
PYTHONPATH=../util VALGRIND="" python3 ./t_authdata.py -v
...
*** [130] Executing: ./adata -p user@B service/rb.b -2 cross_s4u_proxy_ad
?128: 0500000000000000010000000100000058000000000000000B0000001B00000060000000000000000A000000120000008000000000000000060000001000000098000000000000000700000010000000A8000000000000000000000000000000736572766963652F72622E623A696D706572736F6E61746F724041000000000000BCF73213D9D501080075007300650072000000000000000F000000F1 …
```

Allow KDB authdata to be the first ad-elements

---

src/kdc/kdc_authdata.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h

Remove the unused concat_authorization_data().  Split merge_authdata()
into two helpers, one to destructively merge without filtering and one
to merge a copy with filtering.  Remove context parameters where they
aren't needed (taking advantage of knowledge that some libkrb5
functions don't use their context parameters).
[It turns out that all of the existing calls to merge_authdata() either want to copy and filter, or destructively merge without filtering.  I'm taking advantage of that to simplify the helper function contracts.]

Refactor KDC authdata list management helpers

---

src/lib/crypto/openssl/hash_provider/hash_evp.c
src/lib/crypto/openssl/sha256.c

More recent versions of OpenSSL can fail for other reasons.  Indicate a
crypto-related error occurred rather than a memory error to aid
debugging.

Don't OpenSSL failures are due to lack of memory

---

src/kdc/do_as_req.c
src/plugins/kdb/test/kdb_test.c
src/tests/t_authdata.py

[I found this bug while looking into implementing http://mailman.mit.edu/pipermail/krbdev/2020-February/013208.html .]
Commit 7196c03f18f14695abeb5ae4923004469b172f0f (ticket 8823) gave the
KDB the ability to modify auth indicators, but it happens after the
asserted indicators are checked against the server principal
requirements.  In finish_process_as_req(), move the call to
check_indicators() after the call to handle_authdata() so that the
final indicator list is checked.
For the test case, add string attribute functionality to the test KDB
module, and fix a bug where test_get_principal() would return failure
if a principal has no keys.  Also add a test case for AS-REQ
enforcement of normally asserted auth indicators.

Fix AS-REQ checking of KDB-modified indicators

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
src/tests/t_kdb.py

In update_ldap_mod_auth_ind(), if there is no string attribute value
for require_auth, check for krbPrincipalAuthInd attributes that might
need to be removed.  (This will only work if the entry is loaded and
then modified, but that is the normal case for an existing entry.)
Move the update_ldap_mod_auth_ind() call inside the tl-data
conditional (which should perhaps be a check for KADM5_TL_DATA in the
mask instead).  A modification which did not intend to update tl-data
should not remove the krbPrincipalAuthInd attributes.
Change get_int_from_tl_data() to to zero its output so that it can't
leave a garbage value behind if it returns 0 (as it does if no
KDB_TL_USER_INFO tl-data is present).
Based on a patch by Glenn Machin.
ticket: 8877
tags: pullup
target_version: 1.18-next

Allow deletion of require_auth with LDAP KDB

---

src/util/support/plugins.c

#992 - Commit bf5953c549a6d279977df69ffe89b2ba51460eaf introduced  __GLIBC_PREREQ which causes compilation against musl libc to fail.

Fix to musl libc issue introduced by bf5953c

---

src/lib/gssapi/krb5/acquire_cred.c
src/tests/gssapi/t_client_keytab.py

Fixes an issue where client keytabs would be ignored if expired
credentials were present in the ccache.
ticket: 7976

Attempt to refresh credentials in the ccache when expired

---

src/tests/t_otp.py

t_otp.py occasionally fails during the #8708 regression test, reading
a true answer instead of the expected false answer during the first
verify() call.  Most likely the daemons are writing their answers to
the shared queue out of order.  Use a separate queue for the second
daemon to ensure correct correlation of results.

Use two queues for concurrent t_otp.py daemons

---

src/lib/krb5/os/dnsglue.c

Fix the dnsglue.c PRIMARY_DOMAIN macro not to call strdup() with a
null pointer if no DNS search path is configured.

Fix null dereference qualifying short hostnames

---

.github/workflows/build.yml

[Enabled by the resolution of https://github.com/actions/virtual-environments/issues/123 ]
The Github Actions runners for Windows now place Strawberry Perl
earlier in the path than git-bash.

Remove Perl workaround in Github Actions config

---

src/Makefile.in

Add a top-level Makefile.in target to update checked-in generated
files, to simplify release engineering and repository maintenance.

Add "make regen"

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/tests/t_pkinit.py

In pkinit_client_prep_questions(), only act if the input padata type
is KRB5_PADATA_PK_AS_REQ.  Otherwise we will ask questions again when
the KDC issues a ticket.
Commit 7621d2f9a87214327ca3b2594e34dc7cea84596b (ticket 8242)
unintentionally changed the behavior of pkinit_load_fs_cert_and_key(),
causing pkinit_client_prep_questions() to do nothing on its first
call.  Restore the original behavior of returning 0 when prompting is
deferred.
Modify the existing "FILE identity, password on key (responder)"
PKINIT test to check that the responder is only invoked once.

Eliminate redundant PKINIT responder invocation

---

src/plugins/preauth/spake/edwards25519.c
src/plugins/preauth/spake/edwards25519_fiat.h

Use the int128_t and uint128_t types defined by edwards25519.c, rather
than [un]signed __int128 which does not compile with gcc 4.4.
Reported by Norm Green.

Make fiat 128-bit typedefs work with older gcc

---

src/lib/gssapi/krb5/import_name.c
src/tests/gssapi/t_gssapi.py

[As discussed in the krbdev thread, we may also want to make changes to krb5_sname_to_principal().  But this part is pretty clearly an improvement.]
The intended way to specify only a service in a GSS host-based name is
to omit the "@" separator.  Some applications include the separator
but no hostname, and this happened to yield wildcard hostname behavior
prior to commit 996353767fe8afa7f67a3b5b465e4d70e18bad7c when
shortname qualification was added.  To restore this behavior, check in
parse_hostbased() that at least one character is present after the "@"
separator before copying the hostname.  Add a test case to t_gssapi.py.

Correctly import "service@" GSS host-based name

---

src/include/krb5/krb5.hin
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/gic_pwd.c
src/lib/krb5/krb/t_expire_warn.c
src/lib/krb5/krb/t_expire_warn.py

Currently warn_pw_expiry() is called from krb5_get_init_creds_password()
and as a result only if this call is used the expiration callback is
called.
By moving the warn_pw_expiry() to krb5_init_creds_get_creds() other
way of requesting the initial credentials, e.g. the step-by-step
approach with krb5_init_creds_context, can benefit from the expiration
callback, too.

Call warn_pw_expiry() from krb5_init_creds_get_creds()

---

src/lib/krb5/os/trace.c

[Noticed while investigating http://mailman.mit.edu/pipermail/kerberos/2020-April/022447.html , although it seems unrelated to the problem described in the message.]
Always use six digits with leading 0s to format the microseconds in
trace log timestamps; otherwise a small value appears as too large of
a fraction of a second.

Correct formatting of trace log microseconds

---

src/lib/gssapi/spnego/gssapiP_spnego.h
src/lib/gssapi/spnego/spnego_mech.c

This is an easy change, and fixes part of the problem of https://krbdev.mit.edu/rt/Ticket/Display.html?id=8782 .
The other half of that problem is that a caller might supply a mech argument as a workaround, probably the actual_mech returned by gss_accept_sec_context().  In that case, the mechglue will try to reinterpret the SPNEGO name as the underlying mech, which seems to work okay with krb5 but not so much with EAP.
I had intended to extend the gss_accept_sec_context() contract for mechanisms that return an alternate actual_mech to apply to src_name, but I ran into complications.

Pass gss_localname() through SPNEGO

---

src/lib/gssapi/spnego/spnego_mech.c

Commit 24b844714dea3e47b17511746b5df5b6ddf13d43 (ticket 8845) added
releases of sc->internal_name and sc->deleg_cred before calling the
underlying mech's gss_accept_sec_context(), to avoid a potential leak
if the mech reports a value multiple times.  Commit
c2ca2f26eaf817a6a7ed42257c380437ab802bd9 (ticket 8851) added a branch
which calls negoex_accept() instead of calling directly into the
underlying mech.  If negoex_accept() doesn't call into the mech on the
last acceptor leg, the src_name and deleg_cred values from the final
mech call are lost.
Move the releases to the non-NegoEx branch.  negoex_accept() already
does its own releases when it calls into the mech.
Reported by Luke Howard.

Fix overzealous SPNEGO src_name/deleg_cred release

---

src/lib/gssapi/krb5/iakerb.c

[This came up when I looked into the gss_localname() issue.  IAKERB appearing to the mechglue as a negotiation mech creates a problem for extending the mechglue gss_accept_sec_context() SPI contract to apply to src_name.]
In the IAKERB gss_init_sec_context() and gss_accept_sec_context(),
always report the IAKERB mech, as IAKERB is not a negotiation
mechanism.

Stop reporting krb5 mech from IAKERB

---

src/kdc/do_tgs_req.c

[Prompted by http://mailman.mit.edu/pipermail/krbdev/2020-May/013261.html ]
As there was no initial ticket exchange from the client for an
S4U2Self request, the auth indicator check is inapplicable (and would
always fail if any auth indicators are required).

Omit KDC indicator check for S4U2Self requests

---

src/include/krb5/krb5.hin
src/lib/krb5/krb/parse.c

[I discovered this flag in Heimdal while investigating a possible mitigation for https://krbdev.mit.edu/rt/Ticket/Display.html?id=8903 .  Implementing it seems like a good idea regardless of what we do about that issue.]
Implement KRB5_PRINCIPAL_PARSE_NO_DEF_REALM from Heimdal.  This flag
for krb5_parse_name_flags() suppresses the addition of the default
realm, but allows and preserves the realm if one is specified in the
string.

Add KRB5_PRINCIPAL_PARSE_NO_DEF_REALM flag

---

src/lib/krb5/libkrb5.exports
src/lib/krb5/rcache/rc_base.c

[Prompted by https://github.com/alicevision/meshroom/issues/850#issuecomment-612966660 ]
Commit dcb853ac32779b173f39e19c0f24b0087de85771 removed some replay
cache functions that haven't been considered part of the libkrb5 API.
Some of these functions were used in OpenSSL (despite the lack of
prototypes) prior to the OpenSSL 1.1 release.  Run-time linker errors
can occur if an OpenSSL 1.0.x (or earlier) libssl is used with a 1.18
libkrb5, even though the Kerberos code would likely never be used.
Add stubs for the four functions historically used in OpenSSL.
ticket: 8905 (new)
tags: pullup
target_version: 1.18-next

Add stubs for some removed replay cache functions

---

src/kdc/kdc_util.c

Commit 570967e11bd5ea60a82fc8157ad7d07602402ebb took a shortcut in
get_local_tgt() by using the first key data entry in the TGT principal
entry.  This is usually correct, but if the first key data entry has
an invalid enctype (such as a single-DES enctype), we can select a key
we can't use.  Call krb5_dbe_find_enctype() instead.  Reported by
Leonard Peirce.

Prevent use of invalid local TGT key

---

src/kdc/cammac.c
src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/fast_util.c
src/kdc/kdc_preauth.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h

Add a simple static inline function current_kvno() to safely fetch the
current kvno of a principal entry, and use it where we currently write
entry->key_data[0].key_data_kvno.
Add a function get_first_current_key() to find and decrypt the first
valid current key from an entry.  Use it in get_local_tgt() and when
selecting a ticket encryption key during AS and TGS processing.
Add a local_tgt_key field to krb5_kdcpreauth_rock_st and use it in
add_freshness_token() so we don't have to decrypt it again.

Add KDC helpers for current key and kvno

---

src/lib/gssapi/spnego/spnego_mech.c

[I'll issue a patch release for this soon.  The bug was my fault, not Luke's, since it happened when I redid the SPNEGO integration.]
Commit c2ca2f26eaf817a6a7ed42257c380437ab802bd9 (ticket 8851)
accidentally changed SPNEGO's acceptor code to filter mechanisms by
the obtainability of initiator credentials rather than acceptor
credentials, when the default acceptor credential is used.
ticket: 8908 (new)
tags: pullup
target_version: 1.18-next

Fix SPNEGO acceptor mech filtering

---

src/lib/gssapi/krb5/acquire_cred.c
src/lib/gssapi/krb5/store_cred.c
src/tests/gssapi/t_add_cred.c

Earlier versions of the GSS-API spec (RFCs 1508 and 2078) do not list
GSS_S_NO_CRED as a valid error code for gss_acquire_cred.  As a
result, the OpenVision developers of the GSSAPI krb5 mech created
GSS_S_CRED_UNAVAIL as an alias for GSS_S_FAILURE and returned it when
no valid credentials could be obtained.  RFC 2743 lists GSS_S_NO_CRED
as the proper return code when matching credentials cannot be
accessed.  Change the krb5 gss_acquire_cred() implementation to return
GSS_S_NO_CRED where it currently returns GSS_S_CRED_UNAVAIL.
Also stop using GSS_S_CRED_UNAVAIL in the krb5 gss_store_cred(), but
change it to explicitly use GSS_S_FAILURE instead.  RFC 5588 specifies
GSS_S_NO_CRED as indicating a problem with input_cred_handle, not the
receiving store, so GSS_S_NO_CRED would be …

Return GSS_S_NO_CRED from krb5 gss_acquire_cred

---

src/lib/crypto/builtin/aes/Makefile.in

From https://krbdev.mit.edu/rt/Ticket/Display.html?id=8910 .
I created the --enable-static --disable-shared build option primarily in order to use gcov, which didn't support shared libraries at the time.  (It does now, although last I checked, it couldn't handle concurrent execution properly, so it gives some false negatives for coverage when you run the test suite.)  It does some pretty hackish things to make some-but-not-all plugins work, so I'm always nervous when people write in about trying to use it.  That aside, this is a trivial fix and it doesn't hurt anything.

Add static object build rules for AESNI sources

---

src/kadmin/dbutil/dump.c
src/tests/t_kdb.py

When loading a principal entry in process_k5beta7_princ(), set the
KADM5_PW_EXPIRATION mask bit so that the password expiration time is
set on the principal entry.  Add a regression test.
Reported (with fix) by Glenn Machin.

Set pw_expiration during LDAP load

---

src/lib/gssapi/spnego/negoex_util.c

Fix missing return code initialization in negoex_parse_token()

---

src/aclocal.m4

Teach the configure script to look for an ar tool prefixed with the
target triple (i.e., `<target>-ar`) when cross compiling. This matches
the behavior for tools that have built-in autoconf macros, like ranlib.
(For some reason there is no AC_PROG_AR macro.)
Also, remove the AC_PROG_ARCHIVE and AC_PROG_ARCHIVE_ADD macros, which
have been dead code since 780b34cd.
With this change, cross compiling libkrb5 works a bit better out of the
box.

Try to find <target>-ar when cross compiling

---

src/lib/kadm5/srv/svr_principal.c
src/tests/t_kadmin_acl.py

In libkadm5srv, do not allow deletion of the master key principal, as
it is very difficult to recover a KDB after doing so.

Prevent deletion of K/M

---

doc/user/user_commands/kvno.rst
src/clients/kvno/Makefile.in
src/clients/kvno/kvno.c
src/clients/kvno/t_kvno.py
src/man/kvno.man

Add the flags --cached-only and --no-store, which pass the
corresponding options to krb5_get_credentials().  Add the option
--out-cache to write the retrieved credentials to a specified output
cache.
Add a Python test script for kvno command-line options, including
tests for the new options.

Add three kvno options from Heimdal kgetcred

---

src/kdc/kdc_util.c

The KDC's decision to send a PA_S4U_X509_USER entry in encrypted has
no connection to the client USE_REPLY_KEY_USAGE flag.  Only
conditionalize on the enctype.

Fix KDC choice to send encrypted S4U_X509_USER

---

src/include/k5-trace.h
src/lib/krb5/krb/plugin.c

Add trace messages when dlopen() or dlsym() fails when loading a
plugin module.

Trace plugin module loading errors

---

src/kadmin/server/misc.c
src/kadmin/server/ovsec_kadmd.c
src/kadmin/server/schpw.c
src/kdc/main.c
src/lib/kadm5/srv/server_kdb.c

In krb5kdc and kadmind, reinitialize the DB state after daemonizing,
to prevent using an LMDB environment in a different process than it
was created.  Otherwise the daemon's reader table slot appears to be
stale and can be claimed by another process.
In kadmind, this change means that global_server_handle changes value
after the loop setup.  Add an extra level of pointer indirection so
that the handle passed to the loop remains valid.
kdb_init_hist() is now called twice by kadmind.  Change it to avoid
leaking hist_princ on the second invocation.

Avoid using LMDB environments across forks

---

src/lib/krb5/keytab/kt_file.c
src/tests/t_keytab.py

[See https://krbdev.mit.edu/rt/Ticket/Display.html?id=8914 ]
When considering or bypassing an empty record in a keytab file, check
for a lenth of INT32_MIN.  Otherwise we could perform a backwards
seek, as the inverse of INT32_MIN is still negative.

Avoid backward seeks when reading keytab files

---

src/lib/gssapi/krb5/util_crypt.c

[Long discussion at https://github.com/heimdal/heimdal/issues/739 ]
Windows Remote Management, when used with an RC4 session key, appears
to generate GSS wrap tokens with no padding instead of the expected
one byte (RFC 4757 section 7.3).  These tokens cannot be decoded with
gss_unwrap() or a STREAM buffer (even with Microsoft SSPI), but SSPI
allows them to be decoded using explicit IOVs with either a
zero-length padding buffer or no padding buffer.  Allow these cases to
work in kg_fixup_padding_iov().  (It is already possible to make this
work with HEADER | DATA | DATA, but only by
accident--kg_fixup_padding_iov() doesn't find a data buffer because
kg_locate_iov() only looks for singleton buffers, so it exits early.)

Allow gss_unwrap_iov() of unpadded RC4 tokens

---

src/lib/kadm5/str_conv.c

Fixes a problem where the presence of legacy/unrecognized keysalts in
supported_enctypes would prevent the kadmin programs from starting.

Ignore bad enctypes in krb5_string_to_keysalts()

---

src/kadmin/cli/getdate.y

[ https://krbdev.mit.edu/rt/Ticket/Display.html?id=8927 ]
Bison 3.5 adds a warning that %type should only be applied to
non-terminals.  Use %token for terminals in getdate.y.  Reported by
Norm Green.

Fix token and type declarations in getdate.y

---

src/aclocal.m4
src/configure.ac

Xcode 12 will change its clang to have
-Werror=implicit-function-declaration by default.  Fix three autoconf
tests which generate this warning due to missing include declarations.
Reported by Misty De Meo.

Fix three configure tests for Xcode 12

---

doc/admin/admin_commands/kadmin_local.rst
doc/admin/database.rst
src/kadmin/dbutil/kadm5_create.c
src/lib/kadm5/clnt/client_init.c
src/plugins/kdb/ldap/ldap_util/kdb5_ldap_realm.c
src/tests/dejagnu/krb-standalone/kadmin.exp
src/tests/t_iprop.py
src/tests/t_kadmin_acl.py

This PR contains one approach to addressing KDB creation when dns_canonicalize_hostname isn't true.  The first commit changes the kadmin client preference order to kadmin/admin first, and the second stops creating kadmin/hostname and kiprop/hostname.  I prefer this approach because it's technically simple compared to the other options.

Stop creating hostbased principals in new KDBs

---

src/include/k5-trace.h
src/kprop/kprop_util.c
src/lib/gssapi/krb5/init_sec_context.c
src/lib/krb5/ccache/cc_retr.c
src/lib/krb5/ccache/ccapi/stdcc_util.c
src/lib/krb5/ccache/ccfns.c
src/lib/krb5/krb/deps
src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/gic_keytab.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/rd_req_dec.c
src/lib/krb5/krb/s4u_creds.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sn2princ.c
src/tests/icred.c
src/tests/s4u2proxy.c
src/tests/t_sn2princ.py

This isn't complete, but I may have to switch focus next week so I'm putting up what I have so far.  The goal is to iron out a lot of edge cases, and make the server side of things less likely to break regardless of what the qualify_shortname default is.  The design is:
* A lightweight iterator over the one or two service principal candidates, so we can do fallback in more places without duplicating code.
* When dns_canonicalize_hostname=fallback, delay all processing of the sn2princ inputs until use, so that both canonicalizations can be dependent on the original sn2princ inputs and realm lookup can be done properly on each candidate.  (Heimdal does the same thing if the canonicalization rules are non-trivial.)
* Integrate fallback support into the stepwise TGS state machine, so that we …

Expand dns_canonicalize_hostname=fallback support

---

src/plugins/kdb/ldap/ldap_util/kdb5_ldap_realm.c

In kdb5_ldap_util, set lockdown_keys on the special principals when
creating an LDAP KDB, as we do in kdb5_util when creating a regular
KDB.

Set lockdown attribute when creating LDAP KDB

---

doc/user/user_commands/kvno.rst
src/clients/kvno/kvno.c
src/man/kvno.man

It was pointed out [downstream](https://bugzilla.redhat.com/show_bug.cgi?id=1869055) that the three places `kvno` options could be documented differ.  The full state of affairs is:
```
Unimplemented but documented somewhere: []
Undocumented but implemented: [] /* not that these would be a problem necessarily */
Missing from man page synopsis: ['--cached-only', '--no-store', '--out-cache', '-C', '-k', '-u']
Missing from man page long descriptions: ['-C', '-k', '-u']
Missing from xusage: ['-h', '-q']
Complete set: ['--cached-only', '--no-store', '--out-cache', '--u2u',
'-C', '-F', '-I', '-P', '-S', '-U',
'-c', '-e', '-h', '-k', '-q', '-u']
```
The first commit addresses the disparity, while including some missing dependency information and removing -h.
The second commit is a different …

Kvno docs internal consistency

---

src/include/CredentialsCache.h
src/include/CredentialsCache2.h
src/include/krb5/krb5.hin
src/lib/gssapi/generic/gssapi.hin
src/lib/krb5/krb/gic_opt.c

[The use of pragma pack in the ABI is an ancient MIT krb5 mistake that isn't easily fixed by either us or Apple.  We don't want to be incompatible with macOS on ARM or to give Apple reason to migrate it to ARM.]
Replace the TARGET_OS_MAC conditionals with the conditionals used in
Heimdal, so that we do not pack structures inconsistently with macOS
on ARM.  Suggested by Luke Howard.

Harmonize macOS pack declarations with Heimdal

---

src/windows/leashdll/krb5routines.c

Attempting to renew the MSLSA cache can commonly fail with
KRB5_CC_NOTFOUND due to LSA policy.  Do not display an error popup in
this case.  Also fix a logic error in the existing suppressions.

Suppress Leash error popup on MSLSA renew failure

---

src/lib/gssapi/spnego/spnego_mech.c

The first commit is the change requested by Richard Sharpe, to interoperate with a buggy NetApp DER encoder.  The supplied patch had some vulnerabilities, so I rewrote it.
The second commit fixes read length checking issues that I noticed while investigating.  (I don't think they have a material security impact.)

Two SPNEGO DER decoding changes

---

src/windows/leash/LeashView.cpp

CLeashView::RenewTicket() falls back to an ImportTicket or InitTicket
operation if ticket renewal fails.  A 2004 commit (from the old
pismere repository) added code to heuristically determine whether
Leash's cache was imported by comparing the MSLSA cache principal name
to ticketinfo.Krb5.principal.  Commit
9bc411e72fce5bed3ed00ae5b09f8c239309bae0 broke this code by removing
the call to initialize ticketinfo.Krb5 and by making
ticketinfo.Krb5.principal ephemeral.  The strcmp() call now crashes
the process with a null dereference.
Fix the crash by removing the heuristic detection of imported tickets,
using the current value of m_importedTickets (which should be correct
unless Leash was restarted after the tickets were obtained) to decide
whether to import or initialize tickets.

Fix Leash crash when ticket autorenewal fails

---

doc/admin/conf_files/kdc_conf.rst
doc/admin/database.rst
doc/admin/enctypes.rst
src/lib/krb5/krb/get_in_tkt.c

During initial authentication, if des3-cbc-sha1 is used for either the
reply key or session key, display a warning that it will be
deprecated.

Begin deprecating des3-cbc-sha1

---

.github/workflows/build.yml
.github/workflows/doc.yml

Add a second workflow to build documentation, with the HTML output as
a generated artifact.  Skip the doc workflow if no documentation files
were changed.  Skip the existing build workflow if no source files
were changed.

Add doc build to Github Actions config

---

doc/admin/realm_config.rst

The KDC has listened to TCP connections by default since commit
8d88e2ab00be126237569dc72827ced2ce6b7d04 (ticket 6731).  Update the
documentation for _kerberos._tcp accordingly.
Correct a formatting error introduced by commit
10eb93809b1af06e2b1147aee2e3e50058ba1bbd (ticket 8921).
For _kpasswd._udp, if the _kerberos-adm._tcp fallback is used, the
port number is changed to 464, not 749.
Add entries for _kerberos-master._tcp and _kpasswd._tcp.

Update SRV record documentation

---

doc/_templates/layout.html
doc/conf.py
doc/tools/doxybuilder_types.py
doc/tools/func_document.tmpl
src/include/krb5/krb5.hin

I found several issues with the doc build on Ubuntu 20.04.  I think all of them stem from the doxygen 1.8.17 package.  I am not sure what, if anything, I will merge to address these issues, but I want a place to document the investigation.
* Seemingly harmless whitespace issues in comments cause doxygen to emit `<para><linebreak/>\n </para>` within the `<detaileddescription>` element.  A bug in our custom doxygen-to-rst script emits `\n**\n` for these, causing a Sphinx warning about unterminated inline markup.  (I don't fully understand the bug in our scripts; there are lots of `<linebreak/>`s emitted by some of the OTP responder comments, with either new or old Doxygen, and they don't cause the same output.)  The PR currently contains whitespace changes to avoid the problem.
* Python …

Fix doc issues with newer Doxygen and Sphinx

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/tgs_policy.c

When validating AS or TGS requests, pass pointers to DB entry
structures, not the structures themselves.

Avoid passing DB entry structures in KDC

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/tgs_policy.c

Where possible, use the realm of the request server principal
(canonicalized via KDB lookup, if available) in preference to
tgs_server.  This change facilitates alias realm support and potential
future support for serving multiple realms from the same KDB.
S4U2Self local user testing currently uses the uncanonicalized request
realm after this change, which will require attention for alias realm
support.
FAST armor ticket checking is unaffected by this change (it still
compares against tgs_server).  This check poses no issue for realm
aliases, as both tgs_server and the armor ticket server should have
canonical realms, but it will require attention for multi-realm KDB
support.
Remove is_local_principal() as it is no longer used.  Add an
is_local_tgs_principal() helper and shorten …

Minimize usage of tgs_server in KDC

---

.gitignore
src/lib/gssapi/spnego/spnego_mech.c
src/tests/gssapi/Makefile.in
src/tests/gssapi/deps
src/tests/gssapi/reload.c

Commit d160bc733a3dbeb6d84f4e175234ff18738d9f66 (ticket 7045) added a
new thread key K5_KEY_GSS_SPNEGO_STATUS and registered it in SPNEGO
library initialization, but neglected to unregister it in
finalization.  As a result, loading, unloading, and reloading
libgssapi_krb5 could throw an assertion failure if libkrb5support
remained loaded.  Unregister the key in SPNEGO finalization and add a
test case.
Reported and investigated by Adam Dabrowski.

Unregister thread key in SPNEGO finalization

---

src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/tgs_policy.c

[This will require a merge with PR #1106 because of the moved lineage and S4U2Self checks, but it shouldn't be too difficult.]
[I would have liked to move the FX_ARMOR check from kdc_process_tgs_req(), but unfortunately RFC 6113 requires us to check the authenticator authdata as well as the ticket authdata, and it doesn't seem worth it to preserve the authenticator beyond kdc_process_tgs_req().]
Move the following validity checks into validate_tgs_request():
* the INVALID ticket flag check from kdc_process_tgs_req()
* the lineage check from process_tgs_req()
* all S4U2Self validity checks from kdc_process_s4u2self_req()
In process_tgs_req(), add an is_crossrealm boolean to for convenience.
There are some minor behavior changes:
* For invalid S4U2Self request options, the status string is …

Move more KDC checks to validate_tgs_request()

---

src/tests/t_kdcpolicy.py
src/tests/t_renew.py

[The more labor-intensive way to deal with this is to stop scraping klist output, such as by giving icred and gcred options to display the resulting credential lifetimes.  I might do that if I feel motivated, but this approach should be adequate if I don't.]

Avoid daylight savings time issues in tests

---

src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/s4u_creds.c

Active Directory canonicalizes the srealm field of TGS replies,
whether or not the client requests canonicalization.  Allow this for
regular TGS and S4U2Self referrals queries by comparing only the name
part of the service principal.  The S4U2Proxy code is already correct.

Allow KDC to canonicalize realm in TGS client

---

src/aclocal.m4

`autoconf-2.70` removed empty statements assignment
and exposed no-op statement problem:
```
$ autoreconf-2.70_beta3
./configure: line 2898: syntax error near unexpected token `else'
./configure: line 2898: `else'
```
The change uses `AS_IF` to avoid no-op. On autoconf-2.69 the
`./configure` diff is the following:
```diff
--- configure-2.69.pre  2020-11-06 08:20:50.000000000 +0000
+++ configure-2.69.post 2020-11-06 08:20:26.000000000 +0000
@@ -2853,3 +2853,3 @@
-if test -d "$srcdir/$ac_config_fragdir"; then
+if test -d "$srcdir/$ac_config_fragdir"; then :
ac_aux_dir=
```

src/aclocal.m4: add compatibility with upcoming autoconf-2.70

---

src/lib/krb5/asn.1/README.asn1
src/lib/krb5/asn.1/asn1_encode.c
src/lib/krb5/asn.1/asn1_encode.h
src/lib/krb5/asn.1/asn1_k_encode.c
src/lib/krb5/asn.1/krbasn1.h
src/lib/krb5/error_tables/asn1_err.et
src/tests/asn.1/krb5_decode_test.c

This removes support for decoding invalid ASN.1 DER data.  It also fixes
three non-exploitable integer overflows.  As a result of this change,
MIT Kerberos is no longer compatible with ancient broken Kerberos
implementations, but those have security vulnerabilities anyway.

Be strict about ASN.1 decoding

---

doc/appdev/gssapi.rst
src/lib/gssapi/krb5/acquire_cred.c
src/lib/gssapi/krb5/gssapiP_krb5.h
src/lib/gssapi/krb5/gssapi_krb5.c
src/tests/gssapi/Makefile.in
src/tests/gssapi/t_credstore.c
src/tests/gssapi/t_credstore.py
src/tests/gssapi/t_gssapi.py

This patch make the gss_acquire_cred_from_store() function also cover
the same functionality of gss_acquire_cred_with_password().
This makes the interface "complete" in the sense that it allows to cover
all possible acquire scenarios in a single API.
More importantly it makes it safer to acquire cred with password in
processes that need to do so in a thread safe manner. By specifying
unique ccache anmes in the cred store we avoid other non-thread safe
methods (or heavy synchronization) to use different ccaches which
are needed with the current gss_acquire_cred_with_password() interface.

Add password option to cred store

---

src/config/shlib.conf

Based on a patch by Nalin Dahyabhai.
[The full patch also hardcodes PIE support and a couple other things, which I think should no longer be necessary as the distro will pass it in build flags.  Full patch for completeness: [https://github.com/frozencemetery/krb5/commit/c06693e5a17daf0fd585e608e8bfd1eb3eef447c](https://github.com/frozencemetery/krb5/commit/c06693e5a17daf0fd585e608e8bfd1eb3eef447c) ]

Mark shared libraries executable during installation

---

doc/user/user_commands/kvno.rst
src/man/kvno.man

becd1ad6830b526d08ddaf5b2b6f213154c6446c attempted to unify the
synopsis, option descriptions, and xusage(), but missed one option.

Document -k option in kvno(1) synopsis

---

src/aclocal.m4
src/configure.ac
src/include/k5-gmt_mktime.h
src/include/k5-int.h
src/kadmin/cli/getdate.y
src/kadmin/cli/kadmin.h
src/kdc/main.c
src/lib/krb5/os/prompter.c
src/tests/dejagnu/t_inetd.c
src/tests/gss-threads/gss-misc.c
src/util/ss/list_rqs.c
src/util/ss/listen.c
src/util/support/gmt_mktime.c

In configure.ac and aclocal.m4, eliminate the use of old macros that
will generate warning from the forthcoming autoconf 2.70 release.
Specifically:
* Use AS_HELP_STRING instead of AC_HELP_STRING.
* Use AC_{COMPILE,LINK,RUN}_IFELSE and AC_LANG_{SOURCE,PROGRAM}
instead of AC_TRY_COMPILE and similar.
* Use m4_foreach_w instead of ac_foreach.
* Eliminate AC_PROG_LEX and yylineno checking, as we no longer use
lex.
* As recommended by autoconf, assume that signal handlers return void
as specified in C89.
* As recommmended by autoconf, assume <time.h> is present and that
<sys/time.h>, if present, can be included alongside it.
* Don't call AC_CHECK_FUNCS with a shell variable for the thread
safety checks.  Instead just assume (as is currently the case) that
all of the functions have been …

Reduce warnings from mainline autoconf

---

doc/formats/ccache_file_format.rst
src/clients/kinit/kinit.c
src/clients/kvno/kvno.c
src/include/k5-int.h
src/lib/gssapi/krb5/accept_sec_context.c
src/lib/krb5/ccache/ccfns.c
src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/libkrb5.exports
src/lib/krb5_32.def
src/tests/t_crossrealm.py
src/tests/t_pkinit.py

Currently anonymous caches don't work for referrals or cross-realm TGS requests; they only work as FAST armor or for services in the local realm (and marked as such in the server field).
This PR implements one possible solution, which is to add support for Heimdal's start_realm feature.  Heimdal sets start_realm automatically in the cache dispatch layer, which I do not like; I feel like logic implemented at the ccache dispatch layer generally comes back to bite us later.  Right now the PR is setting it for initial creds acquisition when an output cache is specified, as is done for both kinit -n and kadmin -n.  That's elegant but not totally satisfying; it won't work for "kvno --out-cache=... krbtgt/REALM@REALM" and it won't work if you delegate a different-realm TGT over ssh (as twosigma …

Improve anonymous cache behavior by adding start_realm support

---

src/lib/krb5/ccache/cc_memory.c
src/lib/krb5/ccache/t_cc.c

In the memory credential cache type, add new creds to the tail of the
list so that iteration does not reverse the order.

Preserve cred order in memory ccache type

---

src/tests/asn.1/krb5_decode_test.c

Commit d9443a58cd364349b7d764f4e997f3af7d979a87 introduced a leak in
krb5_decode_test.c with its new decode_fail macro.

Fix ASN.1 test memory leak

---

doc/admin/conf_files/krb5_conf.rst
doc/admin/princ_dns.rst
src/kadmin/testing/proto/krb5.conf.proto
src/lib/krb5/krb/init_ctx.c
src/tests/dejagnu/config/default.exp
src/util/k5test.py

Field testing of dns_canonicalize_hostname=fallback (ticket 8911)
revealed more disruptive edge cases than anticipated.  Many were fixed
by ticket 8930, but host-based GSS initiator names were recently
discovered to not work, and one other edge case could not be resolved
without a change to external code.
Restore the default to true for now.  Set the value to fallback in the
test suite, to continue testing the desired configuration and to avoid
restoring tests/resolve.
ticket: 8973 (new)
tags: pullup
target_version: 1.19

Revert dns_canonicalize_hostname default to true

---

src/include/k5-int.h
src/lib/gssapi/krb5/acquire_cred.c
src/lib/krb5/keytab/ktfns.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/rd_req_dec.c
src/lib/krb5/krb/sname_match.c
src/lib/krb5/libkrb5.exports
src/lib/krb5_32.def
src/tests/gssapi/t_gssapi.py

Commit 3fcc365a6f049730b3f47168f7112c03997c5c0b added fallback support
to krb5_rd_req(), but acquiring acceptor creds for a host-based name
could still fail within check_keytab() in the krb5 mech.
Add an internal libkrb5 API k5_kt_have_match() to check for a matching
keytab entry with canonicalization, and use it in check_keytab().  Add
a library-internal function k5_sname_wildcard_host() to share logic
between rd_req and k5_kt_have_match().
ticket: 8971 (new)

Implement fallback for GSS acceptor names

---

src/lib/krb5/ccache/cc_kcm.c

Before this commit, `ccselect_realm` would return the last error encountered by `krb5_cc_get_principal` ("No credential cache found", typically).
Moreover, krb5_cccol_cursor_free ret code is ignored.
With this commit, only the krb5_cccol_cursor_free return code is taken into account here.

ccselect: should not return cc_get_principal errors

---

src/kprop/kprop.c

Do not send an r-address in messages from kprop, so that kpropd will
not check it against the receiver address.  This change allows kprop
to work when a NAT changes the destination address.  (Commit
775e496aac2650343ec20826b1ba7f6306a12f3c allows kprop to work when a
NAT changes the source address.)  Reported by Jorj Bauer.

Allow kprop over more types of NATs

---

doc/appdev/refs/api/index.rst
src/include/krb5/krb5.hin
src/lib/krb5/ccache/ccmarshal.c
src/lib/krb5/ccache/t_marshal.c
src/lib/krb5/libkrb5.exports
src/lib/krb5_32.def

In KCM, the responder will receive a serialized krb5_creds object.
Should it wish to perform any operations on this object, it needs to
deserialize and reserialize it.

Expose krb5 functions for serialization of credentials

---

doc/admin/conf_files/krb5_conf.rst

The [domain_realm] section provides a mapping from hostnames to realm
names, but the individual mappings apply to domains (including
subdomains) or subdomains, not to hostnames.  Reported by Ulf Bremer.

Clarify domain_realm documentation

---

src/include/k5-int.h
src/include/k5-trace.h
src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/acquire_cred.c
src/lib/gssapi/krb5/gssapiP_krb5.h
src/lib/gssapi/krb5/rel_cred.c
src/lib/krb5/ccache/cccursor.c
src/lib/krb5/libkrb5.exports
src/lib/krb5/os/sn2princ.c
src/lib/krb5_32.def
src/tests/gssapi/t_client_keytab.py
src/tests/gssapi/t_credstore.py
src/tests/gssapi/t_gssapi.py
src/util/k5test.py

Having tried a couple of approaches to this problem, I'm putting this up to keep a record of my design notes.
Hostbased initiator names are not currently supported very well; even without dns_canonicalize_hostname=fallback, they fail if there is no [domain_realm] entry supplying a realm name.  But apparently FreeIPA uses them, and there is no conceptual reason why they shouldn't work on a best-effort basis.
gic_keytab does not support wildcarding like krb5_rd_req() does.  At this time I think that's inherent to the nature of the initiator: we need to pick a concrete principal to authenticate as, and there might be multiple matches for a wildcard in the keytab or cache collection.  By contrast, the acceptor has the ticket encryption key to use as an authority.  For this reason, I think it …

Hostbased initiator name support

---

doc/admin/conf_files/krb5_conf.rst
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_identity.c
src/tests/t_pkinit.py

This patch permits the use of multiple pkinit_identities lines in
krb5.conf.  This patch has two components:
Move the call to crypto_load_certs() in pkinit_identity_initialize()
inside of the same loop as process_option_identity().  This will
attempt to load a certificate from each pkinit_identities line in
the configuration, and if the certificate load fails to move to
the next line.
In pkinit_get_certs_pkcs11(), if pkinit_open_session() fails (for
example, if the specified library does not exist) then return an error.
Previously if defer_id_prompts was set an error was NOT returned.
This makes pkinit_get_certs_pkcs11() behave like all other certificate
loading functions called by crypto_load_certs(), and is required if you
want to be able to specify multiple PKCS#11 libraries on …

Allow multiple pkinit_identities lines

---

src/include/krb5/krb5.hin
src/lib/krb5/krb/Makefile.in
src/lib/krb5/krb/bld_pr_ext.c
src/lib/krb5/krb/bld_princ.c
src/lib/krb5/krb/deps
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/krb/parse.c
src/lib/krb5/krb/t_kerb.c
src/lib/krb5/krb/t_ref_kerb.out
src/lib/krb5/krb/tgtname.c
src/plugins/preauth/pkinit/pkinit_kdf_test.c

Although name-type is only a hint, various documents specify
particular values for some use cases.  In particular:
https://tools.ietf.org/html/rfc4120#section-7.3
The principal identifier of the ticket-granting service shall be
composed of three parts: the realm of the KDC issuing the TGS ticket,
and a two-part name of type NT-SRV-INST, with the first part "krbtgt"
and the second part the name of the realm that will accept the TGT.
https://tools.ietf.org/html/rfc6111#section-3.1
A new name type KRB_NT_WELLKNOWN is defined for well-known principal
names.  The Kerberos principal name is defined in Section 6.2 of
[RFC4120].
KRB_NT_WELLKNOWN                  11
A well-known principal name MUST have at least two or more
KerberosString components, and the first component MUST be the string …

krb5_parse_name: improve name-type heuristics

---

src/lib/krb5/krb/init_ctx.c
src/lib/krb5/libkrb5.exports

Samba only uses the correct name (krb5_set_default_tgs_enctypes) if it
cannot find the old one in the library.

Restore krb5_set_default_tgs_ktypes()

---

src/clients/kinit/kinit.c
src/clients/kvno/kvno.c

Stop using macros for the newline and tab dividers between lines of
usage messages in kinit and kvno, so that gettext can extract the full
string.

Fix gettext extraction of usage messages

---

src/windows/leash/KrbListTickets.cpp

In KrbListTickets.cpp, change etype_string() to write its output to a
caller-supplied buffer, so that the session key enctype name and
ticket enctype name don't occupy the same static buffer.  Reported by
Oliver Freyermuth.

Fix enctype display in Leash

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_identity.c

As discussed on krbdev, this allows multiple pkinit_anchor and pkinit_pool lines in krb5.conf.
To expand on this a bit; it is true that the existing code allows multiple anchor/pool lines.  But if any of the entries fail to process (e.g., file not found), then an error is returned from pkinit_identity_prompt() and pkinit ends up failing.
We've found during our PKINIT deployment that it was useful to list multiple locations in pkinit_anchors and pkinit_pool because certificate locations can vary across systems. This change weakens the error checking for the pkinit_anchors and pkinit_pool lines; if those configuration entries are specified, only one working entry is required.

Allow multiple pkinit_anchor and pkinit_pool lines

---

doc/tools/doxybuilder_types.py
src/include/krb5/krb5.hin

The first commit is the impetus for the PR, though I don't have a good solution.  It seems that our docs builds fail when a literal block ends a doxygen section (trace in commit message).
Second commit fixes all (other) warnings from doxygen.  These are visible in CI, but are not currently fatal.
Note that as in 281210909beef4683be3b63bc1ac1e75c2c9c7eb , I have not addressed the sphinx 4.0 deprecations.  Right now, those are:
/home/rharwood/krb5.git/newer-sphinx/src/doc/rst_composite/conf.py:102: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
app.add_stylesheet('kerb.css')
/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py:2147: RemovedInSphinx40Warning: highlightlang directive is deprecated. Please use highlight …

Fix some docs warnings

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h
src/plugins/preauth/pkinit/pkinit_identity.c

Instead of calling dlopen() directly, use the krb5 cross-platform interfaces (krb5int_open_plugin()).
The goal here is to eventually support pkinit on Windows; this is just the first small step in that direction. We had talked about this change a while back on krbdev; the reason I am submitting a pull request now is I would like to submit a pull request soon to include a lot of extra trace points in the pkinit plugin, and this is a small piece of that.
This patch also removes the include of dlfcn.h in pkinit_clnt.c and pkinit_identity.c; that file doesn't exist on Windows and I am not sure why those files include that header as they don't call dlopen(). It looks like it's been that way since the beginning.

Use krb5int_open_plugin for PKCS#11 module

---

src/appl/gss-sample/gss-server.c
src/tests/gss-threads/gss-server.c

Calling listen system call with zero backlog makes gss-server execution (and tests) racy on slower and busy systems.

gss-server: Avoid calling listen(2) with zero backlog

---

src/include/kcm.h
src/lib/krb5/ccache/cc_kcm.c
src/tests/kcmserver.py
src/tests/t_ccache.py

This is based on the following `krbdev` thread:
https://mailman.mit.edu/pipermail/krbdev/2021-February/013424.html
* @greghudson Is this something MIT Kerberos would accept?
* @nicowilliams Is this something that could be accepted for KCM protocol?
**kcm: use GET_CRED_LIST where available**
---
This KCM operation will returned all credentials of the selected
ccache. This change will remove unnecessary IO operations that
are a bottleneck for large ccaches, mostly for GSSAPI and
applications that iterates over credentials often. The implementation
is backwards compatible - if the call is not available or fails, it
will fallback to `GET_CRED_UUID_LIST`.
**cc: add krb5_cc_notification_path**
---
This adds new API function `krb5_cc_notification_path`. The purpose
of this call is to create a …

kcm: improve performance

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_identity.c

pkinit_client_process() calls pkinit_client_profile() a second time,
leaking the values obtained the first time.  Remove the call.
Commit 13ae08e70a05768d4f65978ce1a8d4e16fec0d35 introduced more
possibilities for process_option_identity() to return failure after it
filled in some fields.  PKCS11 option parsing already prevents leaks
by freeing old values before setting new ones; do so in the other
option-parsing functions as well.

Fix PKINIT memory leaks

---

doc/admin/admin_commands/ktutil.rst

The example of writing to a file named `keytab` is ambiguous. Name the file `alice.keytab` instead, to match the example user principal name.

doc: improve ktutil example keytab filename

---

src/lib/crypto/builtin/aes/aes-gen.c

rand() can output different sequences on different platforms with the
same seed, and (since commit cb5f190056ef4d123c5fe5d4923982b830288438)
we want fixed output.  Use specified inputs instead.  Reported by Ken
Hornstein.

Avoid rand() in aes-gen test program

---

src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/init_sec_context.c

Commits abcfdaff756631d73f49103f679cafa7bc45f14e and
41ddaaeb286e8bb1bba64fb557ba0e4cff9b404d incorrectly changed the
interpretation of authenticator sequence numbers in the range
2^31..2^32-1, mapping them to sign-extended 64-bit values.  The major
Kerberos implementations do not generate sequence numbers this large,
so the changed went unnoticed.  Prevent unwanted sign extension by
casting sequence numbers retrieved from auth contexts to uint32_t
before assigning them to uint64_t fields.  Reported by Jake Scott.

Fix gss-krb5 handling of high sequence numbers

---

src/include/kcm.h
src/lib/krb5/ccache/cc_kcm.c

MIT krb5 uses low bits for KRB5_TC flags, while Heimdal uses high bits
so that the same flag word can also hold KRB5_GC flags.  Add a mapping
function and send the Heimdal flag values when performing a
remove_cred operation.

Fix KCM flag transmission for remove_cred

---

src/lib/krb5/ccache/cc_kcm.c

sssd-kcm returns KRB5_CC_IO if the operation code is not known,
therefore krb5 needs to accept this error code to fallback properly.

kcm: fallback to GET_CRED_UUID_LIST also on KRB5_CC_IO

---

src/include/kcm.h
src/lib/krb5/ccache/cc_kcm.c
src/tests/kcmserver.py
src/tests/t_ccache.py

In kcm_retrieve(), try KCM_OP_RETRIEVE.  Fall back to iteration if the
server doesn't implement it, or if we can an answer incompatible with
KRB5_TC_SUPPORTED_KTYPES.
In kcmserver.py, implement partial decoding for creds and cred tags so
that we can do a basic principal name match.

Use KCM_OP_RETRIEVE in KCM client

---

src/include/krb5/krb5.hin
src/lib/krb5/ccache/cccursor.c

For the purposes of determining whether Kerberos credentials are
present, just check for an initialized ccache (as detected by
krb5_cc_get_principal()), not one with credentials in it.  For KCM
caches in particular, this changes avoids the O(n) expense of starting
an iteration.
Also fix a potential memory leak if a cache is found after an error is
saved.

Simplify krb5_cccol_have_content()

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_identity.c
src/plugins/preauth/pkinit/pkinit_matching.c
src/plugins/preauth/pkinit/pkinit_trace.h

As discussed previously, we are in the process of moving away from our own forked PKINIT plugin to the stock MIT PKINIT plugin. One thing our forked PKINIT plugin could do was conditionally enable the pkiDebug macro (this plugin fork predates the KRB5_TRACE functionality)
After observing the existing KRB5_TRACE output, our customer support staff had communicated to me that the existing trace points did not convey enough information that they could successfully debug PKINIT problems. This pull request adds additional trace points based on their feedback.
They specifically asked for more information about the following things:
- Any errors/messages regarding loading a PKCS#11 plugin
- Information about the certificates being processed from a PKCS#11 plugin
- Certificate matching (and more …

Add additional KRB5_TRACE points

---

src/clients/kpasswd/kpasswd.c
src/config/win-pre.in
src/lib/krb5/rcache/rc_dfl.c
src/util/support/dir_filenames.c

Fix three Windows-specific argument type errors, including a crash bug
in the default replay cache type.  Change the compiler flags to treat
several argument type warnings as errors.
The replay cache bug was reported by Thomas Wagner.
[Side note, not in the commit message: I had considered flagging "incompatible types" (C4133) as an error, but we have eleven harmless instances of that warning in the build, all stemming from Windows/POSIX disagreements about pointer types in socket-layer functions like setsockopt().]

Fix argument type errors on Windows

---

src/lib/kadm5/server_internal.h
src/lib/kadm5/srv/svr_policy.c

While working on converting the libkadm5 unit tests away from TCL, I noticed two policy error-handling foibles which seemed (a) asymmetric with the corresponding principal handling functions, and (b) counter to the intent of the TCL tests, although the tests passed (one because it just looked for "DUP" in the error code name, the other because it used an undefined mask bit but also a defined-but-prohibited mask bit).

Two small libkadm5srv policy fixes

---

src/lib/krb5/ccache/cc_kcm.c

Commit 795ebba8c039be172ab93cd41105c73ffdba0fdb added a retrieval
handler using KCM_OP_RETRIEVE, recognizing the same error code as the
previous KCM_OP_GET_CRED_LIST support.  But sssd (as of 2.4) returns
KRB5_CC_NOSUPP instead of KRB5_CC_IO if it recognizes an opcode as
unsupported.  Add a helper function to recognize all possible
unsupported-opcode errors and use it in kcm_retrieve() and
kcm_start_seq_get().

Fix KCM retrieval support for sssd

---

src/include/win-mac.h

ACE library defines MAXHOSTNAMELEN macro - http://www.aoc.nrao.edu/php/tjuerges/ALMA/ACE-5.5.2/html/ace/os__netdb_8h-source.html#l00072
If project uses both ACE and MIT Kerberos then it conflicts and gives compilation error.
Adding a check to prevent macro redefinition.

ACE library defines MAXHOSTNAMELEN macro, adding check for the same.

---

src/clients/kinit/kinit.c
src/lib/kadm5/clnt/client_init.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sn2princ.c
src/tests/t_kadmin.py
src/tests/t_keytab.py

Using `dns_canonicalize_hostname = fallback`, currently:
```
kinit: Cannot determine realm for host (principal host/kerberos.example.com@)
#
```
With changes:
```
[61971] 1622750537.186595: Matching host/kerberos.example.com@ in collection with result: -1765328243/Can't find client principal host/kerberos.example.com@ in cache collection
[61971] 1622750537.186596: Getting initial credentials for host/kerberos.example.com@
[61971] 1622750537.186597: Found entries for host/kerberos.example.com@EXAMPLE.COM in keytab: aes256-cts, aes128-cts, rc4-hmac, camellia256-cts, camellia128-cts
[61971] 1622750537.186601: Sending unauthenticated request
[61971] 1622750537.186602: Sending request (211 bytes) to EXAMPLE.COM
[61971] 1622750537.186603: Resolving hostname kerberos.example.com
[61971] …
```

Allow kinit with keytab to defer canonicalization

---

src/configure.ac
src/tests/softpkcs11/main.c

Technically only the first commit is needed to unbreak the CI, but I took care of the deprecation warning while I was there since it's a similar issue.
One thing I'm not sure about is how far back we want to support: softpkcs11 appears to have glue code for `EVP_PKEY_get0_RSA` that I've left for now.
~~I'm not sure whether we'll need to load the legacy provider for running in openssl's CI.  I have support for that in the other branch if it ends up being needed.~~ (It wasn't needed for this, but it's in the other branch because it's needed for other things.)

Modernize softpkcs11's openssl

---

src/plugins/tls/k5tls/openssl.c

Starting in OpenSSL 3, connection termination without a close_notify
alert causes SSL_read() to return SSL_ERROR_SSL.  Set
SSL_OP_IGNORE_UNEXPECTED_EOF so that we get the more familiar
SSL_ERROR_ZERO_RETURN instead so that we continue working with kdcproxy.
Remove the call to SSL_CTX_get_options() since SSL_CTX_set_options()
doesn't clear existing options.
[This is not detected by openssl CI currently because openssl CI doesn't run the proxy tests.]

Set SSL_OP_IGNORE_UNEXPECTED_EOF for OpenSSL contexts

---

src/lib/kadm5/admin_internal.h
src/lib/kadm5/clnt/client_init.c
src/lib/kadm5/srv/server_init.c
src/lib/kdb/kdb5.c

This patch contains two commits from PR #1193 and some additional work-in-progress fixes.  Together, they are enough for a clean test run with asan enabled.  I apparently did enough leak checking of t_kadm5.c to not have any leaks in the actual test program, but didn't run some of the stuff I wrote later through valgrind or asan.
These are all leaks that can happen in unlikely exception cases, although the exceptions aren't so unlikely that we can't write tests for them.  I will possibly squish these with the other leaks in unlikely exception cases from PR #1193, but I wanted a separate PR branch for WIP and review.
The libkdb5 leak is kind of interesting: if krb5_db_open() fails, it leaves behind a populated dal_handle in the context.  The caller is unlikely to run krb5_db_close() since …

Leaks related to kadm5_init functions

---

.github/workflows/build.yml

Now that there's no dejagnu stuff in the test suite, the Linux jobs run about twice as fast as the Windows build.  That's also the approximate penalty for enabling asan.
I chose to add asan to the existing linux-clang job instead of creating a new job.  That job will skip the test that uses resolv_wrapper, but the other two jobs will run that test so it should be fine.
The CI for this PR branch should fail until PR #1198 is merged, providing an example of what an asan failure will look like.  It looks like the runner doesn't need any explicit symbolizer configuration to produce readable stack traces.

Use asan in one of the CI builds

---

src/lib/krb5/ccache/cc_memory.c

Without locking, the principal pointer could be freed out from under
krb5_copy_principal() by another thread calling krb5_cc_initialize()
or krb5_cc_destroy().
[This seems likely to be the cause of the crash mentioned in https://mailman.mit.edu/pipermail/krbdev/2021-May/013462.html now that I have looked at a stack trace provided by Thomas.]

Using locking in MEMORY krb5_cc_get_principal()

---

src/kdc/kdc_preauth_ec.c

Reorganize ec_verify() and ec_return() to use cleanup labels instead
of if-ladders.  Also use unconditional calls to free functions and
change a few variable names.

Modernize kdc_preauth_ec.c

---

src/tests/t_ccache.py

The build directory path may be too long for a Unix domain socket, so
use a path in a temporary directory instead.  Reported by Ryan
Schmidt.

Avoid long socket paths in KCM tests

---

src/clients/kinit/kinit.c
src/clients/kvno/kvno.c
src/include/kcm.h
src/lib/krb5/ccache/cc-int.h
src/lib/krb5/ccache/cc_dir.c
src/lib/krb5/ccache/cc_file.c
src/lib/krb5/ccache/cc_kcm.c
src/lib/krb5/ccache/cc_memory.c
src/lib/krb5/ccache/ccbase.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/t_vfy_increds.c
src/tests/Makefile.in
src/tests/conccache.c
src/tests/kcmserver.py
src/tests/t_ccache.py

Here is some work on ticket 7707, which is the long-standing problem that refreshing a ccache creates a window of time where krb5_get_credentials() will fail.  As Michael Osipov observed, this can create a problem for concurrent use of a ccache with a client keytab.
The approach here is the fourth alternative described in ticket 7707: make krb5_cc_move() atomic when possible, and make kinit-like activities write to a memory ccache.  Various complications, notes, and TBD items:
* There were some locking calls in krb5_cc_move(), but they just lock process-global mutexes, so I'm not sure what they're supposed to accomplish; anything that could happen to a ccache concurrently within a process could happen within another process.  I didn't preserve them.
* I included a test program to exercise …

Atomic ccache refresh

---

src/include/krb5/audit_plugin.h
src/include/krb5/authdata_plugin.h
src/include/krb5/clpreauth_plugin.h
src/include/krb5/kdcpreauth_plugin.h

Internal krb5 plugins passes const string to the plugin's vtable
name field, most of the available vtables already declare the name
as const char *.

Make name in plugin's vtable const

---

.gitignore
doc/appdev/gssapi.rst
src/include/k5-trace.h
src/lib/gssapi/krb5/store_cred.c
src/tests/gssapi/Makefile.in
src/tests/gssapi/t_credstore.py
src/tests/gssapi/t_store_cred.c
src/tests/gssapi/t_store_cred.py

Select an output credential cache using similar logic to kinit.  Do
not require the target cache to be initialized.
Try to use the per-thread cache set by gss_krb5_ccache_name() if no
output cache was specified via a cred store.
When the destination is a collection, honor the default_cred flag by
switching the primary cache to the selected output cache.  When the
destination is not a collection, ignore the default_cred flag.
(Previously the default_cred flag was mandatory for gss_store_cred()
even though it is an advisory flag, and ignored for
gss_store_cred_into() even if no ccache was specified in the cred
store.)
Honor the overwrite_cred flag by refusing to replace an initialized
cache if it is not set.  Stop using gss_acquire_cred() for this
purpose as it could go out and fetch …

Improve gss_store_cred() behavior

---

src/plugins/preauth/otp/otp_state.c

The radius client is stored in otp state but never freed.

otp: free radius client

---

src/tests/softpkcs11/main.c

Commit 00de1aad7b3647b91017c7009b0bc65cd0c8b2e0 used
OPENSSL_clear_free(), which was added in OpenSSL 1.1.  Use
OPENSSL_cleanse() and OPENSSL_free() instead.

Restore OpenSSL 1.0 compatibility in softpkcs11

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h

Here is the third preparatory refactor for proper OpenSSL 3.0 support.  With these changes, getting rid of the DH deprecation warnings becomes a matter of conditionalizing dh_pubkey_der() and compose_dh_pkey() to use new OpenSSL 3.0 interfaces instead of DH_* operations.

Use EVP key agreement in PKINIT

---

src/lib/krad/client.c
src/lib/krad/internal.h
src/lib/krad/remote.c
src/lib/krad/t_daemon.py

libkrad client requests contain a list of references to remotes, with
no back-references or reference counts.  To prevent accesses to
dangling references during cleanup, cancel all requests on all remotes
before freeing any remotes.
Remove the code for aging out unused servers.  This code was fairly
safe as all requests referencing a remote should have completed or
timed out during an hour of disuse, but in the current design we have
no way to guarantee or check that.  The set of addresses we send
RADIUS requests to will generally be small, so aging out servers is
unnecessary.
[The second commit is borrowed from PR #1229]

Avoid use after free during libkrad cleanup

---

src/lib/krad/attrset.c
src/lib/krad/t_packet.c

To avoid ambiguity the length byte in the Radius attribute is should be treated as unsigned explicitly. Otherwise it might be possible that attributes longer than 125 characters will be rejected with EBADMSG.
A 253 characters long NAS-Identifier attribute is added to the tests to make sure that attributes with the maximal number of characters are working as expected.

kr_attrset_decode: make sure length byte is unsigned

---

src/aclocal.m4

The configure machinery for adding the `-search_paths_first` linker flag
on Darwin does not correctly handle cross compilation. (It should
condition the value of `krb5_cv_host` rather than `uname -s` to detect
when the compilation target is Darwin, rather than the build machine.)
It turns out `-search_paths_first` has been the default behavior of ld
on macOS since XCode 4 (see `man ld`). So this commit just removes that
big of configury entirely. That neatly fixes cross compiling from macOS
to Linux without impacting native macOS builds.
(The history checks out here too: the flag was added way back in 2004,
but XCode 4 wasn't released until 2010.)

aclocal: remove unnecessary -search_paths_first flag on Darwin

---

src/lib/krb5/krb/pac.c

[I noticed this refactoring opportunity just before merging PR #1225 but decided that it would be more churn to the PAC code than I wanted to do as part of that PR.]
Reduce code repetition in PAC checksum handling by adding a helper
function.  Remove the unnecessary prefix on several function names.

Factor out PAC checksum verification

---

src/include/gssrpc/auth.h
src/include/gssrpc/rename.h
src/include/gssrpc/svc.h

```
gssrpc/svc.h:296:1: error: function declaration isn’t a prototype
[-Werror=strict-prototypes]
296 | extern void rpctest_service();
```
The Samba developer build is setting `-Werror=strict-prototypes` and fails to build with mit-krb5 master.

include:gssrpc: Fix prototype definitions

---

src/kadmin/server/server_stubs.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/preauth_otp.c
src/lib/krb5/os/sn2princ.c

Passing null to asprintf as a %s parameter causes noisy libc syslog warnings on OpenBSD.
I couldn't find any documentation indicating that passing null as a %.*s parameter was valid, even if the specified length is zero.
The proposed diff addresses one specific instance that was causing noise in my case. Perhaps it would be better to deal with this within split_trailer() or even in empty_data() by using an empty string rather than NULL.

Do not pass null to asprintf

---

src/util/k5test.py

XCode for macOS provides lldb but not gdb.  For convenience, make
k5test default to lldb if gdb is not found in the path.

In k5test, look for lldb if gdb is not found

---

doc/plugindev/certauth.rst
src/include/krb5/certauth_plugin.h

[I told @cryptomilk I would try to clarify this documentation, particularly in regard to the princ parameter.]
Try to make it clearer that princ is the requested client principal,
not a principal decoded from the certificate, and that the module must
decode the certificate and inspect its attributes.  Document
KRB5_CERTAUTH_HWAUTH_PASS in certauth_plugin.h.

Clarify certauth interface documentation

---

src/include/gssrpc/types.hin

Otherwise this conflicts with bool_t and enum_t in fbthrift:
https://github.com/facebook/fbthrift/blob/main/thrift/lib/cpp2/type/Tag.h#L59

Use typedef to define bool_t and enum_t

---

src/kprop/kprop.c
src/kprop/kprop.h
src/kprop/kprop_util.c
src/kprop/kpropd.c
src/tests/t_kprop.py

When doing a full resync of the KDC database, `kprop` stores and sends the size of the dumped database on a 32 bits integer. As a consequence, any value bigger than 2<sup>32</sup>-1 (ie. >= 4GiB) wraps, resulting in a invalid smaller size.
I am not sure if this behavior could actually result in a truncated database being propagated without any error. It seems the deserialization will just fail if the invalid EOF happens at the middle of a line of the transmitted dumped DB file. But maybe it could happen in case invalid EOF occurs on a newline character. It does not looks like the database dump file contains any information about its length in the header.
This problem has been identified and reported to Red Hat by Keith Young from Morgan Stanley. He provided an initial fix I completed with …

Fix KDC DB propagation when larger than 4 GiB

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

Various organizations [including NIST](https://csrc.nist.gov/News/2017/Research-Results-on-SHA-1-Collisions) have been strongly recommending to stop using SHA-1 for digital signatures for some years already. CMS digest is used to generate such signatures, hence it should be upgraded to use SHA-256.
This change has already been [implemented in Heimdal](https://github.com/heimdal/heimdal/commit/c4c71cc41a2763a23867c7c6a041d1f4f1ebcbf7).

Use SHA-256 instead of SHA-1 for PKINIT CMS digest

---

src/lib/krb5/os/changepw.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sendto_kdc.c

Commit d7b3018d338fc9c989c3fa17505870f23c3759a8 (ticket 7905) changed
change_set_password() to prefer TCP.  However, because UDP_LAST falls
back to UDP after one second, we can still get a replay error due to a
dropped packet, before the TCP layer has a chance to retry.
Instead, try k5_sendto() with NO_UDP, and only fall back to UDP after
TCP fails completely without reaching a server.  In sendto_kdc.c,
implement a NO_TCP transport strategy to allow the UDP fallback.

Try harder to avoid password change replay errors

---

src/include/kdb.h

kdb.h uses time_t, and therefore must include <time.h> to ensure its
definition.  Noticed when building t_sort_key_data.c on macOS.

Include time.h in kdb.h

---

src/lib/kadm5/clnt/client_init.c

kpropd produces a client principal name with
krb5_sname_to_principal(), then converts it to a string to pass as the
client principal to kadm5_init_with_skey().  This conversion loses the
name type, so no canonicalization is performed by libkadm5.
Commit dcb79089276624d7ddf44e08d35bd6d7d7e557d2 addresses this problem
for kadmin -k by looking for the referral realm, but kpropd sets the
realm in the krb5_sname_to_principal() result.  Add an additional
check for a two-component principal with kiprop as the first
component.

Fix iprop with fallback

---

doc/admin/conf_files/krb5_conf.rst
doc/build/options2configure.rst
doc/conf.py
doc/mitK5defaults.rst
src/configure.ac
src/doc/Makefile.in
src/man/Makefile.in
src/man/krb5.conf.man
src/plugins/preauth/pkinit/pkinit.h

Allow to override `opensc-pkcs11.so` as the default PKCS#11 module name.
This is useful to make the client configuration library-agnostic by using modules like `p11-kit-proxy.so` as a generic layer in front of other PKCS#11 implementations.
In this case `pkinit_identities = PKCS11:` would be enough to enable the use of smartcards by having p11-kit detecting any PKCS#11 module installed.

Add autoconf parameter for default PKCS#11 module

---

src/build-tools/krb5-config.in

Linker options supplied at configure time such as -Wl,--as-needed can
be harmful when applied to downstream users of the libraries, and in
most cases should not be necessary.

Omit LDFLAGS from krb5-config --libs output

---

src/plugins/preauth/pkinit/pkinit_srv.c

while testing krb5-1.20-beta1 with Solaris I've found a memory
leak in krb5kdc. The libumem reports leak as follows:
```
CACHE     LEAKED   BUFCTL CALLER
0059d458      46 0075dbd0 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      14 008b2470 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      28 008b2548 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      15 0075cad0 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      15 00757098 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      15 0075c4e8 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      15 008b53b0 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      15 0075dca8 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458      14 008b3700 libcrypto.so.1.0.0`default_malloc_ex+0x1f
0059d458     122 0075d510 …
```

memory leak coming from pkinit_crypto_openssl.c pre-auth plugin

---

src/kdc/main.c
src/plugins/preauth/otp/main.c
src/util/k5test.py

While thinking about PR #1253 I realized we could do a better job of catching asan failures in k5test.  The third commit here does that, by reworking daemon checking so that it applies to daemons we deliberately terminate.
The first two commits fix bugs detected by this change: a small but regular memory leak in OTP, and an exit-time KDC memory error relating to an interaction between OTP and KDC cleanup order.
This change also detects the PR #1253 memory leak, so the CI for this PR should initially fail--and we should be able to see that it displays the asan memory leak traces for the KDC process.

Improve daemon checking in k5test, and fix two bugs

---

src/util/support/plugins.c

the issue has been hit by `pam-krb5` test suite on Solaris.
one of the testcases uses `pkcs11` pre-authentication.
the krb5.conf in question reads as follows:
```
[libdefaults]
default_realm = ACME.COM
[realms]
ACME.COM = {
pkinit_identity = FILE:/usr/tmp/ca/kdc.crt,/usr/tmp/ca/kdc.key
pkinit_anchors = FILE:/usr/tmp/ca/ca.crt
pkinit_identities = PKCS11:
kdc = kdc.acme.com
admin_server = kdc.acme.com
}
[domain_realm]
.acme.com = ACME.COM
[logging]
default = FILE:/var/krb5/kdc.log
kdc = FILE:/var/krb5/kdc.log
kdc_rotate = {
period = 1d
versions = 10
}
[appdefaults]
gkadmin = {
help_url = help_url
}
```
After building a kerberos with `DEBUG` option enabled I could obtain
a log as follows from our `pamtest` binary:
```
Calling pam_authenticate
stat(/usr/lib/krb5/plugins/preauth/spake.so): No …
```

pkinit pre-auth fails to load libpkcs11.so on Solaris

---

src/plugins/preauth/pkinit/pkinit_constants.c
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

The PKINIT client uses `AuthPack.supportedCMSTypes` to let the KDC know
about the algorithms it supports for verification of CMS data signature.
This commit replaces 3DES, which is currently the only algorithm
provided in this list and could be considered outdated, by SHA-256 and
SHA-512. But more algorithms could be added. As a comparison, the [list used by Heimdal](https://github.com/heimdal/heimdal/blob/heimdal-7.7.0/lib/hx509/crypto.c#L966-L988) includes more algorithms.
This change will not affect the way the MIT KDC handles PKINIT requests because the CMS data digest (SHA-256) [is hard coded](https://github.com/krb5/krb5/blob/master/src/plugins/preauth/pkinit/pkinit_crypto_openssl.c#L1674). However, this is important for integration with Heimdal because this KDC selects the digest …

Set SHA-2 as supportedCMSTypes instead of 3DES

---

src/configure.ac
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h

CMS support is present in OpenSSL 1.0, which is the earliest supported
version.
I looked into changing cms_signeddata_create() to use CMS APIs rather than PKCS7 APIs, but it doesn't look easy.  In the PKCS11 case we need to generate the signature ourselves, and the CMS APIs appear to require that OpenSSL generate the digest and signature internally (with the caller providing the private key).  It's possible that we could do something with engines and providers for OpenSSL 1.x and 3.x respectively.
LibreSSL support isn't a priority for us, but I checked and they added CMS support in 2019.

Remove pre-CMS PKINIT compatibility code

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_srv.c

Every caller of cms_signeddata_create() and cms_envelopeddata_create()
passes 1 for include_certchain.  Remove the parameter and
unconditionally add the certificate chain.

Remove include_certchain parameter in PKINIT

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/tgs_policy.c

For simplicity, return com_err codes from validate_as_request() and
validate_tgs_request() instead of protocol error constants.

Avoid protocol error constants in KDC code

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

The code for CMS data verification was initially written for OpenSSL's `PKCS7_verify()` function. It has been replaced by `CMS_verify()` but error handling is still done using `PKCS7_verify()` error identifiers. It results in the `KDC_ERR_DIGEST_IN_SIGNED_DATA_NOT_ACCEPTED` error to not be raised when it should.
This commit replaces error identifiers with CMS ones.
I also replaced the `ERR_peek_error()` call by `ERR_peek_last_error()` because the first error in OpenSSL's stack is always `CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA` in this context. Therefore it does not allow to differentiate an error caused by an unaccepted digest algorithm and an invalid signature.
Tests confirmed the following errors to be raised in given scenarios:
* `EVP_R_INVALID_DIGEST`: The digest algorithm is …

Update error codes for OpenSSL CMS_verify

---

src/include/k5-int.h
src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/acquire_cred.c
src/lib/gssapi/krb5/context_time.c
src/lib/gssapi/krb5/init_sec_context.c
src/lib/gssapi/krb5/inq_context.c
src/lib/gssapi/krb5/inq_cred.c
src/lib/gssapi/krb5/s4u_gss_glue.c
src/lib/krb5/ccache/cc_keyring.c
src/lib/krb5/krb/get_in_tkt.c

During interactive password pre-authentication, a warning is printed in case the password expiry time delta is less than one week. However this time delta is stored as a signed 32-bit integer, while the current and expiry date times are stored as unsigned 32-bit integers (even if their declared type is signed).
As a consequence, an expiry date that is more than 2^31 - 1 seconds in the future will cause this time delta to wrap. It results in the expiry warning message "Your password will expire in less than one hour" to be displayed, while the actual expiry date is more than 68 years in the future.
This commit fixes this issue by casting the delta as unsigned after the expiry date is confirmed to be in the future.

Use unsigned 32-bit integer for password expiry delta

---

src/kdc/do_as_req.c
src/kdc/do_tgs_req.c
src/kdc/fast_util.c
src/kdc/kdc_audit.c
src/kdc/kdc_log.c
src/kdc/kdc_util.c
src/kdc/kdc_util.h
src/kdc/tgs_policy.c

Split the TGS processing code into information gathering, policy
checking, and ticket-issuing steps, using a structure to hold the
gathered information.  Fold kdc_process_s4u2proxy_req() into
validate_tgs_request(), except for the get_pac_princ_with_realm()
which is now done directly in gather_req_info().  Modify some other
utility functions to fit the new design.

Refactor KDC TGS processing code

---

src/include/k5-trace.h

```
[73] 1666981595.989068: Armor ccache sesion key: aes256-cts/7175
^^^^^^                            
```

fix typo in KRB5_TRACE message text

---

src/aclocal.m4

The block argument of the `AC_CACHE_VAL` call ends before the `if` instruction can reach the corresponding `fi` one. This `fi` is definitely meant to be part of this block.

Fix syntax error in aclocal.m4

---

src/lib/krb5/krb/gic_keytab.c

Hi @greghudson 
I found another core dump in the test, The following is the full core dump
```
Type "apropos word" to search for commands related to "word"...
Reading symbols from kinit...
Reading symbols from /usr/lib/debug//usr/bin/kinit-1.19.2-2.h9.eulerosv2r11.x86_64.debug...
[New LWP 3844944]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/kinit -kt /etc/key.keytab user'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  get_as_key_keytab (prompter=<optimized out>, prompter_data=<optimized out>, salt=<optimized out>, params=0x55abc3c5b098, ritems=0x55abc3c5b1b0,
gak_data=0x55abc3c5a7e0, as_key=0x55abc3c5b0a8, etype=18, client=0x55abc3c5adb0, context=0x55abc3c57ba0) at …
```

fix core dump get as key keytab

---

src/kprop/kpropd.c

hey，I am trying to use kpropd recently. I find coredump when enter "kpopd --help" before I read manpage.
I think this patch will fix the coredump.

fix coredump with unrecognized option

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

[@jrisc please verify that this seems okay for Fedora.  Checking specifically for an invalid signature seems much easier than checking for algorithm issues, as the error code is singular and stable whereas algorithm issues can manifest along lots of different code paths.  An invalid signature also seems less likely than an algorithm issue, so we're less likely to return the wrong thing if we assume that almost all error codes indicate algorithm issues.]
Commit 70f61d417261ca17efe3d60d180033bea2da60b0 updated the CMS_verify() error code checks, using two error codes new to OpenSSL 3.0 (RSA_R_DIGEST_NOT_ALLOWED and CMS_R_UNKNOWN_DIGEST_ALGORITHM). This change broke the build for OpenSSL 1.0 and 1.1.
Instead of looking for codes indicating an algorithm issue and assuming that everything else …

Fix PKINIT CMS error checking for older OpenSSL

---

doc/admin/conf_files/krb5_conf.rst
doc/admin/enctypes.rst
src/include/k5-int.h
src/kdc/kdc_util.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_ctx.c
src/tests/gssapi/t_enctypes.py
src/tests/t_etype_info.py
src/tests/t_keyrollover.py
src/tests/t_sesskeynego.py
src/util/k5test.py

This is prompted by https://i.blackhat.com/EU-22/Thursday-Briefings/EU-22-Tervoort-Breaking-Kerberos-RC4-Cipher-and-Spoofing-Windows-PACs-wp.pdf which observes that rc4-hmac pre-hashes the input string before applying HMAC in its checksum and GSS algorithms, and is therefore vulnerable to spoofing via collision attacks (as opposed to just second preimage attacks as it would be if HMAC were properly applied).  The paper concludes that:
* There isn't a current reason to be concerned about the RC4 encryption algorithm, as it properly uses HMAC for the authentication tag.  (RC4's weaknesses might be an issue if lots of data is encrypted with the same key, but that is not common in Kerberos.)
* There is a concrete vulnerability in PACs, but a similar vulnerability is present for almost any …

Prevent issuance of RC4 and DES3 session keys by default

---

src/kadmin/cli/getdate.y

The meridian suffix is typed as "Number" in kadmin YACC file for datetime parsing, while it should be using the "Meridian" enumeration one.
This results in invalid Meridian value on 64-bit IBM zSystems (s390x), causing core dumped errors on most kadmin commands where meridian suffices are used:
```
Hardware watchpoint 2: yyMeridian
Old value = MER24
New value = (MERpm | unknown: 0x4)
getdate_yyparse () at y.tab.c:1428
1428        break;
(gdb) l
1423                yyMinutes = (yyvsp[-1].Number);
1424                yySeconds = 0;
1425                yyMeridian = (yyvsp[0].Meridian);
1426            }
1427    #line 1428 "y.tab.c"
1428        break;
1429
1430      case 12: /* time: tUNUMBER ':' tUNUMBER tSNUMBER  */
1431    #line 231 "getdate.y"
1432 …
```

Fix meridian type in kadmin datetime parser (s390x)

---

src/lib/kdb/decrypt_key.c
src/lib/kdb/encrypt_key.c

The `krb5_dbe_def_encrypt_key_data()` function is [freeing `key_data->key_data_contents[0]` in case the call to `krb5_c_encrypt()` failed](https://github.com/krb5/krb5/blob/krb5-1.20.1-final/src/lib/kdb/encrypt_key.c#L111). However, since a06945b4 a failure return code from `krb5_dbe_encrypt_key_data()` in `add_principal()` will [result in a call to `krb5_db_free_principal()`](https://github.com/krb5/krb5/blob/krb5-1.20.1-final/src/kadmin/dbutil/kdb5_create.c#L476). This function [loops over `key_data_contents`, freeing all non-`NULL` pointers](https://github.com/krb5/krb5/blob/krb5-1.20.1-final/src/lib/kdb/kdb5.c#L124-L129).
```
[...]
==3559== Invalid free() / delete / delete[] / realloc()
==3559==    at 0x48470E4: free (vg_replace_malloc.c:872)
==3559==    by 0x48826B9: …
```

KDB: Set key data pointer to NULL to avoid double free

---

src/lib/krb5/krb/authdata.h
src/lib/krb5/krb/pac.c
src/lib/krb5/krb/pac_sign.c

Put the version and buffers directly in krb5_pac_data to avoid using a variable-length array.  Use k5input for krb5_pac_parse().  Adjust some names and comments.

Modernize PAC code

---

.github/workflows/build.yml
.github/workflows/doc.yml
src/config/ac-archive/README
src/config/ac-archive/ax_pthread.m4
src/lib/krb5/krb/deltat.c
src/lib/krb5/krb/x-deltat.y
src/plugins/kdb/db2/libdb2/hash/hash_page.c
src/plugins/kdb/ldap/ldap_util/kdb5_ldap_realm.c
src/util/export-check.pl

I'm still unsure of whether resolv-wrapper is expected to work on Ubuntu 22.04 (see https://bugzilla.samba.org/show_bug.cgi?id=14830 ).  I may need to find an alternative way to test URI discovery.

Update CI for newer Ubuntu and fix associated warnings

---

src/lib/gssapi/generic/gssapi_ext.h
src/lib/gssapi/generic/gssapi_generic.c
src/lib/gssapi/krb5/gssapiP_krb5.h
src/lib/gssapi/krb5/gssapi_krb5.c
src/lib/gssapi/krb5/inq_context.c

The Oracle database wire protocol contains a cipher reinitialization operation using the ticket session key.  Add a query operation (similar to GSS_C_INQ_SSPI_SESSION_KEY) to retrieve the ticket session key rather than the subkey.

Add GSS_C_INQ_ODBC_SESSION_KEY

---

src/include/krb5/certauth_plugin.h
src/plugins/preauth/pkinit/pkinit_srv.c

Increment the certauth interface major version to 2, without backward compatibility.  Add the realm names list to the init method.  Add an hwauth_out parameter to the authorize method to make that output independent of the error code.
@kenh: Please let me know if this meets your requirements, and if the major version bump would be a burden.  My sene is that there aren't other users of the certauth interface or that they are in similar situations (site administrators rather than downstream software).  (@jrisc you aren't aware of any Red Hat package uses of this interface, right?)
If the major version bump is a burden, we could instead add a second init function to provide the realm list, similar to the kdcpreauth interface's loop() method, and defer the authorize() cleanup.
In the mail …

Revise certauth interface

---

src/config/win-post.in
src/config/win-pre.in
src/lib/Makefile.in
src/lib/crypto/builtin/aes/brg_endian.h

Update various checks to include "ARM64" and "_M_ARM64".
Remove a /BASE flag which fixes an "ARM64 image cannot have base address below 4GB" error and which arguably shouldn't be used in modern times since it prevents using dynamic base addresses.

Get arm64-windows builds working

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h

OpenSSL may no longer allow to decode non-well-known Diffie-Hellman groups as EVP_PKEY objects in FIPS mode. However, OpenSSL does not know about the MODP well-known group 2 (1024-bit), which is [considered as a custom group](https://github.com/openssl/openssl/issues/18981). As a consequence, the PKINIT plugin failed to load systematically in FIPS mode because the 3 groups are required.
This pull request allows initialization of the PKINIT plugin if at least one of the MODP well-known groups succeed to load. So the PKINIT plugin will continue to work with groups 14 (2048-bit) and 16 (4096) in FIPS mode.

Enable PKINIT plugin if at least 1 of the 3 well-known groups is available

---

src/include/k5-trace.h
src/lib/krb5/krb/gc_via_tkt.c
src/lib/krb5/krb/get_creds.c
src/lib/krb5/krb/get_etype_info.c
src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/gic_keytab.c
src/lib/krb5/krb/gic_pwd.c
src/lib/krb5/krb/in_tkt_sky.c
src/lib/krb5/krb/int-proto.h
src/lib/krb5/os/locate_kdc.c
src/lib/krb5/os/os-proto.h
src/lib/krb5/os/sendto_kdc.c
src/tests/Makefile.in
src/tests/t_sendto_kdc.py

Add an internal variant of krb5_sendto_kdc() which records the answering KDC in a history object.  Callers can check the history object for replica KDC use after the success or failure of the KDC exchange is determined, using only DNS query per realm and transport when DNS queries are needed.
Preserve the current signature of krb5_sendto_kdc() (it is used within the tree outside of libkrb5, and might be used by other software despite being non-public), but remove the behavior of setting *use_primary.
See https://krbdev.mit.edu/rt/Ticket/Display.html?id=7721 for more information.  This solution is a little higher on complexity than I would like, and I need to think about whether I can add any tests for it.  The best alternative design I could think of (the second candidate) would bleed …

Defer primary KDC lookups

---

doc/admin/conf_files/kdc_conf.rst
doc/admin/conf_files/krb5_conf.rst
src/plugins/preauth/pkinit/pkinit.h
src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_constants.c
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.h
src/plugins/preauth/pkinit/pkinit_lib.c
src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h
src/tests/t_pkinit.py

I've been wanting to implement ECC PKINIT support (RFC 5349) for a long time, and some concerns about OpenSSL's finite-field DH support gave me the impetus to put some work into an alternative.  Currently I have a proof of concept, but need to work out some details of the user experience before it will be ready for merging.
The biggest problem is how we decide when to use ECDH on the client, how ECDH support interacts with the pkinit_dh_min_bits variable, and how ECDH support interacts with TD-DH-PARAMETERS negotiation.  Some notes on that:
* Heimdal uses ECDH if the client cert has an EC public key.  This is nice in that it puts the decision under control of the client CA, but it doesn't address anonymous PKINIT, and support for EC certs doesn't actually imply KDC support for ECDH (the …

PKINIT ECDH support

---

src/plugins/preauth/pkinit/pkinit_constants.c

Elliptic curve certificates are already supported for PKINIT pre-authentication, but their associated signature types are not advertized in the algorithm agility mechanism of CMS.
This commit adds ecdsa-with-sha512 and ecdsa-with-sha256 OIDs to the supportedCMSTypes list.
This PR results in the following AS-REQ `AuthPack` structure (if used with ECDH support from  #1301):
```
[AuthPack] {
pkAuthenticator [PKAuthenticator] {
cusec [INTEGER]            0x02da7f (187007 decimal)
ctime [KerberosTime]       20230628142900Z
nonce [INTEGER]            0x32973dc7 (848772551 decimal)
paChecksum [OCTET STRING]  ...
}
clientPublicValue [SubjectPublicKeyInfo] {
algorithm [AlgorithmIdentifier] {
algorithm [OBJECT IDENTIFIER]  1.2.840.10045.2.1 (ecPublicKey)
parameters [ECParameters] {
[OBJECT …
```

Add ecdsa-with-sha512/256 to supportedCMSTypes

---

src/configure.ac
src/util/wsgiref-kdcproxy.py

The `ssl.wrap_socket()` function was deprecated in Python 3.7 and [is removed in Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#removed). It results in the following error on Fedora Rawhide:
```
PYTHONPATH=../util VALGRIND="" python3 ./t_proxy.py 
*** Failure: /usr/bin/python3 failed to start with code 1.
*** Last mark: untrusted issuer, hostname mismatch
*** Last command (#4): /usr/bin/python3 /tmp/tmp.YfMScvG3zc/krb5-tests/util/wsgiref-kdcproxy.py 61021 /tmp/tmp.YfMScvG3zc/krb5-tests/tests/proxy-certs/proxy-no-match.pem
*** Output of last command:
Traceback (most recent call last):
File "/tmp/tmp.YfMScvG3zc/krb5-tests/util/wsgiref-kdcproxy.py", line 17, in <module>
server.socket = ssl.wrap_socket(server.socket, certfile=pem, server_side=True)
^^^^^^^^^^^^^^^ …
```

Replace ssl.wrap_socket() Python function

---

src/kdc/do_tgs_req.c

Reproducer in Samba:
`make test TESTS=samba.tests.krb5.kdc_tgs_tests`
```
/usr/sbin/krb5kdc: ================================================================= /usr/sbin/krb5kdc: ==6492==ERROR: AddressSanitizer: attempting double-free on 0x61a00025e080 in thread T0:
/usr/sbin/krb5kdc:     #0 0x7f5c932dad08  (/usr/lib64/libasan.so.8.0.0+0xdad08) (BuildId: a24a20df2a1331371c666de9135abab342429d43)
/usr/sbin/krb5kdc:     #1 0x7f5c9317df72 in krb5_free_ticket krb/kfree.c:455
/usr/sbin/krb5kdc:     #2 0x7f5c9317df72 in krb5_free_ticket krb/kfree.c:450
/usr/sbin/krb5kdc:     #3 0x417fb6 in free_req_info ../../src/kdc/do_tgs_req.c:1144
/usr/sbin/krb5kdc:     #4 0x417fb6 in process_tgs_req ../../src/kdc/do_tgs_req.c:1225
/usr/sbin/krb5kdc:     #5 0x40c35f in dispatch ../../src/kdc/dispatch.c:163 …
```

kdc: Fix double free in free_req_info()

---

src/util/k5test.py

Requiring Python 3.4 gives us shlex.quote() (added in Python 3.3). Use it in _shell_equiv() to quote command arguments.
[I also looked into using subprocess.check_output() for _run_cmd().  It isn't quite a better fit than the existing Popen() and communicate() calls, because it throws an exception on a non-zero status.  subprocess.run() should be a good fit once we require Python 3.5 for the tests.]

Properly quote command strings in k5test.py

---

src/appl/simple/client/sim_client.c

Since a code refactoring in 9139a60c94c24e41109574e84e7cda9c2dc3fb38 getopt.h has not been removed which causes compilation failures on systems without getopt.h being present, .e.g., HP-UX.
Original request, the isser tracker did not accept my report appearantly:
Folks,
with the above change (from 1.21.1) an oversight has been introduced by 
retaining getopt.h include. This fails on HP-UX since there is no 
default getopt library:
```
/opt/aCC/bin/aCC -Ae -DHAVE_CONFIG_H  -I../../../include -I../../../include -I./.. -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE -I/opt/ports/include +We901  -D_REENTRANT -D_THREAD_SAFE -D_POSIX_C_SOURCE=199506L  -c sim_client.c
"sim_client.c", line 42: error #3696-D: cannot open source file "getopt.h"
#include <getopt.h>
^
"sim_client.c", line 234: warning #2167-D: …
```

Replace direct use of getopt.h in favor of a HAVE_GETOPT aware solution

---

src/kadmin/server/deps
src/kdc/Makefile.in
src/kdc/deps
src/lib/crypto/builtin/aes/Makefile.in
src/lib/crypto/builtin/aes/deps
src/lib/crypto/builtin/camellia/Makefile.in
src/lib/crypto/builtin/camellia/deps
src/lib/crypto/crypto_tests/Makefile.in
src/lib/kadm5/Makefile.in
src/lib/kadm5/clnt/deps
src/lib/kadm5/deps
src/lib/krb5/krb/deps
src/lib/krb5/rcache/Makefile.in
src/plugins/preauth/spake/Makefile.in
src/plugins/preauth/spake/deps
src/tests/gssapi/Makefile.in
src/util/et/Makefile.in
src/util/et/deps

I haven't thought of a way to ensure complete dependencies in our CI like we do for some other aspects of build system hygiene (like "make distclean" not leaving anything behind), or even to make sure that this fixes all of the missing dependncies.  I did take a look at semi-recent changes to .gitignore to make sure that all test programs added there have dependencies for their source files.

Add missing dependencies

---

src/doc/Doxyfile.in
src/include/krb5/krb5.hin

Doxygen 1.9.7 avoids duplicating member definitions in the XML documents for groups and header files (doxygen/doxygen#9797).  This change breaks the current Doxygen-REST bridge, which expects to find memberdef elements in krb5_8hin.xml.  To work around this problem, remove the @group and @ref declarations in krb5.hin; they were not translated into REST as it was.
Also remove a deprecated setting in Doxyfile.

Work around Doxygen 1.9.7 change

---

.github/workflows/build.yml
src/clients/ksu/Makefile.in
src/clients/ksu/t_ksu.py

ksu can't easily be tested as part of "make check", because it's setuid and uses a secure krb5_context (which means it will always look at /etc/krb5.conf for configuration).  But these aren't serious impediments for the Github Actions CI, so I wrote a test script for that purpose.  It can also be run on a personal machine which can tolerate a short-term replacement of /etc/krb5.conf.
The asan CI build will fail due to memory leaks, so this will need to be merged after PR #1306 (though of course it can be cherry-picked in a working repository to test that PR).  PR #1309 will require a couple of changes to the script where klist doesn't find a ccache.
There might be something fancy we can do with Linux namespaces to make this friendlier to the host environment, or even runnable as part of …

Add ksu test script

---

src/clients/ksu/main.c
src/clients/ksu/t_ksu.py

ksu attempts to exit with the same status as its child process, but does not do so correctly.  Use WEXITSTATUS() to extract the exit code. Reported by Todd Lubin.
ticket: 8618

Properly mirror child exit status in ksu

---

doc/admin/conf_files/krb5_conf.rst
src/include/k5-int.h
src/lib/krb5/krb/init_ctx.c
src/lib/krb5/os/sendto_kdc.c

Currently there is a hardcoded 10s waiting time for TCP connections before other KDCs or connection types are tried.
With this patch a new libdefaults option 'tcp_waiting_time' is introduced to make this hardcode timeout configurable to either wait longer for the KDC to reply or switch faster to other options if a KDC is not responsive.

make TCP waiting time configurable

---

src/util/def-check.pl

The version of Perl included in git-bash does not translate line endings or filter out the end-of-file marker when reading from files in text mode.  Adjust def-check.pl to work in this environment.

Make def-check.pl work with Windows git-bash perl

---

src/plugins/preauth/pkinit/pkinit_crypto_openssl.c

The PKCS7 ContentInfo content field and EncryptedContentInfo encryptedContent field are optional.  Check for null values in cms_envelopeddata_verify() before calling pkcs7_decrypt().  Reported by Bahaa Naamneh.

In PKINIT, check for null PKCS7 enveloped fields

---

src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto.h
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_kdf_test.c
src/plugins/preauth/pkinit/pkinit_srv.c
src/plugins/preauth/pkinit/pkinit_trace.h

Simplify the client and server PKINIT code by renaming pkinit_alg_agility_kdf() to pkinit_kdf() and making it do RFC 4556 octet2string if alg_oid is null.  Move responsibility for tracing inside the new interface.  Constify some parameters and remove some unnecessary casts.  Rename "key" to "secret" in several internal functions to avoid confusion between the input DH secret and the output key.

Refactor PKINIT KDF internal interfaces

---

src/clients/klist/klist.c

Addition of a `cleanup` section in kinit's `show_ccache()` function as part of 6c5471176f introduced a bug. The `defname` global variable is never explicitly initialized. As a global variable, it implicitly initialized to 0, but in case of a first call to `show_ccache()`, where `krb5_cc_get_principal()` succeeded, a second call occurs where `krb5_cc_get_principal()` failed, it will lead to `free()` being called with the already freed default principal name.
I think we missed this case while working on #1306 because we were doing the assumption `defname` was a local variable. Given the fact the only place were it is used outside of `show_ccache()` is the `show_credential()` function (which is called by `show_ccache()` only), I think we should simply turns `defname` into a local variable …

Double free in klist's show_ccache()

---

NOTICE
doc/conf.py

The SWIG-generated `profile_tcl.c` file was removing in commit 4e186b2789b3613362845b126bf386fa89c26709. There is no need for its license in the NOTICE file anymore.

Remove license for profile_tcl.c

---

src/clients/kcpytkt/kcpytkt.c
src/clients/kdeltkt/kdeltkt.c
src/clients/kinit/kinit.c
src/clients/kinit/kinit_kdb.c
src/clients/klist/klist.c
src/kadmin/cli/kadmin.c
src/kadmin/dbutil/kdb5_util.c
src/kdc/main.c
src/kprop/kpropd.c
src/lib/crypto/builtin/enc_provider/aes.c
src/lib/crypto/openssl/hmac.c
src/lib/krb5/ccache/t_memory.c
src/lib/krb5/ccache/t_stdio.c
src/plugins/kdb/db2/libdb2/btree/bt_debug.c
src/plugins/kdb/db2/libdb2/btree/bt_open.c
src/plugins/kdb/db2/libdb2/hash/dbm.c
src/plugins/kdb/db2/libdb2/test/btree.tests/main.c
src/plugins/kdb/db2/libdb2/test/dbtest.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/tls/k5tls/openssl.c
src/tests/asn.1/make-vectors.c

In commit 4b9d7f7c107f01a61600fddcd8cde3812d0366a2 the `-Werror=strict-prototypes` parameter was added to the build process, but `src/lib/crypto/builtin/enc_provider/aes.c` still contained a non-prototype function declaration. This commit fixes the declaration.
The declaration was probably missed because the code is not always build.

Fix -Werror=strict-prototypes error in aes.c

---

src/kadmin/cli/kadmin.c
src/kadmin/cli/kadmin.h
src/kadmin/cli/keytab.c
src/kadmin/ktutil/ktutil.c
src/kadmin/ktutil/ktutil.h
src/lib/krb5/krb/ser_ctx.c
src/util/profile/prof_init.c
src/util/profile/prof_int.h

Building with link-time optimization reveals some type mismatches in the interface between libkrb5 serialization and the profile library, as well as in consumers of the SS library.  Fix them.  Reported by Eli Schwartz.

Fix type mismatches detected by LTO

---

src/util/profile/prof_file.c
src/util/profile/prof_int.h
src/util/profile/prof_set.c
src/util/profile/t_profile.c

Add the notion of a memory-only prf_data_t object, indicated by an empty filespec field and appropriate flags (do not reload, always dirty, not part of shared trees).  Do nothing when flushing a memory-only data object to its backing file.  When setting up an empty profile for read/write access, create a memory-only data object instead of crashing.
Move prf_data_t mutex initialization into profile_make_prf_data(), simplifying its callers.
[The immediate motivation here is https://github.com/FreeRDP/FreeRDP/issues/9766 .  The less immediate motivation is  https://mailman.mit.edu/pipermail/kerberos/2023-April/022957.html , which proposed that we allow callers to modify the default profile in memory and pass that to krb5_init_context_profile().  The default profile could be empty, so we need …

Allow modifications of empty profiles

---

src/util/profile/prof_file.c

The profile library normally attempts to reload a profile data tree if the backing file has changed.  Reloading a dirty profile object discards any modifications made by the caller.  If we assume that the modifications are destined to be flushed back out to the backing file, then there is no good answer--one or the other set of changes will be lost.  But the caller may have a different intended use for the modified tree (profile_flush_to_file(), profile_flush_to_buffer(), krb5_init_context_profile()), for which the caller's modifications may be critical.

Do not reload a modified profile data object

---

src/util/profile/prof_file.c
src/util/profile/prof_init.c
src/util/profile/prof_int.h
src/util/profile/prof_tree.c
src/util/profile/profile.hin
src/util/profile/t_profile.c

Replace the current implementation of profile_copy() with one that copies the in-memory tree structure of non-shared data objects.  Make profile_copy() a public function.

Make profile_copy() work on dirty profiles

---

doc/admin/conf_files/krb5_conf.rst
doc/admin/realm_config.rst
src/include/k5-int.h
src/lib/krb5/os/dnssrv.c
src/lib/krb5/os/locate_kdc.c
src/lib/krb5/os/os-proto.h

Add support for specifying a sitename in krb5.conf that can be used for DNS-based KDC discovery using SRV or URI RR queries for q-names of the form _kerberos._udp.${sitename}._sites.${realm}.

Support site-local KDC discovery via DNS

---

src/util/profile/final6.ini
src/util/profile/prof_parse.c

When parsing a "}", do not ascend to the parent node if we are still within a discarded section after decrementing group_level, as we did not descend into a child node at the beginning of the subsection. (Discovered by OSS-Fuzz.)
Also adjust the level check to take into account the shifted meaning of state->group_level, so that we properly reject a "}" within a top-level section.
Both bugs were introduced in commit
f951625e6bd3ff44f1056958b56e35a1a043e362.

Fix recently-introduced profile parsing bugs

---

doc/admin/realm_config.rst

Commit 10eb93809b1af06e2b1147aee2e3e50058ba1bbd introduced a formatting error in the SRV record descriptions.  Fix it now.

Fix formatting error in realm_config.rst

---

src/lib/gssapi/krb5/iakerb.c

RFC2744 about gss_init_sec_context states:
Initially, the input_token parameter should be specified either as GSS_C_NO_BUFFER, or as a pointer to a gss_buffer_desc object whose length field contains the value zero.

gssapi:iakerb: Do not fail if we have an initial empty buffer

---

.github/workflows/cifuzz.yml

Continuing the fuzzing integration: https://github.com/krb5/krb5/pull/1346.
Adding [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for checking build failures and PR fuzzing.
Using the main [example](https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/example_cifuzz.yml) provided by the OSS-Fuzz team, with an updated time of only 300 seconds.

Add cifuzz workflow for PR fuzzing

---

src/lib/krb5/ccache/cc_file.c

In the FILE ccache, consider a cred to be removed if it has endtime 0 and authtime non-zero, instead of specifically authtime -1.  This change will let us filter out normal credentials deleted by Heimdal, although not synthetic credentials such as config entries.

Adjust removed cred detection in FILE ccache

---

src/include/krb5/krb5.hin
src/lib/krb5/krb/get_creds.c

Historically, krb5_get_credentials() uses in_creds->times.endtime both as the TGS request endtime and as a cache lookup criterion.  These uses are in conflict; setting a TGS request endtime can only serve to limit the maximum lifetime of the issued ticket, while a cache lookup endtime limits the minimum lifetime of an acceptable cached ticket. The likely outcome is to never use a cached credentials, leading to poor performance as we add an entry to the cache for each request.
Switch to the Heimdal behavior of using in_creds->times.endtime only as the TGS request endtime.

Change krb5_get_credentials() endtime behavior

---

doc/appdev/refs/api/index.rst
src/include/k5-int.h
src/include/krb5/krb5.hin

Add krb5_get_default_config_files() to the public API; it was already in the library export list and the DLL export list.  Also add krb5_free_config_files().
[See also https://krbdev.mit.edu/rt/Ticket/Display.html?id=9130 ]

Make krb5_get_default_config_files() public

---

.gitignore
src/lib/gssapi/krb5/iakerb.c
src/tests/gssapi/Makefile.in
src/tests/gssapi/t_gssapi.py
src/tests/gssapi/t_iakerb.c

@abbra mentioned IAKERB realm discovery in PR #1335.   https://datatracker.ietf.org/doc/html/draft-ietf-kitten-iakerb-03#section-3.1 says:
```
A client using IAKERB may not have any realm information, even for
the realm of the client's host, or may know that the client host's
realm is not appropriate for a given enterprise principal name.  In
such cases, the client can retrieve the realm of the GSS-API acceptor
as follows: the client returns GSS_S_CONTINUE_NEEDED with the output
token containing an IAKERB message with an empty target-realm in the
IAKERB-HEADER and no Kerberos message following the IAKERB-HEADER
structure.  Upon receipt of the realm request, the GSS-API acceptor
fills out an IAKERB_PROXY response message, filling the target-realm
field with the realm of the acceptor, and …
```

Add acceptor-side IAKERB realm discovery

---

.github/workflows/build.yml

I read a few Red Hat blog posts about FORTIFY_SOURCE, and it seems like an easy thing to add to our CI, if only because Fedora is using it in package builds.  It doesn't currently seem to find anything that we haven't already ironed out with asan.

Add fortify flag to gcc CI build

---

src/include/k5-der.h
src/lib/gssapi/generic/gssapiP_generic.h
src/lib/gssapi/generic/util_token.c
src/lib/gssapi/krb5/accept_sec_context.c
src/lib/gssapi/krb5/iakerb.c
src/lib/gssapi/krb5/init_sec_context.c
src/lib/gssapi/krb5/k5unseal.c
src/lib/gssapi/krb5/k5unsealiov.c
src/lib/gssapi/mechglue/g_decapsulate_token.c
src/lib/gssapi/mechglue/g_glue.c
src/lib/gssapi/mechglue/mglueP.h

[This is kind of a minimum viable refactor to clean up the code duplication added in the recent security commit.  I would like to do a more complete refactor of the per-token processing functions, but may not be able to finish that.]
Rewrite g_verify_token_header() to use k5input and to not handle two-byte token IDs.  Add a more general g_get_token_header() which can handle detached wrappers and cases where the mech is not known in advance.  Adjust all current callers, and get rid of the duplicate DER parsing code added in commit b0a2f8a5365f2eec3e27d78907de9f9d2c80505a.
In k5-input.h, split out tag and length parsing into k5_der_get_taglen(), needed by g_get_token_header().

Refactor GSS token header parsing

---

src/util/k5test.py

Commit 1b57a4d134bbd0e7c52d5885a92eccc815726463 made the KDC stop issuing des3 and rc4 session keys by default.  To make the des3 and arcfour passes of the test suite work, it added aes256-sha1 to the permitted enctypes for those passes.  Negotiating AES session keys reduces coverage of pre-CFX GSSAPI code and other uses of the older enctypes.  Instead set the enable_des3 and enable_rc4 variables.

Restore test coverage for old session key types

---

src/lib/krb5/os/sendto_kdc.c

Edit the block comment above k5_sendto() to take into account commits 802318cda963456b3ed7856c836e89da891483be (which added request_timeout) and 6436a3808061da787a43c6810f5f0370cdfb6e36 (which made the open TCP connection wait indefinite).

Update k5_sendto() comment

---

src/windows/installer/wix/lang/ui_1033.wxi

Windows installers must provide a FilesInUse dialog, with the intent of minimizing the need to restart the system after software installations.  For reasons related to the LSA cache, the KfW installer always schedules a post-installation reboot (see commit 50a3c3cbeab32577fba2b21deb72a64015c48ec7).  Reword the FilesInUse dialog text to recommend clicking Ignore, causing the conflicting files to replaced on the reboot.  (The affected files are likely C runtime DLLs, and the existing versions will almost certainly suffice if KfW programs are run prior to a reboot.)

Replace Windows installer FilesInUse dialog text

---

src/aclocal.m4
src/config/shlib.conf
src/include/k5-platform.h
src/lib/win_glue.c

In this PR I want to consider approaches to minimizing the chance of k5_mutex_lock() assertion errors at process exit.  These happen when a krb5 or GSS library function that uses a singleton mutex (like cc_typelist_lock)I is called after library finalization.  I believe we have seen that in the past due to platform bugs with unloading order; recently @nicowilliams stated in a Rust issue that he sees it happen when a multithreaded program exits the process from one thread while another thread is still working.  I don't think we can make that scenario truly safe, but we can probably squash the problem in practice.
Candidate solutions:
1. In the Rust issue, Nico suggested we not destroy mutexes in library finalizers, saying that there is "zero value in doing so".  While that's true for …

Minimize mutex assertion errors at process exit

---

src/lib/krb5/os/c_ustime.c

in `krb5_crypto_us_timeofday()`
Condition is expected to check for "microseconds are moving backwards" but actual code checks an opposite thing:
!ts_after(last_time.usec, now.usec) => !(last_time.usec > now.usec)
=> last_time.usec <= now.usec
This results in ts always being forced to `ts_incr(last_time.usec, 1)` within same second.
Can be illustrated by following strace example:
```
11:12:52.734330 write(32, "... [15981] 1727950372.024394: SPAKE challenge received ...", 233) = 233
11:12:52.909504 getrandom("...", 32, 0) = 32
11:12:52.936009 getpid()                = 15981
11:12:52.995094 write(32, "... [15981] 1727950372.024395: SPAKE key generated ...", 219) = 219
```
- internal libkrb5 ts changed by 0.000001 when only between call to `getrandom()` (used in calculation of SPAKE key) and …

Fix wrong detection of moving backwards microseconds

---

src/include/k5-int.h
src/lib/krb5/os/c_ustime.c
src/lib/krb5/os/trace.c

Logger doesn't need unique timestamps, so expensive mutex lock within krb5_crypto_us_timeofday() makes logger slower for no reason.
New helper - krb5int_us_timeofday() - is merely a wrapper around existing get_time_now() and doesn't need to be exported. A wrapper looks better than pulling 'struct time_now' to a header.

Avoid using locking krb5_crypto_us_timeofday() in krb5int_trace()

---

.github/workflows/cifuzz.yml
.github/workflows/doc.yml

Increment the versions of the upload actions in doc.yml and cifuzz.yml as documented in:
https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/ https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Also fix the conditional in cifuzz.yml to react to changes in itself, not in build.yml.

Update upload action versions in CI scripts

---

src/config/shlib.conf

Remove the handling of DEC OSF (last release in 1992), SINIX (1995), AIX 4 (1999), BSD/OS (2003), and IRIX (2006).

Remove ancient platforms from shlib.conf

---

src/lib/krb5/krb/pac.c
src/util/profile/prof_parse.c

First: https://github.com/krb5/krb5/commit/3911709d968926659ead530a08aaa2bbce640f01
While it is not an issue for fuzz_profile to handle non-existent paths or directories and return an error, when I was looking at code coverage reports https://github.com/google/oss-fuzz/issues/12282, I think there is a problem with the coverage sanitizer.
Second and Third: https://github.com/krb5/krb5/commit/9cbcbf451a8cbebb0e6a41da9816ca562d176d97 https://github.com/krb5/krb5/commit/7fc776398eca8bc8cc1931f762033c85d60d1993
These are new bugs that form PR https://github.com/krb5/krb5/pull/1366
I am making a separate PR, because I think my last PR is bloated.
Reproduce:
```bash
./tests/fuzzing/fuzz_pac leak-e5067f20c8a4c43c783ed8e754fb4608e12cd6ac.zip
./tests/fuzzing/fuzz_pac …
```

Profile: Enable OSS-Fuzz build macro And  Fix: Pac memory leak & Off-by-one  

---

src/include/k5-int.h
src/lib/crypto/krb/checksum_hmac_md5.c
src/lib/crypto/libk5crypto.exports
src/lib/krad/attr.c
src/lib/krad/attrset.c
src/lib/krad/internal.h
src/lib/krad/packet.c
src/lib/krad/t_attrset.c
src/lib/krad/t_daemon.py
src/lib/krad/t_packet.c
src/tests/t_otp.py

[draft-ietf-radext-deprecating-radius-03](https://datatracker.ietf.org/doc/html/draft-ietf-radext-deprecating-radius-03) describes multiple mitigation measures for recent vulnerabilities discovered in the RADIUS protocol, especially the [BlastRADIUS](https://www.blastradius.fail/attack-details) one (CVE-2024-3596). One of them is the enforcement of the `Message-Authenticator` attribute.
`Message-Authenticator` was initially defined in [RFC2869](https://datatracker.ietf.org/doc/html/rfc2869) (2000) as an extension to improve authenticity and integrity verification.
However the BlastRADIUS vulnerability is now pushing vendors to generalize the use of this attibute. FreeRADIUS is now enforcing `Message-Authenticator` since versions 3.2.5 and 3.0.27. `libkrad` has to support …

libkrad: Add Message-Authenticator support

---

src/lib/gssapi/generic/Makefile.in
src/lib/gssapi/generic/deps
src/lib/gssapi/generic/util_errmap.c

Some of the peripheral libgssapi_krb5 utility functions, such as gss_str_to_oid(), do not access the mechanism list and therefore do not reach any of the current calls to
gssint_mechglue_initialize_library().  If one of these functions is called early and produces an error, its call to map_error() will operate on the uninitialized error map.  When the library is later initialized, any entries added to the error map this way will be leaked.
Add library initialization calls to gssint_mecherrmap_map() and gssint_mecherrmap_get() to ensure that the error map is initialized before it is operated on.

Prevent late initialization of GSS error map

---

src/lib/crypto/krb/make_checksum_iov.c
src/lib/crypto/krb/verify_checksum_iov.c

Null keyblocks are allowed by the libk5crypto checksum functions when the checksum type is not keyed.  However, krb5_c_make_checksum_iov() and krb5_c_verify_checksum_iov() crash on null keyblock inputs because they do not check before converting to krb5_key as their non-IOV variants do.  Add the null checks.
[Prompted by a comment by @jrisc in one of the libkrad PR threads]

Allow null keyblocks in IOV checksum functions

---

src/configure.ac
src/lib/crypto/krb/prng.c

When available, use getentropy() in preference to SYS_getrandom or /dev/urandom.  This binding is present in glibc 2.25 and the BSDs.

Use getentropy() when available

---

src/lib/krb5/asn.1/asn1_k_encode.c

In the statement "f |= bits[i] << (8 * (3 - i))", bits[i] is implicitly promoted from uint8_t to int according to the integer promotion rules (C99 6.3.1.1).  If i is 0 and bits[i] >= 128, the result cannot be represented as an int and the behavior of the shift is undefined (C99 6.5.7).  To ensure that the shift operation is defined, cast bits[i] to uint32_t.
(f and the function output are int32_t, but the conversion of uint32_t to int32_t is implementation-defined when the value cannot be represented, not undefined.  We check in configure.ac that the platform is two's complement.)

Prevent undefined shift in decode_krb5_flags()

---

src/plugins/preauth/securid_sam2/securid2.c

It turns out the SecurID SDK no longer provides sdi_athd.h, so remove our include of it.

Remove missing SecurID header file

---

src/configure.ac
src/lib/crypto/krb/prng.c

The function getentropy() is supported on newer versions of MacOS X, but requires the include file sys/random.h.  Check for that and include it where getentroy() is used.

Check for sys/random.h

---

src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap_conn.c

The function "initialize_server" leads to memory leak when the function "authenticate" returns non-success.
We forget to free the memory of "server->ldap_handle".
We should free "server->ldap_handle" before we free "server".

Fix the memory leak issue when Kerberos fails to connect to OpenLDAP.

---

src/lib/krb5/os/dnssrv.c

Commit d035119c3b2 introduced an extra argument to the function k5_make_uri_query(), but did not add that argument to the Windows stub version of this function; that ended up causing an exception when this function was called due to a null pointer dereference.  I do not know why this didn't trigger even a warning during compilation, much less an error.

Fix Windows regression in k5_make_uri_query()

---

src/clients/ksu/heuristic.c
src/clients/ksu/main.c
src/kadmin/server/ovsec_kadmd.c
src/kdc/main.c
src/kprop/kpropd.c
src/lib/crypto/krb/make_checksum.c
src/lib/crypto/krb/make_checksum_iov.c
src/lib/crypto/krb/verify_checksum_iov.c
src/lib/gssapi/generic/oid_ops.c
src/lib/gssapi/mechglue/g_oid_ops.c
src/lib/gssapi/mechglue/mglueP.h
src/lib/gssapi/spnego/spnego_mech.c
src/lib/krb5/krb/ser_actx.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/util/profile/prof_tree.c

In k5_externalize_auth_context(), serialize the correct field when remote_port is set.  This is not a reachable bug because the function is only accessible via gss_export_sec_context(), and the GSS library does not set a remote port.
In generic_gss_oid_to_str(), remove an inconsistently-applied test for a null minor_status.  Also remove minor_status null checks from generic_gss_release_oid() and generic_gss_str_to_oid(), but add output initializations and pointer checks to the API functions in g_oid_ops.c in a similar manner to other GSSAPI functions.  Remove gssint_copy_oid_set() and replace its one call with a call to generic_gss_copy_oid_set().
In the checksum functions, avoid crashing if the caller passes a null key and checksum type 0.  An error will be returned instead when …

Fix minor logic errors

---

src/lib/gssapi/mechglue/Makefile.in
src/lib/gssapi/mechglue/deps
src/lib/gssapi/mechglue/mglueP.h

The functions in g_mechname.c have been unused since release 1.5. Remove the file.

Remove unused GSS mechglue source file

---

src/ccapi/lib/win/Makefile.in
src/config/win-pre.in
src/windows/kfwlogon/Makefile.in
src/windows/kfwlogon/kfwcommon.c
src/windows/kfwlogon/kfwlogon.c
src/windows/kfwlogon/kfwlogon.def
src/windows/kfwlogon/kfwlogon.h

Remove the explicit use of the -entry flag to specify a DLL entry point on Windows; this is no longer recommended.  The default Windows entry point will call a DllMain function if one is provided; make sure we provide when necessary.

Remove explicit use of -entry flag for DLLs on Windows

---

.github/workflows/build.yml
src/lib/krb5/krb/x-deltat.y
src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.c
src/tests/asn.1/krb5_decode_test.c
src/tests/asn.1/krb5_encode_test.c
src/tests/asn.1/ktest.c
src/tests/asn.1/ktest.h
src/tests/hammer/kdc5_hammer.c

Github is transitioning the ubuntu-latest image from 22.04 to 24.04, which means our CI jobs sometimes run on one and sometimes on the other.
Most of the changes here are simple fixes to problems that previous escaped the various nets we've cast around them.  I am currently a bit stymied by an asan problem.  When asan has something to report, it tries to use llvm-symbolizer and fails with an error like:
```
/usr/bin/llvm-symbolizer-18: symbol lookup error: /home/runner/work/krb5/krb5/src/./lib/libkrb5support.so.0: undefined symbol: __asan_option_detect_stack_use_after_return
5131
==29597==WARNING: Can't read from symbolizer at fd 3
5132
```
In some cases this appears to cause the program to exit with status -13 (SIGPIPE).  Usually this is just a minor hindrance to analyzing a problem we …

WIP: Fix CI errors on Ubuntu 24.04

---

src/lib/gssapi/krb5/acquire_cred.c

This fix is just about code sanity.
In case the `cred_store` type is `KRB5_CS_PASSWORD_URN` and the `desired_name` is not set, its value is tested twice while the first test sends the program counter to the end of the function.
This commit removes the second test, because it cannot be true.

Remove redundant test in acquire_cred_from()

---

.github/workflows/build.yml
src/Makefile.in
src/tests/t_kdb.py
src/util/k5test.py

On some platforms llvm-symbolizer is linked against libcurl, which depends on the krb5 libraries.  When the test suite runs programs with LD_LIBRARY_PATH pointed at asan-compiled krb5 libraries, llvm-symbolizer will encounter a dynamic linker error at startup, interfering with the display of stack traces.
In k5test.py, when the build enables asan, wrap the platform's symbolizer in a script that unsets LD_LIBRARY_PATH (or similar) and then runs the real llvm-symbolizer.
[I thought of this workaround for the symbolizer problem described in PR #1404, and it appears to work without requiring major changes to the build system.  Unfortunately, fixing it revealed another detected leak in t_kdb.py.  I'm not sure this leak is ours, since the allocations occur inside a call to …

Work around llvm-symbolizer LD_LIBRARY_PATH issue

---

.gitignore
doc/admin/admin_commands/kadmind.rst
doc/admin/admin_commands/krb5kdc.rst
src/include/socket-utils.h
src/kdc/Makefile.in
src/kdc/deps
src/kdc/t_sockact.c
src/kdc/t_sockact.py
src/lib/apputils/net-server.c

This adds support for systemd socket activation.
See https://0pointer.de/blog/projects/socket-activation.html
This requires PR #1359 to be merged first.

Add support for systemd socket activation

---

src/lib/kdb/kdb_cpw.c

In the default libkdb5 password change method, omit requested key/salt combinations that duplicate an earlier encryption type, even if they have a different salt type.  Any use cases for multiple salts for the same enctype disappeared with single-DES support.  (We already have this behavior for chrand requests.)

Allow only one salt type per enctype in key data

---

src/include/kdb_log.h
src/kprop/kproplog.c
src/lib/kdb/kdb_log.c
src/tests/t_iprop.py

Increase ulog blocksize transparently instead of setting a larger value and reinitializing the log. Log reinitialization triggers a full resync, which is ineffective with bigger databases and large number of key versions.
Eventually we experienced full resync loops in hierarchical incremental propagation, which might be caused by a race condition in the replication process and loading large databases. Turning the ulog resizing immediate eliminated this issue.
**Legal**
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE MIT LICENSE. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://opensource.org/licenses/MIT.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF …

Improve ulog resizing

---

doc/formats/cookie.rst
doc/formats/database_formats.rst
doc/formats/index.rst

Add a new file under doc/formats documenting the dump format, tl-data formats, alias principals, and the DB2 and LMDB principal and policy formats.
Also correct some formatting in cookie.rst, changing a nested list to a code block for consistency with other documentation of binary formats.
[I plan to merge this after PR #1393 as it discusses alias entries.  But I'm keeping it in a separate PR since the majority of it is unrelated.]

Add database format documentation

---

.github/workflows/build.yml
src/Makefile.in
src/config/win-pre.in
src/include/win-mac.h
src/lib/krb5_32.def
src/plugins/preauth/pkinit/Makefile.in
src/plugins/preauth/pkinit/pkinit.def
src/plugins/preauth/pkinit/pkinit.h
src/plugins/preauth/pkinit/pkinit_accessor.c
src/plugins/preauth/pkinit/pkinit_accessor.h
src/plugins/preauth/pkinit/pkinit_clnt.c
src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
src/plugins/preauth/pkinit/pkinit_identity.c
src/plugins/preauth/pkinit/pkinit_matching.c
src/windows/README
src/windows/installer/wix/config.wxi
src/windows/installer/wix/features.wxi
src/windows/installer/wix/files.wxi
src/windows/installer/wix/platform.wxi

These changes implement support for the PKINIT plugin on Windows platforms
This has been split into two parts: the aforementioned std::regex glue code for Windows platforms and the actual building of the PKINIT plugin.
The ```std::regex``` changes were as discussed previously, except that the question I posed on ```krbdev``` regarding specifying the ```-entry:DllMain``` option was never answered. My solution here is to remove this for building the krb5 DLLs; since the system default DLL entry point automatically calls ```DllMain``` if one is provided, it seems like this isn't necessary and things seem to work fine (you get unknown symbols when building the DLL otherwise). The use of ```-entry``` for building the CCAPI DLL and KFWLogin DLL has not been changed, but probably should be …

Add support for PKINIT on Windows

---

src/util/support/plugins.c

Use k5_path_join() to create pathnames in the function krb5int_open_plugin_dirs() for Windows compatibility.

Use k5_path_join() in krb5int_open_plugin_dirs()

---

src/clients/klist/klist.c

Active Directory domain controllers such as Microsoft AD and Samba are including a NetBIOS name in list of client addresses.
Currently when using `klist` NetBIOS names are displayed as `unknown addrtype`.

Add NetBIOS name support when displaying ticket addresses

---

src/appl/gss-sample/t_gss_sample.py
src/lib/gssapi/krb5/iakerb.c

A regression in commit e04f0283516e80d2f93366e0d479d13c9b5c8c2a leads to iakerb_gss_init_sec_context() returning successfully with *context_handle still set to null, in the case where no IAKERB steps are necessary.  Subsequent GSS calls using this context will dereference a null pointer and crash.
Fix this bug by moving the *context_handle assignment to the cleanup handler, alongside the code to clean up new contexts on error.
[ghudson@mit.edu: moved fix to cleanup handler to avoid code duplication; rewrote commit message]

Fix IAKERB accept_sec_context null pointer crash

---

src/lib/gssapi/krb5/iakerb.c
src/tests/gssapi/t_gssapi.py

KRB-ERROR has non-optional realm and sname fields, so we must set a server field in the krb5_error object before calling krb5_mk_error().
Add KRB-ERROR processing to the initiator state machine.

Fix IAKERB error handling

---

src/lib/gssapi/krb5/iakerb.c
src/tests/gssapi/t_gssapi.py

This is similar to the acceptor step which handles this correctly already. Else we return an error for NEED_PREAUTH ...

gssapi: Only handle IAKerb errors in initiator step

---

src/plugins/kdb/ldap/libkdb_ldap/kdb_ldap.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c

The LDAP KDB module synthesizes KRB5_TL_CONSTRAINED_DELEGATION_ACL tl-data when fetching a principal entry, and checks against those values in krb5_ldap_check_allowed_to_delegate().  To avoid a locally incorrect use of a counted data type, adjust the synthesized attributes to include the trailing zero byte in tl_data_length, and verify the zero terminator before calling krb5_parse_name() on the value.

Fix correctness in LDAP delegation ACL checking

---

src/include/kdb.h
src/kadmin/server/server_stubs.c
src/lib/kadm5/admin.h
src/lib/kadm5/clnt/client_principal.c
src/lib/kadm5/srv/svr_principal.c
src/lib/kdb/kdb_cpw.c
src/tests/t_keyrollover.py

In libkadm5, change the type of the keepold parameters from krb5_boolean to unsigned int (which is the underlying type of krb5_boolean, so this is not an API or ABI change).  In libkadm5srv, interpret a keepold value greater than 2 to be a limit on the number of resulting key versions including the new one.
In kadmind, when a principal changes its own keys, limit the number of resulting key versions to 5.

Limit -keepold for self-service key changes

---

src/kdc/t_sockact.c
src/lib/apputils/net-server.c

Our CI recently started failing on an invocation of kdc/t_sockact.c.  In create_socket(), we try to set SO_REUSEPORT on a UNIX domain socket and get back EOPNOTSUPP, causing an abort.  We also set SO_REUSEPORT on UNIX domain sockets in net-server.c, but failures just lead to a log message (which can be found in testdir/kdc.log after running t_sendto_kdc.py with an affected kernel version).
I found https://github.com/python/cpython/issues/128916 which linked to the kernel commit https://github.com/torvalds/linux/commit/5b0af621c3f6ef9261cf6067812f2fd9943acb4b .  I don't think the kernel behavior change makes sense, but litigating it here doesn't serve any purpose, so I'll move on to workarounds.
We set SO_REUSEADDR so that a recently stopped KDC process won't get in the way of a new one …

Remedy CI failure [WIP]

---

src/kadmin/dbutil/kdb5_util.c

Avoid passing NULL to krb5_string_to_keysalt() in add_random_key(). When add_random_key() was first written, krb5_string_to_keysalts() did nothing on a null string input.  After commit
3576bd662be9b7cc2cca97065fe467e745542b69 it calls strdup(NULL) and crashes.

Fix kdb5_util ark with no -e option

---

doc/admin/conf_files/krb5_conf.rst

Document that PKINIT identity specifier values must not contain colons.
[See https://krbdev.mit.edu/rt/Ticket/Display.html?id=9154 ]

Clarify X509_user_identity documentation

---

src/lib/krb5/os/dnsglue.c

When the TXT-DATA value returned by DNS is empty, it causes the program to crash. 
This fix adds fault tolerance to prevent the program from crashing in such cases.

Implement fault tolerance for empty TXT record strings

---

src/lib/krb5/krb/get_in_tkt.c
src/lib/krb5/krb/init_creds_ctx.h
src/lib/krb5/krb/preauth2.c

I've run across an unexpected behavior with SPAKE in MIT Kerberos 1.21.3, which may be a bug. It occurs when some KDCs have SPAKE enabled (by setting `spake_preauth_groups`), while it is off in other KDCs for the same realm. Consider:
KDC A has:
```
[libdefaults]
spake_preauth_groups = edwards25519
[kdcdefaults]
spake_preauth_kdc_challenge = edwards25519
```
while KDC B has both unset. Suppose that the only other supported preauthentication mechanism is encrypted-timestamp. The following can occur with client C:
```
C -> A : AS-REQ
A -> C : KRB5KDC_ERR_PREAUTH_REQUIRED + SPAKE challenge
C -> B : AS-REQ with SPAKE response
B -> C : KRB5KDC_ERR_PREAUTH_REQUIRED (because B does not support SPAKE)
```
At this point the client should stop: it has replaced the reply key as part of sending the …

libkrb5: fix client preauth handling of fallback_disabled

---

src/Makefile.in
src/configure.ac
src/plugins/kdcpolicy/xrealmauthz/Makefile.in
src/plugins/kdcpolicy/xrealmauthz/deps
src/plugins/kdcpolicy/xrealmauthz/main.c
src/plugins/kdcpolicy/xrealmauthz/xrealmauthz.exports
src/tests/Makefile.in
src/tests/t_xrealmauthz.py

This PR introduces a new KDC policy plugin (xrealmauthz) that provides fine-grained authorization control for cross-realm authentication in MIT Kerberos. The plugin allows administrators to explicitly authorize which realms and/or principals can obtain cross-realm TGT to access services across realm boundaries, enhancing security in multi-realm Kerberos deployments.
**Changes
New plugin: xrealmauthz**
- Implements the kdcpolicy plugin interface to intercept and authorize cross-realm TGS requests
- Provides two levels of authorization:
- Support for both direct and transitive trust
- Realm-based: Authorize all principals from a specific realm
- Principal-based: Authorize specific principals
- Configurable enforcing/monitoring modes via xrealmauthz_enforcing kdc.conf setting
- Optional …

Add xrealmauthz KDC policy plugin for cross-realm authorization

---

src/plugins/kdb/ldap/libkdb_ldap/ldap_krbcontainer.h
src/plugins/kdb/ldap/libkdb_ldap/ldap_misc.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_pwd_policy.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_realm.c
src/plugins/kdb/ldap/libkdb_ldap/ldap_tkt_policy.c
src/tests/t_kdb.py

In case policy = NULL, program goes to cleanup and NULL-dereference happens. Return without goto to avoid it.

kdb/ldap: fix error handling in krb5_ldap_read_policy()

---

src/include/krb5/krb5.hin
src/lib/krb5/os/changepw.c

For krb5_change_password(), krb5_set_password(), and krb5_set_password_using_ccache(), document that result_code_string may be NULL and that the caller should free result_code_string and result_string with krb5_free_data_contents().  Also ensure that result_code_string and result_string are initialized along all exit paths.  Reported by Joonas Tuomisto.

Improve password change API docs and behavior

---

src/util/profile/prof_file.c

We ([ClickHouse](https://github.com/ClickHouse/ClickHouse/)), carried this small patch in our krb5 fork around since two years and we like to upstream it. It addresses an issue found by [tsan](https://clang.llvm.org/docs/ThreadSanitizer.html). I unfortunately did not find an associated original error report (e.g. crashdump), so I can't tell you more information. My kind ask would be that you double-check and suggest improvements to this fix, thanks.

Fix TSan report in Kerberos

---

src/config/lib.in
src/config/libnover.in
src/config/shlib.conf
src/include/k5-platform.h

from the manpage of `ld(1)`:
```
-B bind        Select run-time binding behavior of a program
using shared libraries or the binding preference
in building a shared library.  The most common
values for bind are:
nodelete   Mark the shared library so that an
explicit unload using dlclose() or
shl_load() returns success silently
without detaching the shared library
from the process.  Subsequently, the
shared library handle is valid only for
shl_findsym().  It stays invalid for
dlsym(), dlclose(), and shl_unload()
until the next explicit load using
shl_load() or dlopen().
```

Bind shared libraries to programs with 'nodelete' on HP-UX

---

src/tests/t_authdata.py
src/util/k5test.py

Tests rely on behavior of GNU getopt wich is by default non POSIX-compliant and accepts optional and positional arguments in any order. This can be enforced by setting the environment variable POSIXLY_CORRECT. Other platforms like FreeBSD or HP-UX will fail the test.

Fix argument order in t_authdata.py

---

src/plugins/kdb/db2/libdb2/test/Makefile.in
src/plugins/kdb/db2/libdb2/test/run.test

@michael-o for testing
Pursuant to https://mailman.mit.edu/pipermail/kerberos/2025-September/023292.html , I set up an environment where "awk" from the path fails, and ran through make and make check.  The only problem I ran into was the libdb2 test script.  This PR makes that script use the autoconf-selected awk command.

Use configured awk in libdb2 tests
