- src/Makefile.in
- src/config/pre.in
- src/kadmin/testing/util/Makefile.in
- src/lib/krb5/ccache/t_cccol.py
- src/lib/krb5/os/Makefile.in
- src/lib/rpc/unit-test/Makefile.in
- src/tests/dejagnu/Makefile.in
- src/tests/t_ccache.py
- src/tests/t_kdb.py
- src/tests/t_otp.py
- src/tests/t_pkinit.py
- src/tests/t_proxy.py
- src/tests/t_sn2princ.py
- src/util/k5test.py
The first two commits on this branch implement the idea I had for reporting skipped tests at the end of "make check".  The third commit is some t_pkinit.py cleanup for some issues I noted when modifying t_pkinit.py in the second commit.
> Skipped test reporting

- src/Makefile.in
- src/configure.in
- src/plugins/kdb/test/Makefile.in
- src/plugins/kdb/test/kdb_test.c
- src/plugins/kdb/test/test.exports
- src/tests/gssapi/t_s4u.py
The first commit adds a new test KDB module.  The second commit uses the module to add successful S4U2Proxy delegation tests.
> Test KDB module and S4U2Proxy tests

- src/kdc/do_tgs_req.c
The CAMMAC authorization data container requires a checksum over the
encrypted part of the issued ticket, with the CAMMAC contents
substituted for the authdata field.  For this to work, we must
finalize the non-authdata fields of the encrypted ticket part before
adding authdata.  Call handle_authdata() after checking and modifying
the transited field and potentially setting the
transited-policy-checked flag.
Also remove a redundant and inoperative conditional change to
enc_tkt_reply.times.starttime which happens after the ticket is
encrypted.  We do the same thing right after setting up the ticket
times.
> Process TGS authdata after transited in KDC

- src/tests/t_kdb.py
Augment the LDAP KDB module tests to include client principal aliases
as well as server principal aliases.  Also revise the server principal
alias tests to include an AS-REQ case.  (This requires adjusting the
subsequent test not to assume a ccache containing a TGT.)
> Add tests for client principal aliases

- src/kadmin/dbutil/dump.c
- src/tests/t_dump.py
Ticket #7223 added new policy fields and a new dump format version to
marshal them, but did not add a new iprop dump format.  As a result,
slave KDCs running 1.11 or later cannot receive full resyncs from
master KDCs running 1.10 or earlier.
Retroactively add support for pre-1.11 policy entries by making
process_r1_11_policy() read the first ten fields, check whether the
next whitespace character is a newline, and then read the rest.
> Fix compatibility with pre-1.11 iprop dumps

- src/appl/gss-sample/gss-server.c
- src/appl/gss-sample/t_gss_sample.py
- src/lib/gssapi/krb5/gssapi_krb5.c
- src/lib/gssapi/mechglue/g_acquire_cred.c
- src/lib/gssapi/mechglue/g_mechattr.c
- src/lib/gssapi/spnego/spnego_mech.c
This pull request addresses issue #8021, limiting the use of IAKERB by applications which do not explicitly ask for it.
> Limit use of IAKERB

- src/lib/gssapi/spnego/spnego_mech.c
- src/tests/gssapi/t_spnego.c
One of the features added in 1.7 was support for NegTokenInit2 messages contaning NegHints values.  These tokens are sent by the acceptor in response to a completely empty token from the initiator.  While investigating the SPNEGO code for PR #318, I realized that we have no test coverage for NegHints, and that it's a fair amount of code in several different places (in the mechglue to route empty tokens in SPNEGO, in the SPNEGO code which calls acc_ctx_hint(), and in make_spnego_tokenInit_msg()).  I also noticed that our code is going to somewhat heroic efforts to make up a name to put inside NegHints, when the MSDN spec and Heimdal have moved on to just inserting a dummy string there.  I wanted to fix those things sooner rather than later.
The first two commits on the branch are from PR …
> Correct SPNEGO NegHints hintName value and add test case

- src/Makefile.in
- src/config/pre.in
- src/config/shlib.conf
- src/kadmin/testing/scripts/env-setup.shin
- src/kdc/Makefile.in
- src/lib/crypto/builtin/des/Makefile.in
- src/lib/crypto/builtin/sha1/Makefile.in
- src/lib/crypto/builtin/sha2/Makefile.in
- src/lib/crypto/crypto_tests/Makefile.in
- src/lib/crypto/krb/Makefile.in
- src/lib/gssapi/generic/Makefile.in
- src/lib/kdb/Makefile.in
- src/lib/krad/Makefile.in
- src/lib/krb5/ccache/Makefile.in
- src/lib/krb5/keytab/Makefile.in
- src/lib/krb5/krb/Makefile.in
- src/lib/krb5/os/Makefile.in
- src/plugins/preauth/pkinit/Makefile.in
- src/tests/Makefile.in
- src/tests/asn.1/Makefile.in
- src/tests/dejagnu/Makefile.in
- src/tests/gssapi/Makefile.in
- src/tests/misc/Makefile.in
- src/tests/resolve/Makefile.in
- src/tests/shlib/Makefile.in
- src/tests/threads/Makefile.in
- src/util/et/Makefile.in
- src/util/profile/Makefile.in
These four commits supersede PR #332 and also fix RT issue 8264.  The first three commits are intended for the release branch; the fourth is not.
> Fix some uses of installed files in the test suite

- src/include/k5-int.h
- src/lib/crypto/builtin/sha2/sha256.c
- src/lib/crypto/krb/crypto_int.h
- src/lib/crypto/libk5crypto.exports
- src/lib/crypto/openssl/Makefile.in
- src/lib/crypto/openssl/sha256.c
Add a simple private libk5crypto interface for computing SHA-256
hashes.
> Add internal SHA-256 interface

- src/kdc/do_tgs_req.c
I would have done these in a single commit, but Will submitted two different RT tickets for them already.
> Fix KDC memory leaks on requests with second tickets

- src/lib/gssapi/mechglue/g_inq_cred.c
[The diff is best viewed with "git diff -w"]
If the caller does not request a name, lifetime, or cred_usage when
calling gss_inquire_cred(), service the call by copying the mechanism
list (if requested) but do not call into the mech.
This change alleviates an issue where SPNEGO can fail in the presence
of expired krb5 credentials rather than proceeding with a different
mechanism, or can resolve a krb5 credential with the benefit of the
target name.
> Skip unnecessary mech calls in gss_inquire_cred()

- src/util/cstyle-file.py
For each file we check in cstyle-file.py, try to use emacs to
batch-reindent a copy of the file, and compare the resulting lines to
the input to detect indentation errors.
[PR commentary only:] Using emacs for this checking is kind of slow, because the emacs startup has to happen for every changed .c or .h file.  The layering of cstyle.py and cstyle-file.py doesn't make it easy to do multiple files in one emacs invocation.  It's still a lot faster to have a slow tool checking for these errors than to have a human notice it and give PR feedback.
We could alternatively use clang-format or indent, but I think we would have to change our coding practices to strictly conform to a configurable style in one tool or the other, or else they would generate a lot of false positives.  clang-format is …
> Add indentation checking to cstyle-file.py

- doc/user/tkt_mgmt.rst
> Fix typo in doc/user/tkt_mgmt.rst

- src/lib/krb5/os/locate_kdc.c
The most recent change to locate_srv_conf_1() introduced a possible
double-free bug (detected by Coverity), and also broke MS-KKDCP
support.  Separate the three uses of the "host" variable: the C string
copy of the realm name (now "realmstr"), the pointer to the hostname
or hostname:port specification in the profile values array (now
"hoststr"), and the hostname result of k5_parse_host_string() (still
"host").  Pass the correct pointer to k5_parse_host_string() if the
profile value is a URI.
> Fix bugs in recent locate_kdc.c change

- src/lib/krb5/os/sendto_kdc.c
PR #463 resulted from a buggy KDC recv hook, but a valid hook function could also trigger the uninitialized use of server_used.  Here is a fix.
> Fix use_master handling with KDC hook reply

- src/lib/krb5/krb/ai_authdata.c
Remove the authind_context count field.  The indicators list must be
null-terminated because it is freed with k5_free_data_ptr_list().
authind_internalize() didn't null-terminate the list, and the presence
of the count field made it appear that this wasn't a bug.  Use a
different scheme for setting *more in authind_get_attribute() to avoid
requiring an element count.
Also check more thoroughly for errors in authind_externalize() and
authind_internalize(), and remove some unnecessary pointer casts.
> Fix and simplify auth-indicator authdata module

- src/lib/kdb/kdb5.c
When the default realm name is unspecified, and none was set in the
krb5_context object, return KRB5_CONFIG_NODEFREALM from libkdb5
instead of the confusing KRB5_KDB_DBTYPE_NOTFOUND.  To accomplish
this, make kdb_get_library_name() return a krb5_error_code.
> Improve kdb5 error when default realm is unset

- src/configure.in
Delete trailing spaces at EOL.  Other whitespace issues remain for
now.
> Clean up some whitespace in configure.in

- src/include/k5-trace.h
Since it wasn't clear to Will, maybe we should add a comment.
> Comment why TRACE() is not used directly

- src/lib/krb5/os/lock_file.c
A bug in Gnu libc causes OFD locking to fail unpredictably on 32-bit
Linux, typically leading to deadlocks.  Work around this bug by using
the fcntl64 system call and struct flock64.
See also: https://sourceware.org/bugzilla/show_bug.cgi?id=20251
> Work around glibc OFD lock bug on 32-bit Linux

- doc/admin/admin_commands/kdb5_util.rst
- src/include/kdb.h
- src/kadmin/dbutil/dump.c
- src/plugins/kdb/db2/kdb_db2.c
- src/plugins/kdb/db2/libdb2/btree/bt_debug.c
- src/plugins/kdb/db2/libdb2/btree/bt_delete.c
- src/plugins/kdb/db2/libdb2/btree/bt_seq.c
- src/plugins/kdb/db2/libdb2/btree/extern.h
- src/plugins/kdb/db2/libdb2/include/db.hin
- src/plugins/kdb/db2/libdb2/libdb.exports
- src/plugins/kdb/db2/libdb2/mpool/mpool.c
- src/plugins/kdb/db2/libdb2/mpool/mpool.h
- src/plugins/kdb/db2/libdb2/test/btree.tests/main.c
- src/plugins/kdb/db2/libdb2/test/dbtest.c
- src/plugins/kdb/db2/libdb2/test/run.test
There's no automated test case for a KDB, but there is one for the lower layer libdb. Some of the bugfix commits could be squashed after review.
> Restore recursive dump

- src/util/k5test.py
When a k5test failure occurs, display the last executed command, its
command index, and its output.  This will make it easier to understand
"make check" failures when it is not easy to run subsequent commands
or investigate the filesystem of the build host.
> Output last command info on k5test failures

- src/prototype/prototype.c
- src/prototype/prototype.h
> Bump copyright years in src/prototype

- doc/appdev/refs/api/index.rst
- src/include/krb5/krb5.hin
- src/kadmin/dbutil/kadm5_create.c
- src/lib/kadm5/alt_prof.c
- src/lib/krb5/libkrb5.exports
- src/lib/krb5/os/sn2princ.c
- src/lib/krb5_32.def
- src/tests/t_sn2princ.py
This supersedes PR #333.
I have elected not to solve RT issue 8277 in this pull request, because solving that issue is complicated.
> Add and use krb5_expand_hostname()

- src/plugins/kdb/db2/kdb_xdr.c
In krb5_decode_princ_entry(), verify the length of the principal name
before calling krb5_parse_name() or strlen(), to avoid a possible
buffer read overrun.  Check all length fields for negative values.  If
the value of key_data_ver is unexpected, return KRB5_KDB_BAD_VERSION
instead of aborting.
> Improve checking of decoded DB2 principal values

- src/config/config.guess
- src/config/config.sub
ticket: 8489 (new)
tags: pullup
> Update config.guess, config.sub

- src/lib/krad/remote.c
In the previous code, when the remote peer performed an orderly shutdown
on the socket, libkrad would enter a state in which all future requests
timed out. Instead, if the peer shuts down its socket, we need to
attempt to reopen it.
> Properly handle EOF condition on libkrad sockets

- doc/admin/database.rst
In database.rst, describe a couple of krbtgt rollover issues and how
to avoid them.
> Add caveats to krbtgt change documentation

- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
decode_data() mixes errno values with OpenSSL return codes.  Change
its return type to int, and return 1 on success or 0 on failure.
> Fix error handling in PKINIT decode_data()

- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
[The first commit is from PR #580, which I submitted separately for Travis builds.]
In pkinit_crypto_openssl.c, fold decrypt_data() into its caller
pkinit_decode_data_fs(), and simplify its error-handling logic.
Initialize output parameters in pkinit_decode_data_pkcs11() and
pkinit_decode_data().
> Clean up PKINIT decode_data functions

- NOTICE
- README
- doc/conf.py
- doc/copyright.rst
- doc/notice.rst
- src/prototype/prototype.c
- src/prototype/prototype.h
- src/windows/version.rc
Update copyright years to 2017 where appropriate given the impending new year
> Update copyright years to 2017

- src/include/krb5/krb5.hin
- src/lib/krb5/krb/fwd_tgt.c
- src/lib/krb5/krb/mk_req.c
Some fixes for arguments which should be const.
> Some fixes for arguments which should be const

- src/configure.in
- Allows disabling of Native Language Support (NLS).
- Default is enabled to maintain current behavior.
> Add support for --(enable|disable)-nls to configure.

- doc/admin/host_config.rst
[In a recent admin/ops call, the topic of wanting multiple default realms came up, and I thought it might be helpful to document what the default realm does and how to override it in each case.  We are also missing prose documentation for local authorization, which is one of the chief behaviors affected by the default realm.  This PR contains documentation for both.]
Add documentation to host_config.rst describing what the default realm
does.  Also add documentation discussing login authorization
configuration, and give an example showing how to give login access to
principals from a realm other than the default realm.
> Document default realm and login authorization

- doc/appdev/gssapi.rst
Describe how a GSS application can perform S4U2Self and S4U2Proxy
requests using the MIT krb5 GSS library.  Also add a reference to RFC
7546 at the top, and fix a reference to gssapi_krb5.h.
> Add GSSAPI S4U documentation

- src/include/k5-trace.h
- src/lib/krb5/krb/get_in_tkt.c
- src/lib/krb5/krb/init_creds_ctx.h
- src/plugins/preauth/test/Makefile.in
- src/plugins/preauth/test/cltest.c
- src/plugins/preauth/test/common.c
- src/plugins/preauth/test/common.h
- src/plugins/preauth/test/deps
- src/plugins/preauth/test/kdctest.c
- src/tests/icred.c
- src/tests/t_general.py
- src/tests/t_pkinit.py
- src/tests/t_preauth.py
Here are the changes to improve our preauth framework fallback behavior, in four commits.
> Fall back to other preauth mechanisms after failures

- src/lib/krb5/os/sendto_kdc.c
In sendto_kdc:resolve_server() when resolving a server entry with a
specified transport, defer the resulting addresses if the strategy
dictates that the specified transport is not preferred.  Reported by
Jochen Hein.
> Fix udp_preference_limit with SRV records

- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
- src/plugins/preauth/pkinit/pkinit_identity.c
- src/plugins/preauth/pkinit/pkinit_matching.c
- src/plugins/preauth/pkinit/pkinit_srv.c
- src/plugins/preauth/pkinit/pkinit_trace.h
There may be some other pkiDebug() calls that would also be good for TRACE output, but these seemed to be the most useful for now.
> Convert some pkiDebug messages to TRACE macros

- doc/admin/realm_config.rst
> Fix realm_config.rst typo

- src/clients/kcpytkt/kcpytkt.c
- src/clients/kdeltkt/kdeltkt.c
- src/clients/kdestroy/kdestroy.c
- src/clients/kinit/kinit.c
- src/clients/kinit/kinit_kdb.c
- src/clients/klist/klist.c
- src/clients/kpasswd/kpasswd.c
- src/clients/kvno/kvno.c
Clients were refactored to more closely conform to the style and
formatting guide as specified in
http://k5wiki.kerberos.org/wiki/Coding_style
> Refactor clients to conform to the coding style

- src/po/Makefile.in
- src/po/de.po
We received a German translation by email to krbdev@mit.edu; this pull request adds it to the tree.
> Add German translation

- src/lib/gssapi/mechglue/g_glue.c
- src/tests/gssapi/t_invalid.c
gssint_get_mech_type_oid() is used by gss_accept_sec_context() to
determine the mechanism of the token.  Without length checking, it
might read a few bytes past the end of the input token buffer.  Add
length checking as well as test cases for truncated encapsulations.
Reported by Bar Katz.
> Length check when parsing GSS token encapsulation

- src/kdc/main.c
Same patch has been sent to [krbdev](http://mailman.mit.edu/pipermail/krbdev/2018-February/012900.html) few days ago from my Alexandr.Nedvedicky company email
> finish realm should free keys with 0 length too

- src/lib/krb5/ccache/cc_mslsa.c
Patch has been sent earlier from my alexandr.nedvedicky company email.
more details on [krbdev](http://mailman.mit.edu/pipermail/krbdev/2018-February/012902.html)
> KerbSubmitTicket() should check malloc() return for NULL

- .gitignore
- src/include/k5-hex.h
- src/kadmin/dbutil/deps
- src/kadmin/dbutil/tabdump.c
- src/kadmin/ktutil/deps
- src/kadmin/ktutil/ktutil_funcs.c
- src/lib/crypto/crypto_tests/deps
- src/lib/crypto/crypto_tests/t_cksum.c
- src/lib/crypto/crypto_tests/t_crc.c
- src/lib/crypto/crypto_tests/t_hmac.c
- src/plugins/kdb/ldap/ldap_util/deps
- src/plugins/kdb/ldap/ldap_util/kdb5_ldap_services.c
- src/plugins/kdb/ldap/ldap_util/kdb5_ldap_services.h
- src/plugins/kdb/ldap/libkdb_ldap/deps
- src/plugins/kdb/ldap/libkdb_ldap/ldap_service_stash.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_service_stash.h
- src/plugins/kdb/ldap/libkdb_ldap/libkdb_ldap.exports
- src/slave/deps
- src/slave/kproplog.c
- src/tests/gssapi/deps
- src/tests/gssapi/t_prf.c
- src/util/support/Makefile.in
- src/util/support/deps
- src/util/support/hex.c
- src/util/support/libkrb5support-fixed.exports
- src/util/support/t_hex.c
These commits are preparatory for the non-backport part of PR #723.
> Hex support functions

- src/appl/gss-sample/gss-server.c
- src/appl/user_user/client.c
- src/lib/krb5/krb/authdata.c
- src/tests/hammer/kdc5_hammer.c
Since there have been a pile of leak fixes recently, I figured I'd get these out rather than having them duplicated.  Now that the `register` work has merged, there shouldn't be conflicts with master.
> A round of (mostly leak) fixes

- src/lib/krb5/ccache/cc_memory.c
- src/lib/krb5/ccache/t_cc.c
[This bug is serious enough to deserve a backport, but the fix is more complicated than I'm normally comfortable backporting.  I will probably decide to backport it but I'm still considering.]
A memory ccache iterator stores an alias into the cache object's
linked list of credentials.  If the cache is reinitialized while the
iterator is active, the alias becomes invalid.  Also, multiple handles
referencing the same memory ccache all use aliases to the same data
object; if one of the handles is destroyed, the other contains a
dangling pointer.
Fix the first issue by adding a generation counter to the cache and to
cursors, incremented each time the cache is initialized or destroyed.
Check the generation on each cursor step and end the iteration if the
list was invalidated.  Fix the second …
> Fix bugs with concurrent use of MEMORY ccaches

- src/Makefile.in
- src/configure.in
- src/kadmin/dbutil/t_tdumputil.py
- src/tests/jsonwalker.py
- src/tests/t_cve-2012-1014.py
- src/tests/t_cve-2012-1015.py
- src/tests/t_hostrealm.py
- src/tests/t_kdb.py
- src/tests/t_keytab.py
- src/tests/t_mkey.py
- src/tests/t_otp.py
- src/tests/t_tabdump.py
- src/util/Makefile.in
- src/util/k5test.py
- src/util/princflags.py
Look for python3 in configure.in and verify that we got it.  Convert
test code to conform to Python 3.
> Convert Python tests to Python 3

- .travis.yml
- src/lib/krad/t_daemon.py
- src/tests/jsonwalker.py
- python-cjson seems dead upstream and in particular has no python3 version: https://github.com/AGProjects/python-cjson/issues/6
- Update paste dependency to python3
- Fix pyrad-depdendent tests
> CI updates for python3

- src/util/ss/execute_cmd.c
> Check malloc() result in ss_execute_command()

- src/kadmin/ktutil/ktutil_funcs.c
[Some of the leaks fixed by this commit showed up under asan after we added ktutil addent tests in PR #670.  Coincidentally Bean Zhang also reported six minor memory leaks discovered by a static analysis tool today, one of which was in ktutil_add().]
In ktutil_add(), free allocations on success as well as failure.
Change all early returns to jumps to the cleanup label.  Free the
password buffer and unparsed principal name.  Do list manipulation as
the final step to simplify cleanup.  Reported by Bean Zhang.
> Fix multiple leaks in ktutil addent

- src/lib/krb5/krb/t_pac.c
- src/plugins/kdb/test/kdb_test.c
- src/tests/gssapi/t_s4u.py
Also fixup some of the comment in the recently added PAC API tests.
>  Add a test for cross realm S4U2Self using referrals

- doc/admin/admin_commands/kdb5_util.rst
- doc/admin/database.rst
- src/kadmin/dbutil/dump.c
- src/kadmin/dbutil/kdb5_create.c
- src/kadmin/dbutil/kdb5_util.c
This is follow-up from http://mailman.mit.edu/pipermail/kerberos/2018-September/022066.html .
> kdb5_util doc fixups and a small behavior change

- src/lib/krb5/ccache/cc_kcm.c
This is a follow-on to #859 and is based on that (only the top commit is new).  Requested by @jhrozek from SSSD.
> Retry KCM writes once

- doc/mitK5features.rst
This update contains the text that will be used in the README and release announcement.
> Update features list for 1.17

- doc/admin/conf_files/krb5_conf.rst
- src/man/krb5.conf.man
> Fix spelling of auth_to_local example

- src/clients/klist/klist.c
- src/kadmin/cli/kadmin.c
- src/kadmin/dbutil/kdb5_mkey.c
- src/kadmin/server/ipropd_svc.c
- src/lib/gssapi/krb5/gssapi_krb5.c
- src/lib/gssapi/krb5/k5sealv3.c
- src/lib/gssapi/krb5/k5sealv3iov.c
- src/lib/kdb/kdb_convert.c
- src/plugins/kdb/ldap/ldap_util/kdb5_ldap_services.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_create.c
- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
- src/plugins/preauth/pkinit/pkinit_srv.c
- src/tests/hammer/kdc5_hammer.c
Here are (some) things flagged by various analyzers in a pass today.  If there's a better way I can organize any of this please let me know.
> Static analysis update 2019-05-02

- src/clients/klist/klist.c
- src/lib/krb5/ccache/ccfns.c
- src/tests/t_referral.py
Here is the ticket 8764 option 4 implementation.
> Stop double-caching referral tickets

- src/lib/krb5/rcache/rc_file2.c
Coverity flags the following code in rc_file2.c as a NEGATIVE_RETURNS defect:
if (avail_offset == -1) {
if (nread == 0 || ts_after(now, ts_incr(rec1_stamp, skew)))
avail_offset = record_offset;
else if (nread == 1 || ts_after(now, ts_incr(rec2_stamp, skew)))
avail_offset = record_offset + RECORD_LEN;
}
if (nread < 2 || rec1_stamp == 0 || rec2_stamp == 0)
return write_record(fd, avail_offset, tag, now);
on the grounds that it might pass avail_offset=-1 to write_record(), and from there to lseek().
The code here is implementing the following logic:
* If a slot is beyond the end of the file, or empty, or expired, it is available for writing.  We want to track the first available offset.
* If a slot is beyond the end of the file or empty, it terminates the search, because a previous store of …
> Address Coverity defect in new replay cache code

- src/lib/krb5/krb/pac.c
- src/lib/krb5/krb/t_pac.c
Use strcmp instead of trying to parse pac principal, in
order to avoid relying on the provided name type. Windows
seem to be using KRB5_NT_MS_PRINCIPAL for enterprise name
type too, and this change allows us to verify it correctly.
This is an alternative fix for #744
> Simplify pac verify logic based on Heimdal implementation

- src/tests/softpkcs11/main.c
Coverity claimed to find twelve defects in the softpkcs11 code.  None of these are important because the code is only used for testing, but we don't like the defect count to go up.  Nine of the defects are addressed here so far:
* read_conf_file() leaks its file handle.
* OPENSSL_ASN1_MALLOC_ENCODE() can leave behind its B variable as a freed pointer, causing a double-free in the exit handler of add_certificate().  This case probably can't happen because it would require `i2d_##T` to succeed the first time but fail the second time.  (Four defects.)
* add_st_object() uses the wrong test for an empty table slot (it tests whether the table is NULL, not the slot).
* It doesn't check the return value of asprintf() in two places.  (Two defects.)
* sprintf_fill() doesn't initialize its ap …
> Fix Coverity defects in soft-pkcs11 test code

- src/util/k5test.py
In k5test.py, if a daemon process exits before we terminate it,
display the exit status.  If a daemon process generates output beyond
the sentinel, display the output before terminating the process.
[This change is particularly useful when investigating memory bugs in daemon processes using asan, as it displays the asan output which otherwise disappears into the k5test pipe.]
> Display daemon output in Python test scripts

- src/util/k5test.py
[I ran into a daemon issue in a recent PR and PR #962 was useful, but the test script threw a Python exception trying to kill the KDC process which had already been reaped.  There is also a possibility that a daemon might crash in a way that isn't visible to the client side of the tests, in which case the script might exit successfully even though we noticed and logged an early exit.  This PR corrects both problems.]
If a daemon exits early and we detect it with check_daemon(), avoid
trying to terminate it again as the process entry will have been
reaped.  Check all daemons on successful exit and exit with an error
if any daemons exited early.
Also remove a piece of Python 2.5 compatibility code which is no
longer relevant with Python 3.
> Improve daemon checking in Python test scripts

- src/lib/gssapi/krb5/duplicate_name.c
- src/lib/rpc/clnt_tcp.c
Fix three pedantic bugs.  hashtable one is new; the rest are newly detected as a result of tooling updates on our end.
> Static analysis reports (2019-08-30)

- src/kprop/kpropd.c
[See http://mailman.mit.edu/pipermail/kerberos/2020-January/022388.html and following.]
In kpropd, don't set a remote address in the auth context, so that
propagation can work if the client address is changed by a NAT.
> Allow kprop over NATs

- src/kdc/kdc_util.c
- src/plugins/kdb/test/kdb_test.c
- src/tests/gssapi/t_s4u.py
As discussed, I tested each commit with the broken client and it gets an error.
> RBCD KDC fixups

- src/include/kdb.h
- src/kdc/kdc_util.c
- src/tests/gssapi/t_s4u.py
- src/tests/t_audit.py
Per MS-SFU errata changes from 2019/12/09:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-winerrata/68c4fd08-207c-4353-b59d-4d281edfb6bf
> Change KDC constrained-delegation order of precedence

- src/util/et/error_message.c
Samba dumps core on SIGSEGV in atexit() procedure. Problem was identified the et_list is not NULLed after free the list so its value points to freed memory and SIGSEGV is raised in remove_error_table() . also the "et" removal is unsafe and should fail if "et" is pointed by the first member in the list.
> Employ safe coding practices also in src/util/et/error_message.c

- src/clients/ksu/main.c
Commit d439e370b70f7af4ed2da9c692a3be7dcf7b4ac6 (ticket 8800) caused
ksu to ignore KRB5CCNAME from the environment.  ksu uses euid
switching to access the source cache, and should honor KRB5CCNAME to
find the ccache to potentially authorize the su operation.
Add a helper function init_ksu_context() to create the ksu context,
with explicit code to honor KRB5CCNAME using
krb5_cc_set_default_name().
> Make ksu honor KRB5CCNAME again

- .gitignore
- doc/admin/conf_files/krb5_conf.rst
- src/include/k5-int.h
- src/include/krb5/krb5.hin
- src/lib/gssapi/generic/gssapi_ext.h
- src/lib/gssapi/krb5/accept_sec_context.c
- src/lib/gssapi/spnego/gssapiP_negoex.h
- src/lib/gssapi/spnego/negoex_ctx.c
- src/lib/gssapi/spnego/spnego_mech.c
- src/lib/krb5/krb/mk_req_ext.c
- src/plugins/gssapi/negoextest/main.c
- src/tests/gssapi/Makefile.in
- src/tests/gssapi/common.c
- src/tests/gssapi/common.h
- src/tests/gssapi/deps
- src/tests/gssapi/t_bindings.c
- src/tests/gssapi/t_bindings.py
- src/tests/gssapi/t_negoex.py
This is a subset of PR #685, following recent discussions on krbdev.
> Match Heimdal behavior for channel-bindings

- src/lib/gssapi/krb5/accept_sec_context.c
[Found this with asan while checking a different PR.  CBT support hasn't gone into a release yet, so I'm combining this into the implementation ticket.]
In check_cbt(), use a local variable to hold the retrieved authdata
list, and free it before returning.
> Fix leak in KERB_AP_OPTIONS_CBT server support

- src/lib/krb5/krb/s4u_creds.c
Isaac reminded me of https://colabti.org/irclogger/irclogger_log/krbdev?date=2020-01-03#l21 wherein I concluded that the second cache check in krb5_get_credentials_for_user() could probably be omitted.
The change is easy enough.  A few tests have to be adjusted because they look for a trace log message corresponding to the second cache lookup.
However, I did notice that kvno winds up caching under the final result, rather than the requested client principal:
====== cross-realm S4U2Self with enterprise name ======
*** [110] Executing: ./t_s4u e:enterprise@abc@NOREALM - /me/krb5/build/tests/gssapi/testdir/1/keytab
*** [110] Spawning shell
$ /me/krb5/build/clients/kvno/kvno -U enterprise@abc@NOREALM user@SREALM
user@SREALM: kvno = 1
$ /me/krb5/build/clients/klist/klist
Ticket cache: …
> Remove S4U2Self post-canonicalization cache check

- src/kdc/kdc_util.c
> Improve KDC alias checking for S4U requests

- src/kdc/do_tgs_req.c
- src/kdc/kdc_util.c
- src/kdc/kdc_util.h
- src/tests/t_u2u.py
As mentioned in #1106, see bug below. Note that I don't have a way to test it, i'll ask Dario:
https://bugzilla.redhat.com/show_bug.cgi?id=1836630
> Allow aliases in U2U 2nd ticket matching

- doc/tools/doxybuilder_types.py
- src/tests/gssapi/t_s4u.py
- src/tests/t_kdb.py
- src/tests/t_mkey.py
- src/tests/t_referral.py
- src/tests/t_sesskeynego.py
- src/util/k5test.py
Address all warnings issued by "python -Werror::DeprecationWarning"
in the test suite and doc build, as of Python 3.8.2.
> Fix Python deprecation warnings

- src/lib/gssapi/krb5/accept_sec_context.c
- src/lib/krb5/krb/s4u_creds.c
- src/lib/krb5/rcache/rc_base.c
- src/plugins/certauth/test/main.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_create.c
I believe these were found by clang.
> Static analyzer fixes

- src/lib/krb5/libkrb5.exports
- src/tests/threads/Makefile.in
- src/tests/threads/t_rcache.c
tell t_rcache.c that commit
dcb853ac32779b173f39e19c0f24b0087de8577
has modernized and simplified replay cache.
> update t_rcache.c w.r.t. to replay cache changes

- src/kadmin/dbutil/kadm5_create.c
- src/kadmin/dbutil/kdb5_create.c
- src/kadmin/ktutil/ktutil_funcs.c
- src/kdc/do_tgs_req.c
- src/kprop/kpropd.c
- src/kprop/kproplog.c
- src/lib/gssapi/krb5/gssapiP_krb5.h
- src/lib/gssapi/krb5/gssapi_krb5.c
- src/lib/gssapi/krb5/set_ccache.c
- src/lib/gssapi/spnego/spnego_mech.c
- src/lib/kadm5/srv/pwqual_dict.c
- src/lib/kdb/kdb5.c
- src/lib/kdb/kdb_convert.c
- src/lib/krad/remote.c
- src/lib/krb5/krb/gic_keytab.c
- src/lib/krb5/krb/s4u_authdata.c
- src/lib/krb5/krb/send_tgs.c
- src/lib/krb5/os/dnssrv.c
- src/lib/krb5/os/sendto_kdc.c
- src/plugins/audit/kdc_j_encode.c
- src/plugins/kdb/db2/adb_policy.c
- src/plugins/kdb/db2/kdb_db2.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_principal.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_principal2.c
- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
- src/plugins/preauth/pkinit/pkinit_identity.c
- src/util/profile/prof_get.c
Most of these are unimportant leaks, but the tool flags them as "Important", so here we are.  That said, this PR does not touch ksu, sample/test code, or rpc.
The commits are separated for my own convenience when working with them - I'm happy to modify that as needed.
> Another round of static analyzers

- src/lib/krb5/krb/pac.c
We'll need the same for PAC ticket-signature, we could also check that they have the same checksum type and the same RODCIdentifier since the same key is supposed to be used.
> Fix verification of PAC KDC signature issued by RODC

- src/lib/krb5/ccache/ccselect.c
- src/tests/gssapi/t_gssapi.py
> Allow init_sec_context() with no default realm

- src/lib/gssapi/mechglue/g_initialize.c
There is at least one case (with flatpaks) where configuration files
in the special read-only /etc all have (time_t)0 as mtime.
This causes the current code to not read the configuration files even
once because the comparison in check_link_mtime() assumes that a mtime
on disk is always greater than 0 and the initial "high" value
g_confFileModTime is set to 0.
To address this we change the initial high value to the be the "invalid"
value (time_t)-1
Then we special case the check in check_link_mtime() to always,
unconditionally, load the configuration file when the initial '-1' value
is seen.
After the first time the code goes through loadConfigFiles() the value
of g_confFileModTime will be set to the highest mtime found, which will
work correctly even if that "highest" value is the …
> Always read the configuration files the first time

- src/po/Makefile.in
- src/po/ka.po
Hello,
Here's full translation of latest git pot file (regenerated from source several days ago) of Kerberos to Georgian.
> po: Add Georgian translation

- src/appl/simple/client/sim_client.c
In sim_client.c, remove the calls to krb5_gen_portaddr() and krb5_gen_replay_name() as they don't do anything after commit dcb853ac32779b173f39e19c0f24b0087de85771.  Remove them, and include krb5.h plus appropriate system headers rather than k5-int.h.
> Avoid using internal APIs in sim_client

- src/config/win-pre.in
We have identified this vulnerability in BlackDuck Binary Analysis tool.
More about control flow guard: https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard
> Adding security flag control flow guard to Windows builds

- src/appl/gss-sample/gss-client.c
- src/appl/gss-sample/gss-server.c
- src/clients/klist/klist.c
- src/clients/ksu/authorization.c
- src/clients/ksu/ccache.c
- src/clients/ksu/heuristic.c
- src/clients/ksu/krb_auth_su.c
- src/clients/ksu/ksu.h
- src/clients/ksu/main.c
- src/kadmin/cli/keytab.c
- src/kadmin/ktutil/ktutil.c
- src/kprop/kpropd.c
- src/lib/gssapi/krb5/export_cred.c
- src/lib/gssapi/krb5/val_cred.c
- src/lib/kadm5/srv/server_kdb.c
- src/lib/krb5/ccache/cc_kcm.c
- src/lib/krb5/ccache/ccfns.c
- src/lib/krb5/keytab/kt_file.c
- src/plugins/kdb/ldap/libkdb_ldap/ldap_realm.c
This patch fixes a number of memory leaks. Most are in the utilities but there are a few in the libraries.
> Fix memory leaks

- src/plugins/preauth/pkinit/pkinit_crypto_openssl.c
Commit f745c9a9bd6c0c73b944182173f1ac305d03dc3a uses ECDSA_SIG_set0(), which was added in OpenSSL 1.1.  Add a compatibility version for OpenSSL 1.0.
Commit bdcd6075bd4593c8f67722ce075c9519faec58b7 uses EVP_PKEY_get_base_id(), which was added in OpenSSL 1.1.  Add a compatibility macro to use the old name for OpenSSL 1.0.
Commit 0f870b1bcad960fd5319a3f97aafd7f4a289e2fb added ECDH support, but did not change the OpenSSL 1.0 versions of encode_spki(), decode_spki(), or generate_dh_pkey() to work with elliptic curve public keys.  In each function, check the key type and skip the DH-specific handling for key types other than DH.
[I've been debating whether it's time to remove the OpenSSL 1.0 support, and have been remiss at testing recent changes against it.  OSS-Fuzz appears to use a container …
> Fix OpenSSL 1.0 and 1.1 support in PKINIT

- src/clients/klist/klist.c
- src/kadmin/dbutil/dump.c
- src/kdc/ndr.c
- src/lib/kdb/decrypt_key.c
- src/lib/rpc/svc_auth_gss.c
- src/lib/rpc/svc_udp.c
- src/util/support/threads.c
Here are fixes for problems of various severity detected by static analysis.
> Fix various issues detected by static analysis

- src/include/kdb.h
- src/lib/kdb/kdb5.c
- src/lib/kdb/libkdb5.exports
This allows to write a plugin which will load another plugin to extend its functionality.
> Allow kdb plugin reentrancy

- src/lib/gssapi/mechglue/g_mechattr.c
gss_inquire_attrs_for_mech() can return successfully with *mech_attrs or *known_mech_attrs set to GSS_C_NO_OID_SET, which is at best inconvenient as gss_test_oid_set_member() does not allow GSS_C_NO_OID_SET as an input.  Create empty sets instead.
> Avoid gss_inquire_attrs_for_mech() null outputs

- src/lib/krb5/os/dnsglue.c
- src/lib/krb5/os/dnsglue.h
- src/lib/krb5/os/dnssrv.c
Use k5input to make the dnsglue.c and dnssrv.c functions simpler and more robust.  Rename the dnsglue functions to use the now-preferred k5_ prefix instead of krb5int_.  Use stdint type names instead of unsigned char and unsigned short.  Remove some out-of-date comments.
> Refactor dnsglue functions using k5input
